### ISSUE TITLE
Error installing or updating via fisher or running tide bug-report

### ISSUE THREAD

**Issue by cliffrowley** [IlanCosman/tide#101]
Installing or updating via fisher, or running `tide bug-report` yields the following error:

```console
~/.config/fish/functions/_tide_sub_bug-report.fish: Command substitutions not allowed
from sourcing file ~/.config/fish/functions/_tide_sub_bug-report.fish
        called on line 178 of file ~/.config/fish/functions/fisher.fish

in function “fisher”
        called on standard input
        with parameter list “update”

source: Error while reading file “/home/myusername/.config/fish/functions/_tide_sub_bug-report.fish”
```

I'm assuming that this could either be a bug in tide, or a bug in fisher, or it could simply be an issue with my version of fish, but whilst I am not new to fish I have only just started using fisher and tide so it could just as easily be user error.

#### Steps to reproduce

1. Install fish and fisher
2. Run `fisher install IlanCosman/tide` or `fisher update` when tide is already installed
3. See error

#### Environment

- Operating System: Debian 10 (Buster)
- Fish version: 3.0.2
- Output of `tide bug-report`: (unable to run, same error)

**Comment by IlanCosman** [comment]
Tide doesn't support Fish 3.0.2. Try installing the latest stable version [from the PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3).

**Comment by cliffrowley** [comment]
@IlanCosman aha thank you, did I miss this in the documentation?

**Comment by IlanCosman** [comment]
Yah: https://github.com/IlanCosman/tide#system-requirements

**Comment by cliffrowley** [comment]
Oof. I guess I'm having one of those days and must have read straight past it.. sorry for the noise and thank you for the clarification!

I'll close this issue now (on the plus side, at least if someone else searches the tide issues they will find this one!)
