### ISSUE TITLE
Error adding custom prompt item to far left or right

### ISSUE THREAD

**Issue by Barbarossa93** [IlanCosman/tide#102]
#### Describe the bug

I have a couple of simple prompt items that I have on my far left and right prompts. After updating to 4.1, I get this error message after putting the taskwarrior item on the far right:
```
set_color: Expected argument for option b

~/.config/fish/functions/_tide_right_prompt.fish (line 61): 
                set_color -b $color
                ^
in function '_tide_fetch_right_prompt_items'
	called on line 1 of file ~/.config/fish/functions/_tide_right_prompt.fish
in command substitution
	called on line 2 of file ~/.config/fish/functions/_tide_right_prompt.fish
in function '_tide_right_prompt'
	called on line 12 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution

(Type 'help set_color' for related documentation)
```
And this error message for my dna item on the far left:
```
~/.config/fish/functions/_tide_left_prompt.fish (line 38): 
                set_color -b $color
                ^
in function '_tide_left_prompt'
	called on line 13 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution

(Type 'help set_color' for related documentation)
```
The contents of my custom propts are:
```
function _tide_item_taskwarrior
    if type -q task
        set -l count (task status:pending count)
        if [ $count -gt 0 ]
            set_color magenta
            echo '' $count
        else
            set_color normal
            echo ""
        end
    end
end
```
and
```
function _tide_item_dna
    set_color cyan
    echo ''
    set_color normal
end
```
It's likely I need to include something to my items but I'm not sure what =/

#### Steps to reproduce

1. try to add custom prompt items to left and right side prompt
2. See error message
3. My fish-fu sucks, better ask on github

#### Expected behavior

I shouldn't see the error messages. My prompt items should run fine as they did before updating to 4.1

#### Environment (please complete the following information)

- Operating System:  Arch Linux
- Output of `tide bug-report`: 

```console
fish, version 3.1.2
tide, version 4.1.0
xterm-termite
```

**Comment by IlanCosman** [comment]
Can you post the output of `tide bug-report --verbose`?

**Comment by Barbarossa93** [comment]
It's quite a doozy, looks like something went wrong with my setup: https://gist.github.com/Barbarossa93/57dbbf412cce30d0476e3e0dfc977b62

**Comment by Barbarossa93** [comment]
That was with the `taskwarrior` item on the far right. Do you need me to do the `dna` item on the far left as well?

**Comment by IlanCosman** [comment]
I think I see the issue. Tide requires a `bg_color` for each item. So if you just `set -U tide_taskwarrior_bg_color normal` (and the same for dna), it should work. I recently removed the bg_color validation where Tide would check if it existed and use normal if not. I wasn't properly considering custom items, I'll have to consider this further.

**Comment by Barbarossa93** [comment]
Perfect, you were right! Thank you! I'll let you decide whether to close this; sounds like this is a legitimate bug

**Comment by IlanCosman** [comment]
I think I will close this as fish 3.2 will fix this: https://github.com/fish-shell/fish-shell/issues/7154. I'm also putting together a wiki page about custom items that will explicitly state this requirement.
