### ISSUE TITLE
Unknown command: __fish_pipestatus_with_signal

### ISSUE THREAD

**Issue by gokulsoumya** [IlanCosman/tide#103]
#### Describe the bug
Whenever a command in a pipe fails, tide triggers an error:

```
❯ fish: Unknown command: __fish_pipestatus_with_signal
~/.config/fish/fisher/functions/_tide_item_status.fish (line 20):
            __fish_pipestatus_with_signal $_tide_last_pipestatus | string replace 'SIG' '' | string join '|'
            ^
in function '_tide_item_status'
	called on line 1 of file ~/.config/fish/fisher/functions/_tide_right_prompt.fish
in command substitution
	called on line 45 of file ~/.config/fish/fisher/functions/_tide_right_prompt.fish
in function '_tide_fetch_right_prompt_items'
	called on line 1 of file ~/.config/fish/fisher/functions/_tide_right_prompt.fish
in command substitution
	called on line 2 of file ~/.config/fish/fisher/functions/_tide_right_prompt.fish
in function '_tide_right_prompt'
	called on line 12 of file ~/.config/fish/fisher/functions/_tide_prompt.fish
```

#### Steps to reproduce

1. Run `true | false`
2. See error

#### Expected behavior

Correct status codes of the pipe commands shown and no error.

#### Environment (please complete the following information)

- Operating System: Arch Linux
- Output of `tide bug-report`:
```console
fish, version 3.1.2-2086-ge423a58e2
tide, version 4.1.0
alacritty
```

#### Additional context

The function was removed in commit https://github.com/fish-shell/fish-shell/commit/293a3a628d6d5d6220518e3991e989b38cf50c8e and recommends to use `fish_status_to_signal`.

**Comment by IlanCosman** [comment]
Yah, I have a `fish_v3.2.0` branch. When 3.2 releases I'll merge it in.

**Comment by AngryDeveloper** [comment]
Just to let you know (but I guess you already do) 3.2.0 was just released https://github.com/fish-shell/fish-shell/releases/tag/3.2.0 :)

**Comment by IlanCosman** [comment]
Yah... Since Tide can only be compatible with 3.2 or 3.1.2, I'll wait until Brew and perhaps Arch update their packages 😞

**Comment by emvoo** [comment]
temporary solution for me was to `fisher remove IlanCosman/tide && fisher install IlanCosman/tide@new_fish_v3.2.0`

**Comment by AdrianTM** [comment]
Not sure if related to this fish update, but for me git info is not showing with tide > 4 and fish == 3.2
I could install tide 3.2.0 but that shows this __fish_pipestatus_with_signal error

Debian also has either too old fish, or if I install from fish official repo too new. Whatever I choose seems to break tide in one way or another.

**Comment by IlanCosman** [comment]
It's `fisher install IlanCosman/tide@new_fish_v3.2.0` not `fisher install IlanCosman/tide@v3.2.0`. Easy to confuse 😂 

> Whatever I choose seems to break tide in one way or another.

Yah sorry, this is what I get for using internal fish functions. The fix is simply to change `__fish_pipestatus_with_signal` to `fish_status_to_signal` in `_tide_item_status.fish`.

**Comment by IlanCosman** [comment]
Woops wrong button 😅

**Comment by IlanCosman** [comment]
Alright, there, Fish 3.2 support has been merged in.
