### ISSUE TITLE
Detect when custom item’s bg_color is not set

### ISSUE THREAD

**Issue by Debilski** [IlanCosman/tide#104]
#### Is your feature request related to a problem? Please describe

I created a function `_tide_item_myitem` but didn’t set the universal variable for the background colour `set -U tide_myitem_bg_color normal`. Now with each prompt, fish would print the following:

    set_color: Expected argument for option b

    ~/.config/fish/functions/_tide_right_prompt.fish (line 61):
                    set_color -b $color
                    ^
    in function '_tide_fetch_right_prompt_items'
            called on line 1 of file ~/.config/fish/functions/_tide_right_prompt.fish
    in command substitution
            called on line 2 of file ~/.config/fish/functions/_tide_right_prompt.fish
    in function '_tide_right_prompt'
            called on line 12 of file ~/.config/fish/functions/_tide_prompt.fish
    in function '_tide_prompt'
    in command substitution

#### Describe the solution you'd like

Detect in tide that the variable is missing and print a more helpful error message or apply a default colour.

**Comment by IlanCosman** [comment]
Yah, I removed this feature without thinking about custom items. My apologies. However, 

1. It's a simple fix 
2. This is really a [Fish problem](https://github.com/fish-shell/fish-shell/issues/7154), which will be solved when 3.2 releases.

So yeah, I messed up, but I don't plan on changing it right now given the circumstances. Thanks for filing 😄
