### ISSUE TITLE
Add option to show command duration time in milliseconds

### ISSUE THREAD

**Issue by xolve** [IlanCosman/tide#11]
**Is your feature request related to a problem? Please describe.**
Seconds is too large a granularity for me.

**Describe the solution you'd like**
Add option to always show display execution time of commands. Can switch to seconds if execution time is more than `tide_cmd_duration_threshold`

**Comment by IlanCosman** [comment]
You can already do this 😄 Set `tide_cmd_duration_threshold` to something small (it's in milliseconds) and set `tide_cmd_duration_decimals` to anything greater than 0.
