### ISSUE TITLE
Rainbow theme renders directory listings in light grey over light green when SSH-ing

### ISSUE THREAD

**Issue by jeremymeyers** [IlanCosman/tide#110]
#### Describe the bug

I'm not actually sure whether this is a Tide thing or a Fish thing, but when SSH-ing and then doing a ls, the result is unreadable:

<img width="492" alt="Screen Shot 2021-03-02 at 3 56 35 PM" src="https://user-images.githubusercontent.com/3514095/109714160-1099ca80-7b70-11eb-8d2d-694bf17abc77.png">

**Comment by IlanCosman** [comment]
Could you verify which one it is? You can run a clean fish instance with `HOME=(mktemp -d) fish`.

**Comment by jeremymeyers** [comment]
D'oh. confirming its a Fish thing. Will post there.
