### ISSUE TITLE
git version incompatibility

### ISSUE THREAD

**Issue by AdrianTM** [IlanCosman/tide#114]
Not quite a bug, more like an incompatibility, it doesn't work with Debian Buster git version 
> git version 2.20.1

I had to remove "--show-current" from _tide_item_git branch command
> git branch --show-current

Not sure if that works fine in newer git version, but it would be nice to remove --show-current to make it work for the people who use current Debian. or add a check for the git version. 

actually I had to add "git rev-parse --abbrev-ref HEAD" instead of "git --show-current" to show the current branch for older git.

**Comment by IlanCosman** [comment]
It works just fine on newer git versions. Why Debian gotta be so slow 😞 Could you submit a PR to change it to `git rev-parse`?

**Comment by AdrianTM** [comment]
Yeah, it's unfortunate, but in general we cannot assume people use the latest versions of everything. Not sure about the  "git rev-parse --abbrev-ref HEAD" if it adds overhead, I don't want to make things slower for everybody. 

Can you profile this on your system and see if it's equivalent to --show-version, do you get similar times with
>  time git rev-parse --abbrev-ref HEAD

vs.

> time git --show-current

**Comment by IlanCosman** [comment]
Yah, I profiled this a while ago, there's no meaningful difference in speed.

**Comment by AdrianTM** [comment]
Thanks, I will send a PR

**Comment by AdrianTM** [comment]
I sent the PR, but it failed I guess because I removed the template, I thought such a small PR doesn't need that...

**Comment by IlanCosman** [comment]
That is not the reason it failed.

**Comment by AdrianTM** [comment]
Made the change as request, it still fails, sorry I thought it was a simpler fix.
