### ISSUE TITLE
Blank screen after `tide configure`

### ISSUE THREAD

**Issue by fffed** [IlanCosman/tide#118]
#### Steps to reproduce

1. Run `tide configure`
2. Go through all steps till the end
3. Nothing is showing

#### Expected behavior

After passing through configuration the prompt appears

#### Screenshots
![tide](https://user-images.githubusercontent.com/47778360/110337817-60c4d100-8037-11eb-8037-c58e9b9bc0b1.gif)

#### Environment (please complete the following information)

- Operating System: Ubuntu 20.10
- Output of `tide bug-report`: 
fish, version 3.2.0
tide, version 4.2.0
xterm-kitty

```console

```

**Comment by fffed** [comment]
It's weird, 4 consecutive attempts were with the result I've described above but the last one was successful.

**Comment by IlanCosman** [comment]
Yah this is a known bug, I'd like to wait for 3.2.1 and see if it goes away, but I'll try to track it down after that 😄

**Comment by IlanCosman** [comment]
@fffed Does this issue still appear for you in Fish 3.2.1?
