### ISSUE TITLE
fish: Unknown command: nvm

### ISSUE THREAD

**Issue by recteurlp** [IlanCosman/tide#129]
```
fish: Unknown command: nvm
~/.config/fish/functions/_tide_item_nvm.fish (ligne 1) : 
nvm current
```

Is this a missing dependency (nvm.fish) in fisher ?

I added `if command -v nvm` to hide the msg

**Comment by IlanCosman** [comment]
That means you had nvm installed when you installed/ran the configuration wizard for tide. Tide will automatically enable the nvm item in that case.

Run `set -e tide_right_prompt_items[(contains --index nvm)]`

**Comment by IlanCosman** [comment]
oh whoops, that should be `set -e tide_right_prompt_items[(contains --index nvm $tide_right_prompt_items)]` my bad.

**Comment by vamega** [comment]
Is it possible to add `nvm` integration after the configuration is done?

**Comment by IlanCosman** [comment]
Yes? You'd just add it like any other item.

**Comment by douglascamata** [comment]
@IlanCosman I have `nvm` installed and I'm getting a `nvm: unknown flag or command "current"`. I also have installed the nvm plugin through jorgebucaran/fish-nvm 🤔

**Comment by douglascamata** [comment]
Nevermind, a `fisher update` solved it.
