### ISSUE TITLE
First command in new shell is not colored but gray

### ISSUE THREAD

**Issue by pdanpdan** [IlanCosman/tide#132]
#### Describe the bug

When a new shell is opened the commands on the command line are grey, but only until the first enter is pressed.

#### Steps to reproduce

1. Open a new shell
2. Type `ls` - it will be gray
3. Press enter
4. Type `ls` again - it will be colored

#### Expected behavior

The commands should be colored.

#### Screenshots

No screenshots

#### Environment (please complete the following information)

- Operating System: e.g. Ubuntu 20.10
- Output of `tide bug-report`:

```console
fish, version 3.2.1
tide, version 4.2.0
xterm-256color
```
#### Additional context

Latest tide from github (c6a1ad45c7735e0ca473d5dd3367b35430a590a8)
Settings:
- true color
- sparse

**Comment by branchvincent** [comment]
duplicate of #130 (see workaround here https://github.com/IlanCosman/tide/issues/130#issuecomment-802434603)

**Comment by pdanpdan** [comment]
Sorry, missed it. Closing it as duplicate.
