### ISSUE TITLE
4.30: slow performance with unknown command

### ISSUE THREAD

**Issue by markstos** [IlanCosman/tide#133]
#### Describe the bug

This short video demonstrates the bug and also shows my prompt configuration in case that's part of the trigger:

https://user-images.githubusercontent.com/25829/112340712-33169380-8c97-11eb-91ab-a42b5da08301.mp4

The videos me typing "boom", and then a clear pause before the prompt returns.

For a "control" case, it also shows typing "true", which returns instantly. 

I have not tried tide configurations to see if others also trigger it.

#### Steps to reproduce

1. Type "boom"
3. See pause

#### Expected behavior

I expect the prompt to return immediately.

#### Environment (please complete the following information)

- Operating System: Arch Linux
- Output of `tide bug-report`: 

```console
fish, version 3.2.0
tide, version 4.3.0
alacritty
```

**Comment by IlanCosman** [comment]
This is a general Fish thing: https://github.com/fish-shell/fish-shell/issues/7841 Thanks for filing though 😄

**Comment by markstos** [comment]
Thanks. I like "command not found" handling,  but I had no idea it existed with Fish/Arch.
