### ISSUE TITLE
prompt shows ... if there are emojis in item output or directory names

### ISSUE THREAD

**Issue by mknj** [IlanCosman/tide#134]
#### Describe the bug

The beginning of the prompt is messed up if there are emojis in the prompt line

#### Steps to reproduce

Run `mkdir "dirname containing emoji (🐛)"; cd dir*`

#### Expected behavior

The first character of the prompt does not change

#### Screenshots

![image](https://user-images.githubusercontent.com/4385662/112800352-d4bf2b80-906f-11eb-91fa-9d01966a4f79.png)

#### Environments

- Microsoft WSL running "18.04.1 LTS (Bionic Beaver)" +  Microsoft Terminal
- Ubuntu 20.10 + gnome-terminal

```console
fish, version 3.2.1
tide, version 4.3.2
xterm-256color

```

#### Additional context

This is really annoying if you try to put colored emojis in your item. i.e.
![image](https://user-images.githubusercontent.com/4385662/112801444-30d67f80-9071-11eb-88b2-1c4c00d92222.png)

**Comment by mknj** [comment]
The ellipsis vanishes when resizing the window, but it is displayed again when entering commands.

**Comment by IlanCosman** [comment]
The problem is that I've been using `string length` as a proxy for string width.

@faho Could you help me out?

```fish
function foo -a char
    set -l stringLength (string length "$char")
    
    echo $stringLength
    
    printf '%s' $char
    string repeat --max (math $COLUMNS - $stringLength) -
end
```

![string-length-emojis](https://user-images.githubusercontent.com/6318351/112858156-75105280-9066-11eb-96d7-e6c45f8dd664.png)


Is there any way to have `string length` use the values of `fish_emoji_width`/`fish_ambiguous_width`? Or otherwise calculate the width of a string?

**Comment by faho** [comment]
>Is there any way to have string length use the values of fish_emoji_width/fish_ambiguous_width? Or otherwise calculate the width of a string?

No. It's *length*, not *width*. https://github.com/fish-shell/fish-shell/issues/4012 asks for a `string width` subcommand.

**Comment by mknj** [comment]
Would something like https://github.com/flmnt/graphemer -> splitter.countGraphemes(string) help out?
