### ISSUE TITLE
git submodules -- fatal: this operation must be run in a work tree

### ISSUE THREAD

**Issue by Quacktiamauct** [IlanCosman/tide#138]
Using latest version of Fish... ✔
Using latest version of Tide... ✔

#### Describe the bug

When inside a git submodule tide seems to spew out `fatal: this operation must be run in a work tree`.

#### Steps to reproduce

1. Create a git repo
2. Add a submodule 
3. cd into submodule

#### Screenshots

![image](https://user-images.githubusercontent.com/32653278/113524713-bba70500-95b0-11eb-86a2-5ac2a60ee1dc.png)

#### Environment

- Operating system: macOS 11.2.3 (but also tested on Ubuntu in WSL)
- Terminal emulator: kitty

#### Additional context

Nope.

**Comment by IlanCosman** [comment]
Yah alright, I think I just need to add `--ignore-submodules` or something. I'll look into it.
