### ISSUE TITLE
os icon missing & alt-arrow directory switching not updating prompt

### ISSUE THREAD

**Issue by deathtrip** [IlanCosman/tide#139]
#### Describe the bug
After upgrading via fisher from 4.3.0 to 4.3.2 i noticed two issues:
1. the prompt is not redrawn after changing directory via alt+arrow
2. the os logo is missing, there's only the background segment
#### Environment

- Operating system: Arch Linux
- Terminal emulator: Kitty

**Comment by IlanCosman** [comment]
What fish version are you using? (did you run `tide bug-report`?)

**Comment by deathtrip** [comment]
fish 3.2.1

tide bug-report
Using latest version of Fish... ✔
Using latest version of Tide... ✔

**Comment by IlanCosman** [comment]
Yah sorry that was a silly question, I didn't read your question carefully enough. 

For number 2, run: `set -U _tide_os_icon (_tide_detect_os)`

I didn't even know about alt+arrow directory switching, cool! I'll look into that.
