### ISSUE TITLE
Improve detection of SSH connections for context env

### ISSUE THREAD

**Issue by alexandresoro** [IlanCosman/tide#140]
#### Is your feature request related to a problem? Please describe

I am connecting to a headless server w/ fish shell + tide via EternalTerminal (see https://github.com/MisterTea/EternalTerminal ) and the context is not detected correctly.

Eternal Terminal allows a persistent SSH connection - similar to Mosh. My technical understanding of ET is that the TTY remains on the server, and is forwarded to a client that is connected.
So it would make sense that $SSH_TTY is not set when using ET.

My understanding is that there are several ways to detect an SSH connection on top of $SSH_TTY that are $SSH_CLIENT or $SSH_CONNECTION.

A good explanation can be found here:

https://zzz.buzz/2016/02/14/detect-a-ssh-session/

#### Describe the solution you'd like

I suggest to improve the context detection of SSH by checking if either of $SSH_TTY, $SSH_CLIENT or $SSH_CONNECTION is set.
As far as I can see, I don't see any drawback to do these additional checks.

The updates would need to be done at 

https://github.com/IlanCosman/tide/blob/c7d9679b281b56a9378c19f27679e30153d1c934/functions/_tide_item_context.fish#L2

and I am willing to implement it.

**Comment by alexandresoro** [comment]
I forgot to mention that I set `tide_context_always_display` to `true` as a workaround, but in this case, it would be displayed anytime, even when connected directly, which may not suit everyone needs, hence this feature suggestion.

**Comment by IlanCosman** [comment]
Agreed 👍 My method is copied from the [default prompt](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_prompt.fish#L21), so this is something that should be improved upstream. Perhaps a function `fish_is_ssh` like the recently created `fish_is_root_user`. Could you submit an issue there?

**Comment by alexandresoro** [comment]
Before raising this to upstream, I'm going to check first if this makes sense on EternalTerminal side to not set $SSH_TTY. Otherwise, I am not sure that  I'll have enough arguments to discuss this on Fish side.

**Comment by IlanCosman** [comment]
Closing this for now until further news from ET or Fish.
