### ISSUE TITLE
Save current configuration

### ISSUE THREAD

**Issue by paupalou** [IlanCosman/tide#142]
Hello,

I would like to know if it is possible to save the current configuration in order to version it and replicate it on other machines? As far as I have seen some values are set in the `fish_variables` file but there are many lines and with an encode that I don't understand, I suppose that saving these variables and pasting them in another machine would work but is there any other "cleaner" way to do it?

Thank you

**Comment by IlanCosman** [comment]
There is no built in way of saving your Tide configuration.

Basically boils down to:
> As for Tide specifically, here's my recommendation: Base your configuration in the tide configure wizard. The wizard already lets you do a large part of the customization that most people desire, and takes perhaps 10 seconds if you know the choices you want.
Then in your install script only change the variables you actually want to change. This will save you from having to backup your whole Tide configuration, which is over 100 variables, and also has the advantage that you can receive "updates" to the parts of your configuration you didn't customize.

I recommend using an install script that just sets the few universal variables that you actually want to change.
