### ISSUE TITLE
set: Tried to change the read-only variable 'SHLVL'

### ISSUE THREAD

**Issue by monsdroid** [IlanCosman/tide#144]
#### Describe the bug

After Configuration `set: Tried to change the read-only variable 'SHLVL'`
appears in fish shell, configuration gets lost

#### Steps to reproduce

1. clean ubuntu 20.04
2. fish & omf & fisher
3. fisher install tide
4. configure tide
5. shell looks like expected
6. reload shell, looks different (right side disappeared)

#### Environment

- Operating system: Ubuntu 20.04 (WSL)
- Terminal emulator: Windows Terminal Preview (1.7)

#### Additional context

After Configuration is done i can see error messages before the screen gets cleared, but cant find the logs to append this here.
`set: Tried to change the read-only variable 'SHLVL'` is probably the last line.

googling around one user said `omf destroy` helped him get rid of this error but i need some of the plugins which omf's provide

**Comment by IlanCosman** [comment]
Tide does not work with OMF installed afaik. Almost every OMF plugin should work with Fisher though.

**Comment by monsdroid** [comment]
didnt now that. removed omf and switched everthing to fisher. still same problem. after config is finished, error message flashes by and then clears the screen.
anyway i can enable logging during tide installation & configuration?

**Comment by IlanCosman** [comment]
Can you try `tide bug-report --clean`? Do you still have issues there?

**Comment by IlanCosman** [comment]
Closing as stale. Feel free to reopen if you'd like to continue diagnosing.
