### ISSUE TITLE
toolbox support

### ISSUE THREAD

**Issue by Yajo** [IlanCosman/tide#146]
#### Describe the bug

https://github.com/containers/toolbox is a nice tool to have disposable pet containers for development, where you can behave as a privileged user in a common distro, while being still unprivileged in another (or the same) distro.

I use it often, but it seems to break with tide.

#### Steps to reproduce

1. Install tide using fisher in the host system.
2. Configure it.
3. Looks good.
4. `toolbox enter` (note: toolbox has installed the same version of fish as host system).

#### Screenshots

![screenshot-2021-04-19-16-54-49](https://user-images.githubusercontent.com/973709/115266679-50247200-a130-11eb-9c49-6918b8d197ec.png)

#### Environment

Output of `tide bug-report`: 

```
fish, version 3.2.1
tide, version 4.3.2
xterm-256color
```

(before you ask, it returns the same values inside and outside the toolbox)

#### Additional context

Host system: Fedora Silverblue 33
Toolbox system: Fedora 33

**Comment by IlanCosman** [comment]
It looks like a font problem to me where the powerline glyphs aren't being rendered. 
What does `echo ` look like for you outside and inside the toolbox?

**Comment by Yajo** [comment]
https://user-images.githubusercontent.com/973709/115513263-c503c300-a27a-11eb-9a62-4ef4f30909f0.mp4

I find it interesting that, if I configure tide inside the toolbox, then it breaks outside. 🤔

**Comment by IlanCosman** [comment]
Hmm let's try something simple. Can you try another powerline Fish theme? `fisher install oh-my-fish/theme-bobthefish`.

**Comment by Yajo** [comment]
It seems it fails similarly:
![imagen](https://user-images.githubusercontent.com/973709/116363503-1a9c1a80-a7fb-11eb-99e6-8b35b2e7b578.png)

**Comment by IlanCosman** [comment]
Ok, yeah, then this is a Toolbox/Fish problem. Open an issue in on of those projects.

**Comment by debarshiray** [comment]
> Ok, yeah, then this is a Toolbox/Fish problem. Open an issue in on of those projects.

Can you elaborate, please? I don't use Fish, and I have no idea what the prompt is supposed to look like.

**Comment by IlanCosman** [comment]
@debarshiray Turns out you fixed this bug at some point along the way 🤷‍♂️ No need to do anything 😄

That said, prompts should look the same inside and outside the toolbox. As you can see from @Yajo's comment, there were font problems inside the toolbox, but that has since been fixed somehow.

**Comment by debarshiray** [comment]
Oh, that's wonderful to hear. Thanks a lot for confirming that.
