### ISSUE TITLE
Error when updating

### ISSUE THREAD

**Issue by ironstarfish** [IlanCosman/tide#148]
Ran a fisher update command and met the error below.  Tried installing tide on my laptop and gets an error as well.  I will capture the logs for the install later, logs below for the update error.

Distributor ID:	Pop
Description:	Pop!_OS 21.04
Release:	21.04
Codename:	hirsute

fisher update version 4.2.0
Fetching https://codeload.github.com/jorgebucaran/fisher/tar.gz/HEAD
Fetching https://codeload.github.com/ilancosman/tide/tar.gz/HEAD
Installing jorgebucaran/fisher
           /home/ed/.config/fish/functions/fisher.fish
           /home/ed/.config/fish/completions/fisher.fish
Installing ilancosman/tide
           /home/ed/.config/fish/functions/_tide_decolor.fish
           /home/ed/.config/fish/functions/_tide_detect_os.fish
           /home/ed/.config/fish/functions/_tide_find_and_remove.fish
           /home/ed/.config/fish/functions/_tide_item_chruby.fish
           /home/ed/.config/fish/functions/_tide_item_cmd_duration.fish
           /home/ed/.config/fish/functions/_tide_item_context.fish
           /home/ed/.config/fish/functions/_tide_item_git.fish
           /home/ed/.config/fish/functions/_tide_item_jobs.fish
           /home/ed/.config/fish/functions/_tide_item_nvm.fish
           /home/ed/.config/fish/functions/_tide_item_os.fish
           /home/ed/.config/fish/functions/_tide_item_php.fish
           /home/ed/.config/fish/functions/_tide_item_prompt_char.fish
           /home/ed/.config/fish/functions/_tide_item_pwd.fish
           /home/ed/.config/fish/functions/_tide_item_rust.fish
           /home/ed/.config/fish/functions/_tide_item_status.fish
           /home/ed/.config/fish/functions/_tide_item_time.fish
           /home/ed/.config/fish/functions/_tide_item_vi_mode.fish
           /home/ed/.config/fish/functions/_tide_item_virtual_env.fish
           /home/ed/.config/fish/functions/_tide_left_prompt.fish
           /home/ed/.config/fish/functions/_tide_prompt.fish
           /home/ed/.config/fish/functions/_tide_remove_unusable_items.fish
           /home/ed/.config/fish/functions/_tide_right_prompt.fish
           /home/ed/.config/fish/functions/_tide_sub_bug-report.fish
           /home/ed/.config/fish/functions/_tide_sub_configure.fish
           /home/ed/.config/fish/functions/fish_mode_prompt.fish
           /home/ed/.config/fish/functions/fish_prompt.fish
           /home/ed/.config/fish/functions/fish_right_prompt.fish
           /home/ed/.config/fish/functions/tide
           /home/ed/.config/fish/functions/tide.fish
           /home/ed/.config/fish/conf.d/_tide_init.fish
           /home/ed/.config/fish/completions/tide.fish
complete: Too many arguments

~/.config/fish/completions/tide.fish (line 1):
complete tide --no-files
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 177 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'update'

(Type 'help complete' for related documentation)
complete: Too many arguments

~/.config/fish/completions/tide.fish (line 3):
complete tide -x -n __fish_use_subcommand -a --help -d "Print help message"
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 177 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'update'

(Type 'help complete' for related documentation)
complete: Too many arguments

~/.config/fish/completions/tide.fish (line 4):
complete tide -x -n __fish_use_subcommand -a --version -d "Print tide version"
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 177 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'update'

(Type 'help complete' for related documentation)
complete: Too many arguments

~/.config/fish/completions/tide.fish (line 5):
complete tide -x -n __fish_use_subcommand -a bug-report -d "Print info for use in bug reports"
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 177 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'update'

(Type 'help complete' for related documentation)
complete: Too many arguments

~/.config/fish/completions/tide.fish (line 6):
complete tide -x -n __fish_use_subcommand -a configure -d "Run the configuration wizard"
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 177 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'update'

(Type 'help complete' for related documentation)
complete: Too many arguments

~/.config/fish/completions/tide.fish (line 8):
complete tide -x -n '__fish_seen_subcommand_from bug-report' -a --clean -d "Run clean Fish instance and install Tide"
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 177 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'update'

(Type 'help complete' for related documentation)
complete: Too many arguments

~/.config/fish/completions/tide.fish (line 9):
complete tide -x -n '__fish_seen_subcommand_from bug-report' -a --verbose -d "Print full Tide configuration"
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 177 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'update'

(Type 'help complete' for related documentation)
Updated 2 plugin/s

**Comment by IlanCosman** [comment]
What's your fish version?

**Comment by ironstarfish** [comment]
Shell: fish 3.1.2

**Comment by IlanCosman** [comment]
Yah that's old. Updating to 3.2 should fix this.

**Comment by IlanCosman** [comment]
https://github.com/IlanCosman/tide/wiki/Fish-version-compatibility

**Comment by ironstarfish** [comment]
Solved. Thanks!
