### ISSUE TITLE
Spurious newlines when using tmux focus-events

### ISSUE THREAD

**Issue by JesseFarebro** [IlanCosman/tide#150]
#### Describe the bug

This is kind of unusual. I use tmux and when using tide I get these random newlines that are inserted when typing a command. If I'm using a custom prompt this isn't an issue so I'm not sure what might be going on with tide. I isolated this to the case where I have `focus-events` enabled in tmux. I'm not quite sure why this might be happening but I'd like to try and figure this out.

#### Steps to reproduce

1. Install tmux
2. Make sure you have `set -g focus-events on` in your tmux config
3. Start typing a command, e.g., `ls -l`
4. A new line is inserted while typing the command

Note: it is somewhat intermittent, if it doesn't insert a newline just clear the screen and try typing a command again. I'd say it happens 95%+ of the time for me.

#### Screenshots

I typed `l` on the first line and this creates a line break and the result as seen below:

<img width="953" alt="Screen Shot 2021-05-04 at 10 26 39 AM" src="https://user-images.githubusercontent.com/1377567/117036981-39028a00-acc3-11eb-841b-1565f24d20fd.png">

#### Environment

```
fish version: 3.2.2
tide version: 4.3.4
term: alacritty
os: macOS 11.3.1
terminal emulator: Alacritty
tmux version: 3.2
```

**Comment by IlanCosman** [comment]
I know essentially nothing about tmux, so I'm not going to be much help here, sorry 😞There's a lot of factors here, Fish, Tmux, Tide async, and Alacritty. Sorry to say this, but you're on your own. 

I wish you luck in finding the problem, and would happily accept a PR if it's fixable in Tide 😄

**Comment by JesseFarebro** [comment]
I think I'll close this, for now, I don't know where to start debugging this. I just wanted to post this incase anyone comes upon this issue and might know of a potential fix. Thanks, @IlanCosman.
