### ISSUE TITLE
Improve git status items with icons and tag name

### ISSUE THREAD

**Issue by bric3** [IlanCosman/tide#154]
#### Is your feature request related to a problem? Please describe

I am using the lean config with icon full mode, yet git item does not display any (neither git, or github icon). Also I noted that git item could be improved as well when git repo is on a tag.

powerline10k :
```
  ~/opensource/one-nio   master ❯
  ~/opensource/one-nio  #1.3.1 ❯
```

<img width="291" alt="image" src="https://user-images.githubusercontent.com/803621/117948053-10a50c00-b311-11eb-9e11-61ddddec1b39.png">
<img width="266" alt="image" src="https://user-images.githubusercontent.com/803621/117948479-75606680-b311-11eb-8f2c-6e39e2573874.png">

fish:
```
  ~/opensource/one-nio master ❯ git co 1.3.1 &> /dev/null
  ~/opensource/one-nio 0b9c0ab ❯
```

<img width="430" alt="image" src="https://user-images.githubusercontent.com/803621/117948551-84471900-b311-11eb-9c2a-2d225b0a7abf.png">

#### Describe the solution you'd like

In the images above I am showing what powerline 10k is doing, I think this should be what this status should aim for.

**Comment by IlanCosman** [comment]
There, tags will show up nicely in Tide v5, whenever that comes out. 

I don't want to add the git/github logo though, for performance reasons. `git config --get remote.origin.url` takes 8ms by itself, and we'd have to parse it to see whether it was a github url. That a steep performance penalty fora tiny improvement in functionality.

**Comment by bric3** [comment]
@IlanCosman Cool thank for the update, I get the performance reason to read the remote url, but why not a default git icon ?

Also shouldn't the async rendering somewhat moderate this performance penalty.

**Comment by IlanCosman** [comment]
Sure, I can do a default git icon.

And yes, async means that a 10ms delay in git repos isn't a big deal, especially when `git status` takes most of the time. But it's still a small cost, and a moderate cost in code complexity, that I think isn't worth it.

**Comment by bric3** [comment]
> But it's still a small cost, and a moderate cost in code complexity, that I think isn't worth it.

Fair enough

**Comment by luxalpa** [comment]
Do you think it's possible to make  the standard git icon instead of using the placeholder? It's being used in the screenshots and it was disappointing to see that it didn't show the icon when using the theme :(

**Comment by IlanCosman** [comment]
@luxalpa That gif shows Starship first, a separate popular prompt. The gif is meant to show that Starship is slower than Tide in large git repositories.

**Comment by luxalpa** [comment]
aw, still I think an icon for git would be much nicer than having just text.

**Comment by IlanCosman** [comment]
It actually is a nerd font icon: 
It does look like text though 😂
