### ISSUE TITLE
Prompt directory path does not update after cd in config.fish

### ISSUE THREAD

**Issue by smthpickboy** [IlanCosman/tide#155]
#### Describe the bug

After I add
```
cd ~/work
````
to config.fish, prompt does not update current directory.

If I delete the above line, prompt works fine.

#### Steps to reproduce

1. Modify `~/.config/fish/config.fish`, add `cd ~/work`
2. Start a new terminal session
3. cd to another directory

#### Environment

Output of `tide bug-report`: 

```
tide, version 4.3.4
fish, version 3.2.2
```

#### Additional context

`tide bug-report --clean`
also reproduce the issue.

Just add a config.fish file under the temp directory this command created, e.g., `/var/folders/zb/ntffqnsx6zz2nn06bw5wvb4h0000gn/T/tmp.7IGUOTiT/.config/fish/config.fish` and add `cd /Users/Jobs/work`.

**Comment by smthpickboy** [comment]
Apparently, env var `PWD` is not updated properly in `_tide_item_pwd`, when using `cd` in `~/.config/fish/config.fish`.

Any thoughts? @IlanCosman

**Comment by IlanCosman** [comment]
Yeah sure, I don't consider this a bug though 😄 Tide creates a fish background process each time you press enter. That fish background process loads the `config.fish` like normal. So if you change the environment there, Tide can't get the correct information. 

You should enclose anything you want to run only interactively like so:

```fish
if status is-interactive
    do-interactive-stuff
    cd ~/work
end
```

A structure like this will be [recommended by default](https://github.com/fish-shell/fish-shell/pull/7796/files#diff-0d2c4442bc9780ab3f6d9e4b371b7cd7c89c18aca56bb25204e94d244a8d683bR275-R277) in Fish 3.3.0.

**Comment by smthpickboy** [comment]
Thank you! It fixes the issue. Good to know the mechanic under the hood.
