### ISSUE TITLE
Add a `SHLVL` module

### ISSUE THREAD

**Issue by kidonng** [IlanCosman/tide#156]
#### Is your feature request related to a problem? Please describe

I would like to propose a `SHLVL` module to display current `$SHLVL` if it exceeds a configurable threshold.

This is really handy if one frequently works with nested shells (or people loving to tinker around like me 😀).

#### Describe the solution you'd like

Something like:

```fish
function _tide_shlvl
  if test $SHLVL -gt $tide_shlvl_threshold
    echo ↕️ $SHLVL
  end
end
```

#### Additional context

Powerlevel10k doesn't have this (AKAIK) but [Starship does](https://starship.rs/config/#shlvl).

**Comment by IlanCosman** [comment]
I don't really get why this is useful. I read the original issue on Starship, but it doesn't really explain why either. Could you try to explain this? I'm not opposed to adding it, but I'd like to first understand why it's useful.

**Comment by kidonng** [comment]
Nested shell is fairly common. Depending on the terminal/desktop environment/program we use, it can go deep quickly.
For example, shell launched in terminal may or may not have a deeper level of SHLVL, depends on settings/the way it is opened/whatever.
Some applications can be open via both GUI and terminal, and the latter, of course, has a deeper level of SHLVL.
Some programs are designed to work with these nested shells, like tmux, screen.
Sometimes you may want to open a new shell, either to isolate the environment or do some temporary tasks.
SHLVL is a important piece info of how deep have we go, it can tell us whether the current shell environment is suitable for you tasks, while also great for troubleshooting.

I admit this _is_ a niche feature and normally we don't care about it, but just like why I opened #157, it's a nice addition to tide and _has_ its own value. 

I hope I've convinced you 😊

**Comment by IlanCosman** [comment]
Alright, sure, I can add a SHLVL item. It will be disabled by default though because I don't think this is useful to most people 😄

**Comment by kidonng** [comment]
Thank you! ✨

**Comment by kidonng** [comment]
Is this something I can work on? I'd like to contribute, but don't know how to pick a color 👀

**Comment by IlanCosman** [comment]
Yeah, sure 😄 You can make a PR against the `v5` branch. A bunch of stuff has changed, but it shouldn't be too hard to figure out the new system. As for colors, Maybe just yellow or something, with this:  as the icon (up-down arrow nerd font).

**Comment by IlanCosman** [comment]
Closed by #165

**Comment by kidonng** [comment]
Just to extend the usage I described a little bit:

- Fish's private mode also creates a deeper level of shell. Well I have a separate mode proposal for that but it's still two different things.
- I've been using [Nix](https://nixos.org/) recently and now I _frequently_ goes in and out of nested shells. Having a `SHLVL` module really makes things clearear.

**Comment by kidonng** [comment]
We may need to keep an eye on Fish 3.3.0 because of this change: fish-shell/fish-shell#7864
