### ISSUE TITLE
Add private mode indicator module

### ISSUE THREAD

**Issue by kidonng** [IlanCosman/tide#157]
#### Is your feature request related to a problem? Please describe

[Fish's private mode](https://fishshell.com/docs/current/interactive.html#private-mode) is very useful, but you may forget that you have entered it when you switching between sessions.

I propose to add a private mode indicator module to easily show if the current shell is under private mode or not.

#### Describe the solution you'd like

Something like:

```fish
function _tide_private_mode
  if test -n "$fish_private_mode"
    echo 👓 # like Chrome's incognito mode
  end
end
```

**Comment by IlanCosman** [comment]
Sure 👍

**Comment by kidonng** [comment]
This may be a little more difficult to add because `$fish_private_mode` is a global **unexported** variable.

**Comment by kidonng** [comment]
An idea:

```fish
# In conf.d/_tide_init.fish
# Don't further export $fish_parent_private_mode
set -q fish_parent_private_mode && set -u fish_parent_private_mode $fish_parent_private_mode
# Export $fish_private_mode to subshells via $fish_parent_private_mode, and reference the latter in the module
set -q fish_private_mode && set -x fish_parent_private_mode $fish_private_mode
```

This has been working well:

```
~
❯ fish -P
fish is running in private mode, history will not be persisted.

~                                                      2
❯ fish

~                                                       3
❯ 
```

**Comment by IlanCosman** [comment]
More simply, add it to the list of variables in `fish_prompt.fish`:

```fish
fish --command "_tide_jobs_status=$status _tide_private_mode=$fish_private_mode \
            CMD_DURATION=$CMD_DURATION COLUMNS=$COLUMNS fish_bind_mode=$fish_bind_mode \
            set -U $_tide_prompt_var (_tide_prompt)" &
```

**Comment by kidonng** [comment]
It would certainly be simpler to implement this in tide itself. My solution doesn't need to hack tide.

**Comment by IlanCosman** [comment]
Oh, I thought you were suggesting a way of adding this to Tide 😄
