### ISSUE TITLE
No git status shown

### ISSUE THREAD

**Issue by hybridvision** [IlanCosman/tide#159]
Hello!

Thank you for this beautiful, polished prompt!

It works very nicely except for one thing: the git status is missing and I can't figure out what is wrong. I have the latest versions of everything and previously git status worked fine. I tested with another theme (bobthefish) and the git status is working there. I even tried installing on a different profile + a different machine but I get the same result.

I checked that `$tide_left_prompt_items` contains `pwd git`.

I'm at a loss for what else to try... Any suggestions appreciated!

#### Steps to reproduce

1. Install tide 
2. Run configuration
3. Change directory to a git repository: **no git status is shown** (nor any errors).

#### Screenshots
Inside a git repository: ![image](https://user-images.githubusercontent.com/11492432/119678014-8051e580-be3f-11eb-8005-6a292738c822.png)

Same repository, using bobthefish theme: ![image](https://user-images.githubusercontent.com/11492432/119678522-e0e12280-be3f-11eb-93a9-12a5b2441859.png)

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.2.2
tide version: 4.3.4
term: xterm-256color
os: Mac OS 10.14.6
terminal emulator: iTerm2
```

#### Additional context

git version: `2.20.1 (Apple Git-117)`

**Comment by IlanCosman** [comment]
Thanks for the bug report 😄

Thanks a ton for adding the additional context btw, it would have taken me a bit to figure this out otherwise.

Your git version is too old; it doesn't have `git branch --show-current`. Git 2.22 (which introduced `git branch --show-current`) came out almost 2 years ago.

**Comment by hybridvision** [comment]
Aha! 💡  Thanks for the rapid reply @IlanCosman!

I had wondered if Git might be to blame but I didn't get around to upgrading it yet. I'll do that now 😃

**Comment by hybridvision** [comment]
By the way: it might be useful to list the minimum Git version in the requirements in case anyone else is running an older version like me.
