### ISSUE TITLE
single line default config doesn't show the right prompt on a brand new fish install

### ISSUE THREAD

**Issue by pierreN** [IlanCosman/tide#16]
**Bug description**
When installing tide on a brand new fish install, configuring it with `tide configure`, selecting the single line configuration, the right prompt doesn't appear.

Note that I have a large screen (430 cols)

**To Reproduce**

Cleaning my dotfiles and decided to switch from zsh to fish.

Ran into this nice project which looked fine for what I'm used too, so installed it on a brand new (arch linux)/fish install.
After `tide configure`, selecting the single line configuration, the right prompt doesn't appear

**Expected behavior**
A right prompt as shown in `tide configure` should actually appear

**Environment:**

- OS: Up-to-date arch linux
- Fish Version: fish, version 3.1.2-1199-gd8eb7fc46
- Tide Version: removed now, but just ran `curl -sL git.io/tide | source && tide_install` a few hours before opening this issue

**Comment by IlanCosman** [comment]
Thanks for submitting an issue @pierreN 😄

From what I can tell, your experience was simply a series of misunderstandings

![Capture](https://user-images.githubusercontent.com/6318351/89806922-9bd84380-daec-11ea-83e6-28e54a845694.PNG)

I presume you selected the `No` option at this point. The golden sections with the `5s` is the `cmd_duration` item, which only displays if you the last command exceeded `cmd_duration_threshold`. `tide configure` displays that item only to give you an idea of what the right prompt will look like when it displays. There are a number of other items in the right prompt, but none that display by default. Thus your right prompt displayed nothing after exiting `tide configure`.

Similarly the `context` item which you struggled with does not display by default, only when in SSH or while the user is root. After the latest commit you can set `context_always_display` to always display the context item. 

Would you be willing to reinstall Tide briefly to verify my thoughts? You can uninstall it right after 😂, I'd simply like to make sure there aren't actually any bugs.

If you do so, try running `sleep 5` and seeing the `cmd_duration` item display. Or `set tide_context_always_display true` to activate the context item.
