### ISSUE TITLE
virtual environment indicator removed if only python3 installed

### ISSUE THREAD

**Issue by GregDMeyer** [IlanCosman/tide#162]
#### Describe the bug

If there is no command `python` present on the system, but Python 3 is installed (e.g. by default on recent Ubuntu distros), the virtual environment item is removed from the prompt.

#### Steps to reproduce

1. Run a machine that has only `python3` but not `python` available
2. Generate a virtual environment with `python3 -m venv test_env`
3. Run `source test_env/bin/activate.fish`
4. Virtual environment indicator is not present on the right hand side of prompt

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.2.2
tide version: 4.3.4
term: xterm-256color
os: Pop OS 20.10
terminal emulator: Gnome terminal
```

#### Additional context

I did a tiny bit of digging and it looks like the function `_tide_remove_unusable_items` removes the `virtual_env` item if the command `python` is not present (it does not check if `python3` etc. may be available instead).

**Comment by IlanCosman** [comment]
Nice catch!
