### ISSUE TITLE
fish_title is invoked 3 times

### ISSUE THREAD

**Issue by karmicdude** [IlanCosman/tide#164]
#### Describe the bug

I wanted to add a condition to the `fish_title` function, that shows the name of the git directory if I am in it. 

A very simplified version of my `fish_title` function (it has a lot more conditions, but it doesn't matter for this problem):

```fish
function fish_title
    if set -l git_dir (git rev-parse --show-toplevel 2> /dev/null)
        echo " "(basename $git_dir)
    else
        echo fish
    end
end
```
On a new fish initialization, `fish_title` is called 3 times. After the second call, there is a wait for some action that redraws the prompt, for example enter or clearing term.

At first I was blaming different plugins or my settings. In the end I did a pure fish installation without any customization, then I installed tide. Then I created the `fish_title` function which outputs the message to stderr and found that the `fish_title` function is called 3 times for some reason when `tide` is plugged.

```fish
function fish_title
   echo fish >&2
   git rev-parse --show-toplevel 2> /dev/null
end
```

Without using `tide`, the prompt is drawn once and everything works as it should.

To demonstrate this more clearly, I recorded a gif animation.

![fish_title.gif](https://i.imgur.com/sGOH52r.gif)

#### Environment

```
fish version: 3.2.2
tide version: 4.3.4
term: xterm-kitty
os: Arch Linux 5.12.10-arch1-1
terminal emulator: fish
```

**Comment by kidonng** [comment]
`fish_title` runs after` `fish_prompt`, which we use to check if the prompt is loading:

![image](https://user-images.githubusercontent.com/44045911/122640555-c5adbe00-d132-11eb-8844-5437dbf294d5.png)

So to prevent unnecessary `fish_title` calls, guard it with the following code:

```fish
function fish_title
    set -q $_tide_left_prompt_display_var || return
    # rest of the function
end
```

Result:

![image](https://user-images.githubusercontent.com/44045911/122640613-1f15ed00-d133-11eb-8543-d9cd1f842b17.png)

**Comment by IlanCosman** [comment]
I don't really see any bugs here. `fish_title` is supposed to run after every `fish_prompt`. This includes when the prompt is re-run through `commandline -f repaint`, which is what's happening here.

This behavior might be annoying if you have a `fish_title` that takes a while to run 🤷‍♂️
