### ISSUE TITLE
see unexpected symbol under any git dict

### ISSUE THREAD

**Issue by WangHuancheng** [IlanCosman/tide#166]
#### Describe the bug

i see unexpected symbol under any git dict, do using mesol font

#### Steps to reproduce

1. Set to any git dict
2. see the bug

#### Screenshots

![2021-06-24 19-48-31 的屏幕截图](https://user-images.githubusercontent.com/9625870/123259315-ead17080-d526-11eb-9128-e1a1683a0406.png)

#### Environment

Output of `tide bug-report`: 

```
Your Fish version is out of date.
The latest is 3.2.2. You have 3.2.1.
Please update before submitting a bug report.
```
note 3.2.1 is the lastest version for my package source, Ubuntu 20.04 focal

**Comment by IlanCosman** [comment]
I don't see any bugs here. It looks just fine to me. Could you point it out more specifically?

**Comment by WangHuancheng** [comment]
i mean the '?9' part, actually i notice that there are some ? and ! in different git dict, so maybe its a feature ?

**Comment by IlanCosman** [comment]
Ah, yah that should probably be more clearly documented 😄 That's the number of untracked files in the repo.

**Comment by WangHuancheng** [comment]
oh i see, i should know that earlier, anyway thanks for answering the stupide question and developing this great prompt.
