### ISSUE TITLE
doesn't load / update right away on fish 3.3.0

### ISSUE THREAD

**Issue by cap10morgan** [IlanCosman/tide#168]
#### Describe the bug

On fish 3.3.0 tide requires an additional enter key press to show up initially in a new shell and any new information like current directory after running `cd`, etc.

#### Steps to reproduce

1. Install fish 3.3.0
2. Install tide (via fisher 4.3.0)
3. Launch a new shell
4. Change to a new directory

After #3 you'll notice the prompt doesn't appear until you hit enter.

After #4 you'll notice the current directory in the prompt doesn't update until you hit enter again.

See attached screen recording. The initial prompt load happens when I hit enter (it's not obvious from the recording).

#### Screenshots

https://user-images.githubusercontent.com/59748/123706532-9e877880-d825-11eb-9f74-2674ba433e3c.mov

#### Environment

Output of `tide bug-report`:

```
fish version: 3.3.0
tide version: 4.3.4
term: xterm-256color
os: macOS 11.4
terminal emulator: iTerm 3.4.8
```

**Comment by IlanCosman** [comment]
Yah. https://github.com/fish-shell/fish-shell/issues/8088

**Comment by nicoelayda** [comment]
For anyone else on macOS with this issue and needs to temporarily downgrade back to fish 3.2.2:

```sh
exec zsh
cd $(brew --repository homebrew/core)
git checkout e34eefd -- Formula/fish.rb
brew reinstall fish && brew pin fish
git checkout master -- Formula/fish.rb
```

Restart your terminal afterwards.

Don't forget to `brew unpin fish` once this issue is resolved.

**Comment by IlanCosman** [comment]
Thanks @nicoelayda. I apologize for creating this mess, I should have checked that Tide was working before the release. I don't know what I was thinking 😅 Hopefully this will resolve itself for 3.3.1.

**Comment by philipbjorge** [comment]
For anyone on Ubuntu:
I believe you will have to compile from source as none of the 3.2 line of releases ended up in[ launchpad](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3).

**Comment by IlanCosman** [comment]
Another short term solution is to install Tide from the experimental `remove-async` branch, which as the name suggests removes the async functionality. That should work with Fish 3.3.0.

**Comment by PatrickF1** [comment]
Fish 3.3.1 has dropped! Can confirm it works. Ilan, I think you should update https://github.com/IlanCosman/tide#system-requirements

**Comment by cap10morgan** [comment]
Yep, fish 3.3.1 fixes it for me too! 🔧
