### ISSUE TITLE
`tide configure` menu doesn't appear

### ISSUE THREAD

**Issue by GrafKiedyUHC** [IlanCosman/tide#172]
#### Describe the bug

`tide configure` does nothing, just goes to the next line instead of opening the config menu.
I updated fish to the newest version (tried to `fish bug-report` and it said I was on and old version, updated.
Still the same result.

#### Steps to reproduce

1. `tide configure`

#### Screenshots

![Screenshot from 2021-07-11 21-06-12](https://user-images.githubusercontent.com/61237859/125207381-525c1f80-e28c-11eb-86fb-6c0ed8768b08.png)

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 4.3.4
term: xterm-256color
os: Ubuntu 20.04
terminal emulator: default (?)
```

#### Additional context

New to Linux, forgive me.

**Comment by IlanCosman** [comment]
Thanks for opening an issue 😄 I can't reproduce though on Arch or macOS, I suppose I should try Ubuntu 20.04 though.

P.S: You should probably use the [recommended font](https://github.com/IlanCosman/tide#meslo-nerd-font), your current font has the characters weirdly sized.

**Comment by GrafKiedyUHC** [comment]
Changed the font, tried it again just out of curiosity but it's definitely not a font issue, still no go.
I'm also using the Starship Shell Prompt, not sure if that changes anything.

**Comment by IlanCosman** [comment]
Can you try running `tide bug-report --clean` and reproducing the bug there?

**Comment by GrafKiedyUHC** [comment]
Worked fine after running that command, configuration went through as expected.

**Comment by IlanCosman** [comment]
`tide bug-report --clean` runs a new shell with none of your configuration. If that worked, then it's something about your configuration that's the problem.

As for `exit`. The first `exit` closed the inner shell, and then the second `exit` closed the outer one, which tells the terminal to close.

Tide and Starship both fulfill the same function (at least for Fish): being your prompt. There's no way to use both at the same time.

Idk what's wrong with your configuration. Perhaps a `fisher update` might help.

**Comment by GrafKiedyUHC** [comment]
That makes sense, everything works fine inside the inner shell but outside of it it's a no-go.
I disabled Starship in my fish config files but still no luck.

**Comment by IlanCosman** [comment]
Tha's unfortunate. Well feel free to poke around and try to find whatever the problem is in your config. Or don't, and use Starship 🤷‍♂️

Thanks for reporting 😄
