### ISSUE TITLE
My color settings are ignored with tide

### ISSUE THREAD

**Issue by raven2cz** [IlanCosman/tide#173]
I have question to tide. I switch to tide, but my color settings from config.fish are ignored.
What has to be set to activate my fish color variables?

```
### AUTOCOMPLETE AND HIGHLIGHT COLORS ###
set fish_color_normal brcyan
set fish_color_autosuggestion '#7d7d7d'
set fish_color_command brcyan
set fish_color_error '#ff6c6b'
set fish_color_param brcyan
```

**Comment by IlanCosman** [comment]
I don't understand the question. Those color variables apply to the commandline, not the prompt. That's true even without Tide.

**Comment by raven2cz** [comment]
Yes, but it is true. It lost colors.

Try test case:

tide configure, select:

Lean -> True color -> 24h format -> **One line** -> Compact -> few icons.

After this settings, the colors are lost, and default white color is taken only.

**Comment by IlanCosman** [comment]
Great, I can reproduce, thank you. I'll look into it.

**Comment by IlanCosman** [comment]
Alright, found the problem. Seems like a fish bug to me. Some bug with the right prompt.

```fish
function fish_right_prompt
    set_color yellow
    date
end
```

```fish
~> set fish_color_command brcyan # This works, commands are now cyan
~> set fish_color_normal brcyan # This breaks things, commands are now yellow
```

**Comment by IlanCosman** [comment]
Ok, found the old Fish report: https://github.com/fish-shell/fish-shell/issues/6563
