### ISSUE TITLE
Performance questions

### ISSUE THREAD

**Issue by IlanCosman** [IlanCosman/tide#175]
@nemonik Let's continue conversing here, I'd like to get to the bottom of this. 

> Sorry to waste your time

No problem 😄

> No, actually 8, 9, or sometimes 15 seconds worse case...

Those are still abnormally high values. It really shouldn't take more than a second or two I think, under absolute worst case scenarios (and usually much, much faster than that).

A few questions:

What's your `time fish -ic exit`?
Are you using a hard drive or SSD?
Is your computer fast?

**Comment by nemonik** [comment]
```
Executed in    8.52 secs    fish           external
   usr time    6.31 secs  241.00 micros    6.31 secs
   sys time    2.97 secs  643.00 micros    2.97 secs
 ```

**Comment by nemonik** [comment]
```
  Model Name:	MacBook Pro
  Model Identifier:	MacBookPro15,1
  Processor Name:	6-Core Intel Core i7
  Processor Speed:	2.6 GHz
  Number of Processors:	1
  Total Number of Cores:	6
  L2 Cache (per Core):	256 KB
  L3 Cache:	12 MB
  Hyper-Threading Technology:	Enabled
  Memory:	16 GB
  ```

**Comment by IlanCosman** [comment]
Ok, yah, Fish should _**Not**_ be taking that long to start up. For context my M1 Macbook Air runs that command in ~16ms. That's why Tide is taking so long, because it uses a background Fish process to do all the computation.

My guess is you might be appending to PATH on fish startup, making it grow larger over time. 
Can you do `echo PATH: $PATH fish_user_paths: $fish_user_paths`?

**Comment by nemonik** [comment]
Yes, that does an obsessively huge return... 

I need to move updating the my path of out ~/.config/fish/config.fish

Cuz with each shell start up it is getting longer and longer.  My bad.  Thank you!

**Comment by IlanCosman** [comment]
Yah, you should try to understand universal variables 😄 For your convenience, you can use `fish_add_path`.

**Comment by nemonik** [comment]
Yep, I see.  https://fishshell.com/docs/current/tutorial.html#path

Thank you.

**Comment by IlanCosman** [comment]
Alright hopefully that solved the problem, and you'll have a nice and snappy prompt now 😄 If not, feel free to reopen this issue.
