### ISSUE TITLE
I'm using tide v5 but it doesn't show the git status

### ISSUE THREAD

**Issue by nuo-promise** [IlanCosman/tide#188]
Do you need to set it up somewhere, please tell me？

<img width="782" alt="iShot2021-08-23 16 30 10" src="https://user-images.githubusercontent.com/46160170/130415963-5678fd49-897f-4b14-aa15-a92978f77109.png">

#### Environment

Output of `tide bug-report`: 

```

```

**Comment by IlanCosman** [comment]
Please put the output of `tide bug-report` inside the code block I added to your post.

**Comment by nuo-promise** [comment]
resolved, because my git version is too low. I update git then can display.
