### ISSUE TITLE
Some symbols not showing even with Nerd Font installed

### ISSUE THREAD

**Issue by shankargopal** [IlanCosman/tide#195]
#### Describe the bug

Comparing the appearance of the prompt to the images on Github, some symbols appear to be missing:

![image](https://user-images.githubusercontent.com/1425785/131991066-d526c43d-4c90-48e0-a975-faeb521e4003.png)

I don't quite know how to describe them, but the gaps are visible

#### Steps to reproduce

1. Install tide using `fisher` on a Debian system
2. Download fonts listed on Github page (the Nerd Fonts)
3. Copy fonts to `/usr/local/share/fonts`
4. Run `tide configure`

#### Screenshots

As shown above:
![image](https://user-images.githubusercontent.com/1425785/131991165-1b4f329e-dd7d-41f1-a42c-0f045cee02c6.png)

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: Debian 11
terminal emulator: Yakuake
```

**Comment by IlanCosman** [comment]
Did you enable the font in you terminal?

**Comment by shankargopal** [comment]
I had enabled it, but it still didn't work even after I restarted the terminal and ran `fc-cache -fv`.  But the problem magically resolved itself when I restarted the computer later.

Thank you for all the hard work you do, and for this absolutely wonderful prompt! :smile: :+1:

**Comment by IlanCosman** [comment]
> But the problem magically resolved itself when I restarted the computer later.

Haha, classic 😄 Glad to hear to problem is fixed.

> Thank you for all the hard work you do, and for this absolutely wonderful prompt!

😊
