### ISSUE TITLE
Error when pasting, running `tide configure` or running `tide bug-report`

### ISSUE THREAD

**Issue by KnifeFed** [IlanCosman/tide#196]
#### Describe the bug

When pasting something in the terminal I get the following error:

```
test: Missing argument at index 3
= 0
    ^
~/.config/fish/functions/_tide_item_jobs.fish (line 2):
    test $_tide_jobs_status = 0 && _tide_print_item jobs $tide_jobs_icon
    ^
in function '_tide_item_jobs'
	called on line 49 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_right_prompt'
	called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
	called on line 2 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution
```

I get the same error when running `tide configure`, for every prompt. My choices are `3 1 2 4 4 1 2 3 2 4 2 2`.

Now that I ran `tide bug-report` I got the same error for every prompt.

I'm pretty sure this issue started after updating to version 5.0. I have another machine running version 4.1.1 and don't experience the problem there.

#### Steps to reproduce

1. Paste from clipboard _or_ run `tide configure` _or_ run `tide bug-report`.
2. See error

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: macOS Big Sur 11.5.2
terminal emulator: iTerm2
```

#### Additional context

```shell
$ fisher list

jorgebucaran/fisher
franciscolourenco/done
PatrickF1/fzf.fish
jethrokuan/z
decors/fish-colored-man
jorgebucaran/autopair.fish
gazorby/fish-abbreviation-tips
jorgebucaran/nvm.fish
ilancosman/tide@v5
```

**Comment by IlanCosman** [comment]
My guess is it's just some upgrade bug. Try uninstalling Tide and reinstalling?

**Comment by KnifeFed** [comment]
Hiya. I have reinstalled and the issue persists.

**Comment by IlanCosman** [comment]
Is it still there when you run `tide bug-report --clean` (which creates a new, perfectly clean fish instance)?

**Comment by KnifeFed** [comment]
The error has yet to present itself in a clean fish instance.

**Comment by KnifeFed** [comment]
I added `set -l fish_trace on` in `_tide_item_jobs.fish` and when the error occurs it shows `-----------> test = 0` and then I noticed that the `_tide_jobs_status` variable doesn't exist, so `test` is not receiving a left operand.

**Comment by KnifeFed** [comment]
The error has yet to present itself in a clean fish instance.

I added `set -l fish_trace on` in `_tide_item_jobs.fish` and when the error occurs it shows `-----------> test = 0` and then I noticed that the `_tide_jobs_status` variable doesn't exist, so `test` is not receiving a left operand. 

In a clean instance, the `_tide_item_jobs` function hasn't been called so far.

**Comment by IlanCosman** [comment]
That is the problem, yes. But that really shouldn't be possible: https://github.com/IlanCosman/tide/blob/d64e9c37397e2894f70247a902ce862842d28085/functions/fish_prompt.fish#L20-L21

The `$status` variable always exists, so `_tide_jobs_status` should always exist.

**Comment by KnifeFed** [comment]
How does `fish --command "_tide_jobs_status=$status"` work? I haven't seen assignment with `=` in Fish before. `_tide_jobs_status` is not set in a clean instance either.

**Comment by IlanCosman** [comment]
That's the syntax for setting a variable for just one command. http://fishshell.com/docs/current/cmds/set.html#notes

`foo=bar echo $foo` is the same thing as `begin; set --local --export foo bar; echo $foo; end`

> _tide_jobs_status is not set in a clean instance either.

Correct. `_tide_jobs_status` only exists in the background Fish that Tide creates.

**Comment by KnifeFed** [comment]
I now:

1. Uninstalled tide
2. Deleted `_tide_interactive_init.fish` which was left over
3. Removed all the left-over tide-related variables in `fish_variables`
4. Reinstalled 

...and so far so good 🤞

**Comment by IlanCosman** [comment]
> Deleted _tide_interactive_init.fish which was left over

That's really interesting. Fisher should have removed that automatically when you upgrade to 5.0. Weird.

Great that you solved the problem 😄
