### ISSUE TITLE
Prompt shows '?' for icons

### ISSUE THREAD

**Issue by moali87** [IlanCosman/tide#197]
#### Describe the bug

By default prompt icons are '?'
<img width="263" alt="Screen Shot 2021-09-09 at 10 01 39 AM" src="https://user-images.githubusercontent.com/7011993/132700366-3d1b01fe-e1a1-4c94-aa2a-eeb1793070eb.png">

#### Steps to reproduce

Install tide configure
run tide configure with any settings except minimal

#### Screenshots
<img width="263" alt="Screen Shot 2021-09-09 at 10 01 39 AM" src="https://user-images.githubusercontent.com/7011993/132700366-3d1b01fe-e1a1-4c94-aa2a-eeb1793070eb.png">

#### Environment

mac big'sur

Output of `tide bug-report`: 

```

Please copy the following information into the issue:

fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: mac big'sur
terminal emulator: iterm2
```

**Comment by moali87** [comment]
And I do have powerline fonts installed and set on my iterm2.

**Comment by IlanCosman** [comment]
> I do have powerline fonts installed and set on my iterm2.

Tide requires a Nerd font, not just powerline.

**Comment by moali87** [comment]
> > I do have powerline fonts installed and set on my iterm2.
> 
> Tide requires a Nerd font, not just powerline.

That did solve it for many of my use cases.  However, when selecting many icons I only get '?' still.

<img width="530" alt="Screen Shot 2021-09-09 at 10 57 48 AM" src="https://user-images.githubusercontent.com/7011993/132710474-2cda2aee-8aa4-46a3-8e15-36606c9d7c0f.png">

Thank you for the quick response.

**Comment by moali87** [comment]
> Are you using the recommended font? If not, please do, at least for debugging purposes.

I feel like a complete moron.  I had the wrong Meslo font set.  Thank you so much.

**Comment by IlanCosman** [comment]
Haha, no worries. Happens to the best of us 😄
