### ISSUE TITLE
`pwd` item does not work correctly on second line

### ISSUE THREAD

**Issue by Lasoloz** [IlanCosman/tide#199]
#### Describe the bug

Not sure if this is something feasible, but I would like to have the current path on the second line (and then develop a custom prompt structure suited for me). Unfortunately whenever I put the `pwd` item on the second line, it just stops being correctly interpolated (I guess? I didn't dive deeply in the source), and `@PWD@` is shown.

#### Steps to reproduce

1. Use `set --global tide_left_prompt_items os git pwd newline character`
2. Path is shown correctly on first line, prompt looks correct
3. Use `set --global tide_left_prompt_items os git newline pwd character`
4. Path is not shown, instead `@PWD@` is visible

#### Screenshots

Correct behaviour on first line:
![tide_correctly](https://user-images.githubusercontent.com/17884077/133330310-b3be5fac-4594-4b1e-8155-683296c4452c.png)

Incorrect behaviour, when working directory is on second line
![tide_incorrectly](https://user-images.githubusercontent.com/17884077/133330349-18213231-b43b-46b8-b8a6-2482ae363e80.png)

#### Environment

Output of `tide bug-report`:

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: Manjaro
terminal emulator: gnome-terminal
```

#### Additional context

Nothing to mention

**Comment by IlanCosman** [comment]
Yes, currently Tide is only set up to work with a PWD in the first line.

One of the major reasons that a two-line prompt is nice, is that every command starts in the same spot. With a one-line prompt, you get a "bumpy" scrollback history.

So I don't really understand why you'd want PWD in the second line. What would go in the first? If you are recreating another prompt, could you provide images of it?

**Comment by Lasoloz** [comment]
Yes, you are right, I didn't think about the prompt being bumpy when scrolling.

There is no prompt being recreated, I'm just experimenting with different prompt structures. One thing I wanted to try out is a prompt which has two lines when the user is in a git repository and one line otherwise.

```
<git info><maybe other info, like node, rust, etc.><optional new line, if this line was filled>
/my/path >
```

Now, thinking about it, maybe I will implement a custom pwd item, which only shows the last directory if on the second line, and shows the old pwd item, if it's on the first line.

Thanks for the insight.

**Comment by IlanCosman** [comment]
Closing this for now, as there isn't significant justification for changing the current behavior. I'm happy to reconsider if new reasons/examples of good prompts are presented 👍
