### ISSUE TITLE
Icon support

### ISSUE THREAD

**Issue by AtifChy** [IlanCosman/tide#20]
![Screenshot_20200829_123927](https://user-images.githubusercontent.com/42291930/91630634-b408f780-e9f4-11ea-809b-4ad1ed16220f.png)
I like tide. I want to switch to fish completely but I need those icons from powerlevel10k. Please add them.

**Comment by IlanCosman** [comment]
Hi @AtifChy, thanks for submitting this feature request. I've known I needed to add icons for a while, but it wasn't a pressing issue since I've never wanted to use them. I'll add an `icons` menus to the configuration wizard. For now though you _can_ add the `os` item.

**Comment by AtifChy** [comment]
how's you progress on this?

**Comment by IlanCosman** [comment]
This issue has been put on hold for a bit. Icons don't actually give you any new information, so this feature is merely cosmetic. Bugs and features that have a larger effect on the user experience are given higher priority, but I will return to this when I can.

**Comment by IlanCosman** [comment]
Hi @AtifChy, sorry this took so long, but I've added an icons menu to the configuration wizard! There are probably missing icons that you'd like to have, so please open a new issue if you find any! Thanks for your patience.
