### ISSUE TITLE
Unable to install in WSL Ubuntu-20.04

### ISSUE THREAD

**Issue by ryanbbrownavanade** [IlanCosman/tide#201]
#### Describe the bug

The installation of tide errors out with process exit code 15 and locks up my terminal when attempting to install tide. 

#### Steps to reproduce

1. Set tide as your default shell in Ubuntu-20.04 WSL
2. Run either fisher installer or manual script installer
3. See clammed up and unresponsive terminal with several substitution and other errors. 

#### Screenshots

nction 'type' with arguments '--query chruby'
        called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function '_tide_remove_unusable_items'
        called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
in command substitution
type: Unknown option '--query'
/usr/share/fish/functions/type.fish (line 7):
    argparse -n type -x t,p,P $options -- $argv
    ^
in function 'type' with arguments '--query git'
        called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function '_tide_remove_unusable_items'
        called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
in command substitution
type: Unknown option '--query'
/usr/share/fish/functions/type.fish (line 7):
    argparse -n type -x t,p,P $options -- $argv
    ^
in function 'type' with arguments '--query go'
        called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function '_tide_remove_unusable_items'
        called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
in command substitution
type: Unknown option '--query'
/usr/share/fish/functions/type.fish (line 7):
    argparse -n type -x t,p,P $options -- $argv
    ^
in function 'type' with arguments '--query kubectl'
        called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function '_tide_remove_unusable_items'
        called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
in command substitution
type: Unknown option '--query'
/usr/share/fish/functions/type.fish (line 7):
    argparse -n type -x t,p,P $options -- $argv
    ^
in function 'type' with arguments '--query node'
        called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function '_tide_remove_unusable_items'
        called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
in command substitution
type: Unknown option '--query'
/usr/share/fish/functions/type.fish (line 7):
    argparse -n type -x t,p,P $options -- $argv
    ^
in function 'type' with arguments '--query php'
        called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function '_tide_remove_unusable_items'
        called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
in command substitution
type: Unknown option '--query'
/usr/share/fish/functions/type.fish (line 7):
    argparse -n type -x t,p,P $options -- $argv
    ^
in function 'type' with arguments '--query rustc'
        called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function '_tide_remove_unusable_items'
        called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
in command substitution
type: Unknown option '--query'
/usr/share/fish/functions/type.fish (line 7):
    argparse -n type -x t,p,P $options -- $argv
    ^
in function 'type' with arguments '--query python python3'
        called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function '_tide_remove_unusable_items'
        called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
in command substitution
set_color: Expected argument for option b

~/.config/fish/functions/_tide_cache_variables.fish (line 1):
set_color normal -b $tide_pwd_bg_color; set_color $tide_pwd_color_dirs
^
in command substitution
        called on line 5 of file ~/.config/fish/functions/_tide_cache_variables.fish
in function '_tide_cache_variables'
        called on line 7 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
in command substitution

(Type 'help set_color' for related documentation)
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish
jobs: Unknown option '--query'

~/.config/fish/functions/fish_prompt.fish (line 20):
        jobs --query
        ^
in function 'fish_prompt'
in command substitution

(Type 'help jobs' for related documentation)
~/.config/fish/functions/_tide_pwd.fish (line 9): Invalid index value
        set split_pwd_for_output '' $_tide_color_anchors$split_pwd[2]$_tide_reset_to_color_dirs $split_pwd[3..]
                                                                                                              ^
in function '_tide_pwd'
        called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
        called on line 25 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution
set: Array index out of bounds
~/.config/fish/functions/_tide_pwd.fish (line 1): Invalid index value
string join -- / $split_pwd[..$i] | string replace '~' $HOME
                            ^
in command substitution
        called on line 24 of file ~/.config/fish/functions/_tide_pwd.fish
in function '_tide_pwd'
        called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
        called on line 25 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution
~/.config/fish/functions/_tide_pwd.fish: Unknown error while evaluating command substitution
in function '_tide_pwd'
        called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
        called on line 25 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution
~/.config/fish/functions/_tide_pwd.fish (line 1): Invalid index value
string join -- / $split_pwd[..$i] | string replace '~' $HOME
                            ^
in command substitution
        called on line 24 of file ~/.config/fish/functions/_tide_pwd.fish
in function '_tide_pwd'
        called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
        called on line 25 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution
~/.config/fish/functions/_tide_pwd.fish: Unknown error while evaluating command substitution
in function '_tide_pwd'
        called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
        called on line 25 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution
~/.config/fish/functions/fish_prompt.fish (line 29): Invalid index value
    string unescape $_tide_add_newline $$~/.config/fish/f_tunctions/_tide_piwd.fish (line 1)d: Invalid index evalue
string joi_n -- / $split_pwprd[..$i] | stringo replace '~' $HOmME
             p               ^t
in command subs_titution
        calledv on line 24 of faile ~/.config/firsh/functions/_ti[de_pwd.fish
in f1]unction '_tide_p[2wd'
        called on l.ine 1 of file ~/..config/fish/fun]ctions/_tide_pro
mpt.fish
in comm and substitution
        called on line  25 of file ~/.c onfig/fish/funct ions/_tide_promp t.fish
in functi on '_tide_prompt '
in command sub stitution
                                       ~/.config/fish/f unctions/_tide_p wd.fish: Unknown  error while eva luating command  substitution
in  function '_tide_ pwd'
        called on  line 1 of file ~ /.config/fish/fu^nctions/_tide_pr
ompt.fish
in comimand substitutionn
        called on lin e 25 of file ~/.fconfig/fish/funcutions/_tide_promnpt.fish
in functcion '_tide_promptt'
in command suiobstitution
n 'fish_prompt'
in command substitution
#### Environment

Output of `tide bug-report`: 

```

```

**Comment by IlanCosman** [comment]
I think you're not using the latest version of Fish.

**Comment by ryanbbrownavanade** [comment]
Let me give that a try.

**Comment by ryanbbrownavanade** [comment]
Yep ubuntu installed 3.1 from apt-get. I'll have to see what I can do to upgrade.

**Comment by ryanbbrownavanade** [comment]
Followed process outlined https://launchpad.net/~fish-shell/+archive/ubuntu/release-3 and got fish upgraded to 3.3.x

**Comment by ryanbbrownavanade** [comment]
Welp, installing with fisher didn't work, but at least the process terminated and gave me back my prompt!

**
![image](https://user-images.githubusercontent.com/40359080/133857375-ddd1fe4b-9017-499d-9c19-21d49c6681c4.png)
**

**Comment by ryanbbrownavanade** [comment]
Now attempting to start fish gives me 'set: You provided 1 indexes but 0 values' error.

**Comment by IlanCosman** [comment]
Have you tried deleting the Fish configuration and reinstalling?
```
rm -r $__fish_config_dir
--> *close your terminal and reopen* <--
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher install ilancosman/tide@v5
```

**Comment by ryanbbrownavanade** [comment]
That's a great next step. I'll give that a try.

From: Ilan Cosman ***@***.***>
Sent: Friday, September 17, 2021 5:00 PM
To: IlanCosman/tide ***@***.***>
Cc: Ryan Brown ***@***.***>; Author ***@***.***>
Subject: [External] Re: [IlanCosman/tide] Unable to install in WSL Ubuntu-20.04 (#201)


Have you tried deleting the Fish configuration and reinstalling?

rm -r $__fish_config_dir

--> *close your terminal and reopen* <--

curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher

fisher install ***@***.***

-
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FIlanCosman%2Ftide%2Fissues%2F201%23issuecomment-922103886&data=04%7C01%7Cryan.b.brown%40avanade.com%7C9d2c78a436814b21740d08d97a2672bf%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637675127834083716%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ixfACQykiuB%2FR%2FKQLB1aBJ%2BljTmBzmpv%2F4GJGEwMYH0%3D&reserved=0>, or unsubscribe<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJT5JKCLF4ZOXNDHJ6ERDXDUCO24XANCNFSM5EIIJQ2A&data=04%7C01%7Cryan.b.brown%40avanade.com%7C9d2c78a436814b21740d08d97a2672bf%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637675127834088705%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CFkA1Om9%2FMb9Wz31WWfmsu9fchhJn%2B9hMz8CRXANLIE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cryan.b.brown%40avanade.com%7C9d2c78a436814b21740d08d97a2672bf%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637675127834093702%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=DybYmM7GQ6bkMNZacOa7cENsSbJld%2FeXNJWEBKMvWRQ%3D&reserved=0> or Android<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Cryan.b.brown%40avanade.com%7C9d2c78a436814b21740d08d97a2672bf%7Ccf36141cddd745a7b073111f66d0b30c%7C0%7C0%7C637675127834098681%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=yD4ykGWaC77huRN5uNztgvyh0SP7WnO9b3KMzgBwdbQ%3D&reserved=0>.

**Comment by ryanbbrownavanade** [comment]
That worked!

**Comment by IlanCosman** [comment]
Lovely 😄
