### ISSUE TITLE
My custom item is not shown as I expected

### ISSUE THREAD

**Issue by yongyili** [IlanCosman/tide#204]
Hi, 
I want to add a custom item to show AWS Profile and Region.

Therefore, I add a `_tide_item_aws.fish` under `~/.config/fish/functions`, the content is:
```fish
function _tide_item_aws
    if [ -n $AWS_PROFILE ]
        _tide_print_item aws {$AWS_PROFILE}/{$AWS_DEFAULT_REGION}
    end
end
```

When `$AWS_PROFILE` is not set, there is still an empty item in the prompt, like blow image:
![image](https://user-images.githubusercontent.com/2041418/134712399-c7c94e63-c44e-49d3-87b8-a874fdc07f86.png)
How can I hide my custom item when `$AWS_PROFILE` is not set?

When ` $AWS_PROFILE` is set, it shows an ugly white triangle in the prompt:
![image](https://user-images.githubusercontent.com/2041418/134712683-a9ac01bd-44b2-48b0-9d50-d45016a7600e.png)

I wish the color should be shown as Git item as show in below image:
![image](https://user-images.githubusercontent.com/2041418/134713238-50712aea-e968-4a36-b079-7099dc987f7d.png)
 How can I fix the color of my custom item?

Thank you very much.

**Comment by IlanCosman** [comment]
1. You need to add quotes around `$AWS_PROFILE`:
```fish
if test -n "$AWS_PROFILE"
```
2. You haven't [set the colors for the item](https://github.com/IlanCosman/tide/wiki/Custom-items).
