### ISSUE TITLE
items character and status not working properly together

### ISSUE THREAD

**Issue by pvsmpraveen** [IlanCosman/tide#205]
#### Steps to reproduce

1. Added 'character' to tide_left_prompt_items and 'status' to tide_right_prompt_items.
2. status is not working as expected, I expect green box to be present, but it becomes inactive, but when error red box pops up
3. After removing 'character' green box works as expected

#### Screenshots

**With 'character' and 'status' (expecting green box in middle)**

![Screenshot 2021-09-25 at 7 16 03 PM](https://user-images.githubusercontent.com/16336470/134773741-0a3e21f4-fabd-450b-abca-ea70d80828ed.png)

**Without 'character' and only 'status' (works fine)** 

![Screenshot 2021-09-25 at 7 15 42 PM](https://user-images.githubusercontent.com/16336470/134773775-0154bb28-8a11-42c6-ab71-ec1d227bd352.png)

#### Environment

Output of `tide bug-report`: 

fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: Mac OS Catalina
terminal emulator: Mac terminal

#### Additional context

**_My global configs in config.fish_**

**What is not working :** 
```
set --global tide_right_prompt_items cmd_duration status time 
set --global tide_left_prompt_items os pwd git newline character

```
**What is working : (removing character)**
```
set --global tide_right_prompt_items cmd_duration status time 
set --global tide_left_prompt_items os pwd git newline
```

**Comment by IlanCosman** [comment]
This is currently intended. `character` already tells you whether the command succeeded or failed, so `status` only appears in more complex cases.

**Comment by pvsmpraveen** [comment]
How to force status to appear? like is there any status_always_show true option?

**Comment by IlanCosman** [comment]
Not currently.
