### ISSUE TITLE
`BrokenPipeError` when enter key held (with latest version).

### ISSUE THREAD

**Issue by cole-wilson** [IlanCosman/tide#206]
#### Describe the bug

Tide raises `BrokenPipeError` and dumps error to console when multiple empty prompts are shown repeatedly.

#### Steps to reproduce

1. Run fish (`v3.3.1`) with tide.
2. Hold enter down.
3. See error.

#### Screenshots
<img width="605" alt="Screen Shot 2021-09-25 at 10 01 14 AM" src="https://user-images.githubusercontent.com/49500253/134780068-1ff823cd-bf8d-45e3-be9d-50178f15d6bd.png">

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-kitty
os: macOS Big Sur (11.5.2)
terminal emulator: kitty
```

**Comment by IlanCosman** [comment]
#143
