### ISSUE TITLE
git icon causing unexpected tab space towards the right

### ISSUE THREAD

**Issue by pvsmpraveen** [IlanCosman/tide#207]
#### Steps to reproduce

1. Set tide_git_icon to "\uE0A0"
2. Go to any git repo
3. sees unexpected tab spacing toward the right

#### Screenshots

![Screenshot 2021-09-26 at 2 05 46 AM](https://user-images.githubusercontent.com/16336470/134785449-43baf0fe-728e-4e7d-aeea-2f4c47dc2dc8.png)

#### Environment

Output of `tide bug-report`: 

fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: Mac OS Catalina
terminal emulator: iterm2

#### Additional context

**config.fish** 
```
set --global tide_git_icon "\uE0A0"
set --global tide_right_prompt_items time
set --global tide_left_prompt_items os pwd git newline character
```

**Comment by IlanCosman** [comment]
Oh, that's fun. You need to unquote `"\uE0A0"`.

```fish
ilan@arch ~> set --global tide_git_icon "\uE0A0"
ilan@arch ~> string length $tide_git_icon 
6
ilan@arch ~> set --global tide_git_icon \uE0A0
ilan@arch ~> string length $tide_git_icon
1
```

Basically, you're setting the icon to the string "\uE0A0". Until it is explicitly unescaped, it will remain as a string.

**Comment by pvsmpraveen** [comment]
Ah okay, I thought since there are special characters I need to escape it, thanks for the help.

btw why does it add a tab?

**Comment by IlanCosman** [comment]
> btw why does it add a tab?

I'm not sure 🤷‍♂️
