### ISSUE TITLE
Extraneous output on scp and troubles with ssh. 

### ISSUE THREAD

**Issue by jduhamel** [IlanCosman/tide#21]
**Describe the bug**

When using scp or tramp (in emacs) I get superfluous output 
string replace: Expected at least 2 args, got 1
string replace: Expected at least 2 args, got 1
string replace: Expected at least 2 args, got 1

**To Reproduce**

1. Set 'TERM' to 'dumb'
2. Run 'fish'
3. See error

**Expected behavior**
I've narrowed it down to ~/.config/fish/conf.d/_tide_Ω_init.fish when it calls _tide_pwd_set_max_length

I'm not sure of the best way to fix it. It only happens when TERM is dumb or session is non-interactive. I can fix the TERM is dumb by bracketing the _tide_Ω_init.fish with `if test "TERM" != "dumb"` but that doesn't fix the non interactive part. 

**Screenshots**

**Environment (please complete the following information):**

- OS: (e.g. Ubuntu 20.04)
Arch
- Fish Version: (run `fish --version`)
fish, version 3.1.2
- Tide Version: (run `tide --version`)
2.3.0
**Additional context**

**Comment by jduhamel** [comment]
I worked around it with this. 
feels cludgy but..

`if status is-interactive
  if test "$TERM" != "dumb"
    _tide_count_left_prompt_height

    _tide_git_prompt_set_vars

    _tide_pwd_set_max_length
    _tide_pwd_var_change

    _tide_detect_os
  end
end`

**Comment by IlanCosman** [comment]
Thanks for the report @jduhamel , I'll look into this :) This is a workflow I've never used.

**Comment by jduhamel** [comment]
I sort of figured. Easy way to test is to spin up a vm/cloud instance with fish shell as default. setup tide. Go to a different machine and scp a file to the vm/cloud.

**Comment by IlanCosman** [comment]
I figured out the issue, and it's one that I believe I've run into before.

`string replace foo (set_color $doesNotExist)"hello" foo/bar` doesn't work because command substitution removes the entire argument when it prints nothing for some reason.

When the `TERM` is `dumb`, colors dont work and therefore `set_color` won't print anything. This in turn leads to the entire argument being removed and then `string replace` erroring.

I'll ask around and see what I can do to fix this.

**Comment by jduhamel** [comment]
It also occurs with non-interactive. I don't know what TERM scp sets but that also seems to trigger it. hence the if satus ninteractive. 

--Joe

**Comment by IlanCosman** [comment]
Hi Joe, can you try installing Tide from the `dumb` branch to see if I've fixed the issue?

```console
curl -sL git.io/tide | source && tide_install dumb
````

**Comment by jduhamel** [comment]
Looks fixed. Thanks.
