### ISSUE TITLE
Ability to configure underlying background colors

### ISSUE THREAD

**Issue by eproxus** [IlanCosman/tide#216]
#### Is your feature request related to a problem? Please describe

I find it hard to distinguish between prompts, even when using the solid line as a delimiter in a multiline prompt. Configuring the background of individual items is not enough since it doesn't color the whole line.

#### Describe the solution you'd like

A way to configure the global background color of the first line when using a multiline prompt. (Perhaps even a way to configure the background of any prompt lines/sections if possible?.

#### Additional context

I'm used to a theme like this:

<img width="439" alt="Screen Shot 2021-10-28 at 10 29 13" src="https://user-images.githubusercontent.com/112878/139217830-f1fec148-780d-4dc4-a727-eb5f2f16bb8a.png">

I find it more legible than the dots or line that Tide draws (I'd ideally like to keep those as well, just to be able to set the underlying background color).

Compare against Tide:
<img width="439" alt="Screen Shot 2021-10-28 at 10 32 02" src="https://user-images.githubusercontent.com/112878/139218392-015fcb36-f981-4b89-8af7-e794e387a010.png">

**Comment by IlanCosman** [comment]
I personally don't have much problem telling those lines apart, but I can see how one might have trouble.

Your options are basically
1. Enable `tide_prompt_add_newline_before`. It'll make telling lines apart easier, though it'll come at the price of scrollback history.
2. Use a powerline theme, that'll make it much more obvious which lines are which. 
3. Use a dark terminal theme.

I don't feel this feature offers enough to enough users to justify the code expense, sorry.
