### ISSUE TITLE
Use branding colors in os icons

### ISSUE THREAD

**Issue by IlanCosman** [IlanCosman/tide#220]
Currently we display all os icons in monochrome.
However, whenever possible, I'm a big fan of following brand guidelines and using the correct colors.
So here are some example changes that might be made:

| Current | Proposed |
| ------- | -------- |
| ![image](https://user-images.githubusercontent.com/6318351/139559239-cbd992b2-d542-4a9d-b63c-0aee9baecdc0.png) |     ![image](https://user-images.githubusercontent.com/6318351/139559341-b057f105-cd3d-4370-a679-6b67d96a767b.png) |  
![image](https://user-images.githubusercontent.com/6318351/139559216-129c141e-561d-4640-b9c9-7736b5bff24e.png)  |     ![image](https://user-images.githubusercontent.com/6318351/139559194-5e40f7e0-1fca-48cf-97a0-118b76a2b6c7.png)    |
| ![image](https://user-images.githubusercontent.com/6318351/139559438-32b516df-157a-44de-87d6-9975fc2710fd.png)    |  ![image](https://user-images.githubusercontent.com/6318351/139559424-52e062fc-d9d7-4d32-8c57-ce3f6da08547.png) |
|  ![image](https://user-images.githubusercontent.com/6318351/139559466-e5dec4f8-5a0a-4aaf-85f1-a07304cf57e9.png) |    ![image](https://user-images.githubusercontent.com/6318351/139559450-3bdd3cdd-2fc3-4c9a-866d-7f8404d42326.png)   |
| ![image](https://user-images.githubusercontent.com/6318351/139559524-094d8620-e8f9-41ca-a642-2923978d31c7.png) | ![image](https://user-images.githubusercontent.com/6318351/139559574-4f85c044-912e-4dd3-8a4e-a1fc69da31b3.png) |

Totally open to comments 😄

**Comment by SweepingBishops** [comment]
Hello! I'm new here but I would like to contribute too.
So, how many brands do you plan to support? Even only the most common distros can be a lot.

**Comment by IlanCosman** [comment]
@SweepingBishops Basically anything with a nerd font icon. You can take a look at the current work here: https://github.com/IlanCosman/tide/blob/color-os-logos/functions/_tide_detect_os.fish

I think it's all done actually. Just some work needed to merge it in.

**Comment by SweepingBishops** [comment]
Is there any way I can contribute?

**Comment by IlanCosman** [comment]
Not really right now 😞

If you happen to be missing any items for the tools you use, those would be appreciated additions 😄

**Comment by whitelynx** [comment]
I love this idea! Since it looks like you have the implementation pretty much done, would you be up for opening a PR?
