### ISSUE TITLE
Crashes my fish shell

### ISSUE THREAD

**Issue by Ngomana** [IlanCosman/tide#222]
#### Steps to reproduce

`omf install https://github.com/IlanCosman/tide.git `

3. See error
`zsh: terminated  fish`
#### Screenshots

https://user-images.githubusercontent.com/61317733/139633167-3d3710ef-dd5f-4a2c-adf0-2912c46168ab.mov

and now i'm unable uninstall it as i can not seem to find the root files, even runing `omf uninstall tide`

**Comment by IlanCosman** [comment]
omf is not listed as an installation option because it does not work.

What version of fish are you using?

**Comment by Ngomana** [comment]
i'm using the latest version of fish, by the way i was using omf before fisher
