### ISSUE TITLE
Missing fonts/styles shows '?' for icons

### ISSUE THREAD

**Issue by Lykos115** [IlanCosman/tide#223]
![image](https://user-images.githubusercontent.com/29809477/139790149-0e4bb235-8f1c-4500-80e9-2a5c14c87d3d.png)

### I also tried doing it with out hyper terminal editor with no success
Any help would be greatly appreciated,

![image](https://user-images.githubusercontent.com/29809477/139790045-b3dfaa54-a6dc-4370-b5c2-d716ba02888c.png)

**Comment by IlanCosman** [comment]
Have you configured your terminal to use the font? From p10k docs:
> Open Hyper → Edit → Preferences and change the value of fontFamily under module.exports.config to MesloLGS NF.
