### ISSUE TITLE
Shorten current directory length

### ISSUE THREAD

**Issue by leomayer** [IlanCosman/tide#227]
#### Describe the bug

Setting ` set tide_prompt_min_cols 2`  doesn't have any effect for shortening the path

#### Steps to reproduce

1.  set tide_prompt_min_cols 2  

#### Screenshots

![Bildschirmfoto von 2021-11-23 15-07-49](https://user-images.githubusercontent.com/2641128/143039076-af13f1fc-3251-4007-bc06-b6c41caccc33.png)

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: OpenSuse Leap
terminal emulator: 
```

**Comment by IlanCosman** [comment]
`tide_prompt_min_cols`
> if using one-line prompt, Tide attempts to have at least this many columns for you to type in

You want to make `tide_prompt_min_cols` a big number, not a small number.

**Comment by leomayer** [comment]
Thx for the hint - it better.
But as far as I remember in the previous version the path was truncated to one char only. Now its somehow strange truncated. Is there a way to truncate it to 1 or 2 chars uniformly?

![Bildschirmfoto von 2021-11-23 15-26-02](https://user-images.githubusercontent.com/2641128/143042194-f21cdbbe-ae50-412c-874a-bb0b1fc1b117.png)

**Comment by IlanCosman** [comment]
> Is there a way to truncate it to 1 or 2 chars uniformly?

No. Tide is being more intelligent than that.

From the features section:

> When the full directory doesn't fit, the leftmost segment is truncated to its shortest unique prefix. In the example above, `Documents` becomes `Doc` instead of `D` because that could be confused with `Downloads`. Important segments are bold and never truncated. These include the first and the last segments, roots of Git repositories etc.

**Comment by leomayer** [comment]
Ok - thx for the response.
