### ISSUE TITLE
Visual bug like .. glitch ?

### ISSUE THREAD

**Issue by Aperrix** [IlanCosman/tide#228]
#### Describe the bug

I just do a fresh install of fish, fisher and tide and now my terminal is glitched. To be sure it's a tide problem and not fish or other, i try to uninstall it, reboot and it's working well.

So please can you help me or deploy a bug fix ? It's a shame because tide is the best theme i have used and this bug is very annoying 😩 

#### Steps to reproduce

Simply type whatever in the terminal

#### Screenshots

![image](https://user-images.githubusercontent.com/26674548/143416554-2b5d6804-5c53-42f1-b1c9-ef2caad84a24.png)

#### Environment
```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: fedora 35
terminal emulator: terminology
```

**Comment by IlanCosman** [comment]
I can't reproduce on Arch with terminology.

This kind of glitch is certainly not a Tide bug. Tide created the prompt correctly, it was just cut off by your terminal.

Does this same bug happen with a simple prompt like

```fish
function on_foo --on-variable foo
    set -g repainting
    commandline -f repaint
end

function fish_prompt
    set -e repainting || fish --command "sleep .05;set -U foo $PWD" &

    echo
    echo $foo
    echo '>'
end
```
