### ISSUE TITLE
Setting background color for prompt_icon_connection

### ISSUE THREAD

**Issue by ruudk** [IlanCosman/tide#229]
Is it possible to set a background color for the padding between the left and right prompt?

I can change the character with `tide_prompt_icon_connection`. But I want to keep it as a space, but just a different bg color.

**Comment by IlanCosman** [comment]
No, it's not currently possible, but you can hack your way around it. 😄
Set `tide_prompt_icon_connection` to the full block character: `█`
Then set `tide_prompt_color_frame_and_connection` to whatever you would have wanted your bg color to be.

**Comment by ruudk** [comment]
Clever, that will work :) Thanks!
