### ISSUE TITLE
When hitting `Ctrl+L` twice very fast, it produces an error

### ISSUE THREAD

**Issue by TonalidadeHidrica** [IlanCosman/tide#232]
#### Describe the bug

When I type `Ctrl+L` twice fast (like 200ms interval or so), the following happens:
- For the first time, it shows normal prompt
```
~ ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 23:00:47
❯
```
- For the second time, it outputs some mysterious errors:
```
~ ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 23:02:38
❯ Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
BrokenPipeError: [Errno 32] Broken Pipe
```
  - soon after that, the second line is overwritten by a new prompt:
```
~ ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 23:03:47
❯ Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='UTF-8'>
~ ───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────── 23:03:52
❯ 
```

#### Steps to reproduce

1. Type `Ctrl+L` twice.

#### Screenshots

Not available now, but if necessary, I'll add it somehow.

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: screen-256color
os: MacOS Big Sur 11.6
terminal emulator: tmux on iTerm2
```

#### Additional context

It only happened in Mac, but not in Ubuntu 20.04 on WSL on Windows Terminal.  It happens inside or outside `tmux`.

**Comment by IlanCosman** [comment]
Is this https://github.com/IlanCosman/tide/issues/143? Do you have Conda installed?

**Comment by TonalidadeHidrica** [comment]
@IlanCosman Uh-oh, exactly.  I've been neglecting opening the issue just because it contains only "conda" in the title, which is seemingly unrelated.  Thanks a lot, I'm closing it as a duplicate.

**Comment by TonalidadeHidrica** [comment]
@IlanCosman But wait, I commented out the

```fish
eval (eval /usr/local/Caskroom/miniconda/4.6.14/miniconda3/bin/conda "shell.fish" "hook" $argv)
```

line in my `config.fish`, but the issue still persists.  Am I missing something?
