### ISSUE TITLE
Lingering characters in left prompt when not using right prompt

### ISSUE THREAD

**Issue by alexavdb** [IlanCosman/tide#233]
I use Tide with only a two-line left prompt, thus with `tide_right_prompt_items` unset. When my prompt gets shorter between commands the additional characters from the previous prompt remain visible in the new prompt. Two screenshots to clarify the issue:

![tide_example](https://user-images.githubusercontent.com/95910348/145569738-c9332824-e53e-4e12-848a-43a7a91cef9a.png)

![20211210-125944](https://user-images.githubusercontent.com/95910348/145571189-7b53c5b8-053e-46f5-8693-e7e2d7b48ae5.png)

In both cases everything following the (first) 'main' should no longer be in the prompt.

The current solutions I see are either
- press Enter an additional time whenever this occurs, but as the second screenshot shows it can be difficult to notice;
- set `tide_prompt_icon_connection` to a space so that any lingering characters are explicitly overwritten by spaces. But this tends to mess up my prompt by adding additional white space between the two prompt lines when decreasing the size my terminal window.

Would there be a cleaner way to deal with this issue that avoids the downsides of the above solutions?

(Note, I do not think this is a bug in Tide, but rather that I might be using Tide in a way it was not designed for.)

**Comment by IlanCosman** [comment]
> (Note, I do not think this is a bug in Tide, but rather that I might be using Tide in a way it was not designed for.)

Yah unfortunately that is the case.

> set `tide_prompt_icon_connection` to a space so that any lingering characters are explicitly overwritten by spaces. But this tends to mess up my prompt by adding additional white space between the two prompt lines when decreasing the size my terminal window.

This is how you're supposed to do it. And yah, it does have some drawbacks 😞

I think I _might_ be able to solve this problem if I move some formatting stuff to the main shell, as opposed to having it all be done in the subshell. I'll look into it.

**Comment by alexavdb** [comment]
> > (Note, I do not think this is a bug in Tide, but rather that I might be using Tide in a way it was not designed for.)
> 
> Yah unfortunately that is the case.

I suspected as much :smile: 

> > set `tide_prompt_icon_connection` to a space so that any lingering characters are explicitly overwritten by spaces. But this tends to mess up my prompt by adding additional white space between the two prompt lines when decreasing the size my terminal window.
> 
> This is how you're supposed to do it. And yah, it does have some drawbacks disappointed

Okay, I will continue to use this solution for the time being then.

> I think I _might_ be able to solve this problem if I move some formatting stuff to the main shell, as opposed to having it all be done in the subshell. I'll look into it.

That would be great if possible. But feel free to close this issue if you want, the connection icon solution is not ideal but it is not a showstopper either.
In any case, thank you for the quick feedback.

**Comment by IlanCosman** [comment]
Hmm, I can't actually reproduce this using tide v5. Please tell me if I'm doing this correctly:

1. Erase `tide_prompt_icon_connection` and `tide_prompt_icon_connection` with `set -e`.
2. Restart shell.
3. `cd` into clean git directory, see branch name.
4. `touch test.txt`, see branch name and `?1`
5. `rm` test.txt`, see just branch name.

**Comment by IlanCosman** [comment]
Ah ok, figured it out. The problem appears with `fish 3.3.1`, but doesn't appear with fish master branch.

**Comment by alexavdb** [comment]
Interesting so the problem is with fish itself instead of Tide. Thanks for looking into to this.
I consider this closed than, as it should be resolved when fish 3.4.0 is released.
