### ISSUE TITLE
"jobs" item always on, when "fishgretel/fasd" fish plugin is installed

### ISSUE THREAD

**Issue by jinliu** [IlanCosman/tide#234]
#### Describe the bug

With both tide and fishgretel/fasd installed, and the "jobs" item is enabled, that indicator is always visible after any successful commands.

#### Steps to reproduce

1. Run fisher install fishgretel/fasd
2. Enable "jobs" item
3. Run ls
4. "jobs" gear icon is visible, even when no jobs running

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: Archlinux
terminal emulator: Konsole
```

#### Additional context

The problem can be worked around by modifying the following line:
~/.config/fish/conf.d/__fasd_run.fish:17
```command fasd --proc (__fasd_expand_vars $argv) > "/dev/null" 2>&1 &```
removing the "&" at the end.

In the fish_postexec hook, the fasd plugin starts a job to record the last command. Therefore, the "jobs --query" later in tide tests true.
Is it possible that the "jobs --query" test runs earlier, maybe in another fish_postexec hook (somehow earlier than the fasd hook), so the two can work together?

**Comment by IlanCosman** [comment]
> Is it possible that the "jobs --query" test runs earlier, maybe in another fish_postexec hook (somehow earlier than the fasd hook), so the two can work together?

That would have some drawbacks that I'm not willing to make right now, especially for a smallish and unmaintained tool like `fasd`. Sorry 😞 

There's really not much need for that line to be backgrounded though. It only takes about 12 ms on my machine, 4 of which comes from the non-backgrounded `(__fasd_expand_vars $argv)` part.
