### ISSUE TITLE
Automatically update OS icon on shell initilization

### ISSUE THREAD

**Issue by uajqq** [IlanCosman/tide#236]
#### Is your feature request related to a problem? Please describe

I use Syncthing to keep my config files synchronized across a few different systems, including the `fish_variables` file. Whenever I SSH into a different system (e.g. from MacOS to Ubuntu), the OS icon does not update, because it's being read from `fish_variables`. I've added a line to my `config.fish` file to fix this issue:
```
set -U tide_os_icon (_tide_detect_os)
```

#### Describe the solution you'd like

Ideally, Tide would automatically check which OS is running each time it is initialized, not just the first time it is installed or configured.

**Comment by IlanCosman** [comment]
I won't be implementing this because
1. I want to allow users to override the logo if they choose
2. It's quite a bit of extra startup time. Something like 40% of the default fish startup time.
3. Your use case is fairly exceptional I think

Thanks for the suggestion though 😄
