### ISSUE TITLE
Strange newlines are inserted when use vi key bindings

### ISSUE THREAD

**Issue by silvercrown07** [IlanCosman/tide#237]
#### Describe the bug

when use tide with fish vi key bindings, some strange newlines are inserted before the prompt and push the prompt down.

#### Steps to reproduce

under macOS:
1. install fish via homebrew(`brew install fish`)
2. install fisher (`curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher`)
3. install tide (`fisher install IlanCosman/tide@v5`)
4. (if style matters) choices: 3(Rainbow) -> 1(True color) -> 2(24-hour format) -> 1(Angled) -> 1(Sharp) -> 1(Flat) -> 2 (Two lines) -> 3(Solid) -> 1(No frame) -> 3(Dark) -> 2(Sparse) -> 1(Few icons)
5. enable vi mode (`fish_vi_key_bindings`)
6. the issue can be triggered under following cases:
    - the mode changes(say from `insert` to `normal`) and there're already some contents
    - paste things under `insert` mode

#### Screenshots

screenshot when changing the mode:
![image](https://user-images.githubusercontent.com/44765224/147377886-ccd20632-eea1-43e9-b5c6-a94bc398091f.png)

screenshot when pasting things:
![image](https://user-images.githubusercontent.com/44765224/147377879-1501dc8c-051e-4523-b38b-5e07a0acaeb9.png)

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-kitty
os: macOS Big Sur
terminal emulator: kitty
```

#### Additional context

I can only reproduce under macOS(see environment section), tried also on linux but unable to reproduce

**Comment by IlanCosman** [comment]
I can't reproduce using basically the same environment. Sorry 😞 Hopefully Fish 3.4 will release soon, followed by Tide 5.1, and those might fix it 🤷‍♂️

**Comment by silvercrown07** [comment]
no worries, i'll then cross my fingers for the new releases, and thank you for putting so much effort in maintaining such an awesome project!

then maybe we close this ticket for now?

**Comment by silvercrown07** [comment]
oh did another search and realized this could be [a upstream issue](https://github.com/fish-shell/fish-shell/issues/8233)

for guys who also encountered this, my issue was gone after adding following in my `config.fish`
```fish
function fish_vi_cursor; end
```
hope this also works for you : )

closing this ticket
