### ISSUE TITLE
Breaking my fish

### ISSUE THREAD

**Issue by alanpi** [IlanCosman/tide#238]
#### Steps to reproduce
Fresh install
1. Install fish
2. install oh myfish
3. install fisher
4. fisher install IlanCosman/tide@v5

#### Screenshots

<pre>Willkommen zu fish, der freundlichen interaktiven Shell
Type `help` for instructions on how to use fish
<span style="background-color:#06989A"><font color="#EEEEEC">⋊&gt;</font></span> <font color="#999900">~</font> <font color="#005FD7">fisher</font> <font color="#00AFFF"><u style="text-decoration-style:single">install</u></font> <font color="#00AFFF">IlanCosman/tide@v5</font>                          <font color="#555555">23:39:09</font>
<b>fisher install version 4.3.1</b>
Fetching <u style="text-decoration-style:single">https://codeload.github.com/IlanCosman/tide/tar.gz/v5</u>
Installing <b>IlanCosman/tide@v5</b>
           /home/alan/.config/fish/functions/_tide_detect_os.fish
           /home/alan/.config/fish/functions/_tide_find_and_remove.fish
           /home/alan/.config/fish/functions/_tide_item_character.fish
           /home/alan/.config/fish/functions/_tide_item_chruby.fish
           /home/alan/.config/fish/functions/_tide_item_cmd_duration.fish
           /home/alan/.config/fish/functions/_tide_item_context.fish
           /home/alan/.config/fish/functions/_tide_item_git.fish
           /home/alan/.config/fish/functions/_tide_item_go.fish
           /home/alan/.config/fish/functions/_tide_item_jobs.fish
           /home/alan/.config/fish/functions/_tide_item_kubectl.fish
           /home/alan/.config/fish/functions/_tide_item_newline.fish
           /home/alan/.config/fish/functions/_tide_item_node.fish
           /home/alan/.config/fish/functions/_tide_item_os.fish
           /home/alan/.config/fish/functions/_tide_item_php.fish
           /home/alan/.config/fish/functions/_tide_item_rustc.fish
           /home/alan/.config/fish/functions/_tide_item_shlvl.fish
           /home/alan/.config/fish/functions/_tide_item_status.fish
           /home/alan/.config/fish/functions/_tide_item_time.fish
           /home/alan/.config/fish/functions/_tide_item_vi_mode.fish
           /home/alan/.config/fish/functions/_tide_item_virtual_env.fish
           /home/alan/.config/fish/functions/_tide_print_item.fish
           /home/alan/.config/fish/functions/_tide_prompt.fish
           /home/alan/.config/fish/functions/_tide_pwd.fish
           /home/alan/.config/fish/functions/_tide_remove_unusable_items.fish
           /home/alan/.config/fish/functions/_tide_sub_bug-report.fish
           /home/alan/.config/fish/functions/_tide_sub_configure.fish
           /home/alan/.config/fish/functions/fish_mode_prompt.fish
           /home/alan/.config/fish/functions/fish_prompt.fish
           /home/alan/.config/fish/functions/tide
           /home/alan/.config/fish/functions/tide.fish
           /home/alan/.config/fish/conf.d/_tide_init.fish
           /home/alan/.config/fish/completions/tide.fish
status: Subcommand &apos;dirname&apos; is not valid
type: Unbekannte Option &apos;--query&apos;
/usr/share/fish/functions/type.fish (Zeile 7): 
    argparse -n type -x t,p,P $options -- $argv
    ^
in function &apos;type&apos; with arguments &apos;--query chruby&apos;
	called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function &apos;_tide_remove_unusable_items&apos;
	called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;
type: Unbekannte Option &apos;--query&apos;
/usr/share/fish/functions/type.fish (Zeile 7): 
    argparse -n type -x t,p,P $options -- $argv
    ^
in function &apos;type&apos; with arguments &apos;--query git&apos;
	called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function &apos;_tide_remove_unusable_items&apos;
	called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;
type: Unbekannte Option &apos;--query&apos;
/usr/share/fish/functions/type.fish (Zeile 7): 
    argparse -n type -x t,p,P $options -- $argv
    ^
in function &apos;type&apos; with arguments &apos;--query go&apos;
	called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function &apos;_tide_remove_unusable_items&apos;
	called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;
type: Unbekannte Option &apos;--query&apos;
/usr/share/fish/functions/type.fish (Zeile 7): 
    argparse -n type -x t,p,P $options -- $argv
    ^
in function &apos;type&apos; with arguments &apos;--query kubectl&apos;
	called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function &apos;_tide_remove_unusable_items&apos;
	called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;
type: Unbekannte Option &apos;--query&apos;
/usr/share/fish/functions/type.fish (Zeile 7): 
    argparse -n type -x t,p,P $options -- $argv
    ^
in function &apos;type&apos; with arguments &apos;--query node&apos;
	called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function &apos;_tide_remove_unusable_items&apos;
	called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;
type: Unbekannte Option &apos;--query&apos;
/usr/share/fish/functions/type.fish (Zeile 7): 
    argparse -n type -x t,p,P $options -- $argv
    ^
in function &apos;type&apos; with arguments &apos;--query php&apos;
	called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function &apos;_tide_remove_unusable_items&apos;
	called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;
type: Unbekannte Option &apos;--query&apos;
/usr/share/fish/functions/type.fish (Zeile 7): 
    argparse -n type -x t,p,P $options -- $argv
    ^
in function &apos;type&apos; with arguments &apos;--query rustc&apos;
	called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function &apos;_tide_remove_unusable_items&apos;
	called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;
type: Unbekannte Option &apos;--query&apos;
/usr/share/fish/functions/type.fish (Zeile 7): 
    argparse -n type -x t,p,P $options -- $argv
    ^
in function &apos;type&apos; with arguments &apos;--query python python3&apos;
	called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish
in function &apos;_tide_remove_unusable_items&apos;
	called on line 6 of file ~/.config/fish/functions/fish_prompt.fish
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;
status: Subcommand &apos;dirname&apos; is not valid
_load_config: Befehl nicht gefunden.
~/.config/fish/conf.d/_tide_init.fish (line 7): 
    _load_config lean
    ^
in function &apos;_tide_init_install&apos;
	called on line 1 of file ~/.config/fish/functions/fisher.fish
in event handler: handler for generic event &apos;_tide_init_install&apos;
	called on line 178 of file ~/.config/fish/functions/fisher.fish
_tide_finish: Befehl nicht gefunden.
~/.config/fish/conf.d/_tide_init.fish (line 8): 
    _tide_finish
    ^
in function &apos;_tide_init_install&apos;
	called on line 1 of file ~/.config/fish/functions/fisher.fish
in event handler: handler for generic event &apos;_tide_init_install&apos;
	called on line 178 of file ~/.config/fish/functions/fisher.fish
Configure tide prompt? [Y/n] n

Run <font color="#005FD7">tide</font> <font color="#00AFFF">configure</font> to customize your prompt.
complete: Zu viele Argumente

~/.config/fish/completions/tide.fish (Zeile 1): 
complete tide --no-files
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;

(Type &apos;help complete&apos; for related documentation)
complete: Zu viele Argumente

~/.config/fish/completions/tide.fish (Zeile 3): 
complete tide -x -n __fish_use_subcommand -a --help -d &quot;Print help message&quot;
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;

(Type &apos;help complete&apos; for related documentation)
complete: Zu viele Argumente

~/.config/fish/completions/tide.fish (Zeile 4): 
complete tide -x -n __fish_use_subcommand -a --version -d &quot;Print tide version&quot;
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;

(Type &apos;help complete&apos; for related documentation)
complete: Zu viele Argumente

~/.config/fish/completions/tide.fish (Zeile 5): 
complete tide -x -n __fish_use_subcommand -a bug-report -d &quot;Print info for use in bug reports&quot;
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;

(Type &apos;help complete&apos; for related documentation)
complete: Zu viele Argumente

~/.config/fish/completions/tide.fish (Zeile 6): 
complete tide -x -n __fish_use_subcommand -a configure -d &quot;Run the configuration wizard&quot;
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;

(Type &apos;help complete&apos; for related documentation)
complete: Zu viele Argumente

~/.config/fish/completions/tide.fish (Zeile 8): 
complete tide -x -n &apos;__fish_seen_subcommand_from bug-report&apos; -a --clean -d &quot;Run clean Fish instance and install Tide&quot;
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;

(Type &apos;help complete&apos; for related documentation)
complete: Zu viele Argumente

~/.config/fish/completions/tide.fish (Zeile 9): 
complete tide -x -n &apos;__fish_seen_subcommand_from bug-report&apos; -a --verbose -d &quot;Print full Tide configuration&quot;
^
from sourcing file ~/.config/fish/completions/tide.fish
	called on line 176 of file ~/.config/fish/functions/fisher.fish
in function &apos;fisher&apos; with arguments &apos;install IlanCosman/tide@v5&apos;

(Type &apos;help complete&apos; for related documentation)
Installed 1 plugin/s
jobs: Unbekannte Option &apos;--query&apos;

~/.config/fish/functions/fish_prompt.fish (Zeile 19): 
        jobs --query
        ^
in function &apos;fish_prompt&apos;
in command substitution

(Type &apos;help jobs&apos; for related documentation)
~/.config/fish/functions/fish_prompt.fish (line 29): Invalid index value
    string unescape $$_tide_prompt_var[1][2..]
                                          ^
in function &apos;fish_prompt&apos;
in command substitution
set_color: Expected argument for option b

~/.config/fish/functions/_tide_pwd.fish (Zeile 1): 
set_color normal -b $tide_pwd_bg_color; set_color $tide_pwd_color_dirs
^
in command substitution
	called on line 4 of file ~/.config/fish/functions/_tide_pwd.fish
in function &apos;_tide_pwd&apos;
	called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
	called on line 26 of file ~/.config/fish/functions/_tide_prompt.fish
in function &apos;_tide_prompt&apos;
in command substitution

(Type &apos;help set_color&apos; for related documentation)
~/.config/fish/functions/_tide_pwd.fish (line 11): Invalid index value
        set split_pwd_for_output $color_anchors$split_pwd[1]$reset_to_color_dirs $split_pwd[2..]
                                                                                               ^
in function &apos;_tide_pwd&apos;
	called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
	called on line 26 of file ~/.config/fish/functions/_tide_prompt.fish
in function &apos;_tide_prompt&apos;
in command substitution
set: You provided 1 indexes but 0 values
~/.config/fish/functions/fish_prompt.fish (line 29): Invalid index value
    string unescape $$_tide_prompt_var[1][2..]
                                          ^
in function &apos;fish_prompt&apos;
in command substitution
jobs: Unbekannte Option &apos;--query&apos;

~/.config/fish/functions/fish_prompt.fish (Zeile 19): 
        jobs --query
        ^
in function &apos;fish_prompt&apos;
in command substitution

(Type &apos;help jobs&apos; for related documentation)
Beendet
<font color="#4E9A06"><b>alan@pop-os</b></font>:<font color="#3465A4"><b>~</b></font>$ set_color: Expected argument for option b

~/.config/fish/functions/_tide_pwd.fish (Zeile 1): 
set_color normal -b $tide_pwd_bg_color; set_color $tide_pwd_color_dirs
^
in command substitution
	called on line 4 of file ~/.config/fish/functions/_tide_pwd.fish
in function &apos;_tide_pwd&apos;
	called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
	called on line 26 of file ~/.config/fish/functions/_tide_prompt.fish
in function &apos;_tide_prompt&apos;
in command substitution

(Type &apos;help set_color&apos; for related documentation)
~/.config/fish/functions/_tide_pwd.fish (line 11): Invalid index value
        set split_pwd_for_output $color_anchors$split_pwd[1]$reset_to_color_dirs $split_pwd[2..]
                                                                                               ^
in function &apos;_tide_pwd&apos;
	called on line 1 of file ~/.config/fish/functions/_tide_prompt.fish
in command substitution
	called on line 26 of file ~/.config/fish/functions/_tide_prompt.fish
in function &apos;_tide_prompt&apos;
in command substitution
set: You provided 1 indexes but 0 values
</pre>

#### Environment

Output of `tide bug-report`: 

```

```

**Comment by IlanCosman** [comment]
Old fish version.

**Comment by alanpi** [comment]
yes thanks alot. Iam using pop os and they had the 3.1 version. after i added  the fish repo and reinstalled  everything it worked
