### ISSUE TITLE
OS detection fails in non-systemd distributions

### ISSUE THREAD

**Issue by kudakeru** [IlanCosman/tide#24]
#### Describe the bug

cat: /etc/os-release: No such file or directory
math: Expected at least 1 args, got 0
cat: /etc/os-release: No such file or directory
math: Expected at least 1 args, got 0
Welcome to fish, the friendly interactive shell
Type `help` for instructions on how to use fish

#### Steps to reproduce

1. Launch new shell

#### Expected behavior
OS detection should check for /etc/lsb-release if /etc/os-release is not present

#### Screenshots
```fish
function _tide_detect_os_extract_os_release_info -a key
    set -l splitOsRelease (cat /etc/os-release | string split '=')
    set -l value $splitOsRelease[(math (contains --index $key $splitOsRelease)+1)]

    string trim --chars='"' $value | string lower
end
```

#### Environment (please complete the following information)

- Operating System: Artix
- Output of `tide bug-report`: 

```console
fish, version 3.1.2
tide, version 2.3.0
xterm-256color
```

**Comment by kudakeru** [comment]
Changing the function to the following at least eliminates the error about /etc/os-release:

`function _tide_detect_os_extract_os_release_info -a key
    if test -e /etc/os-release
      set -l splitOsRelease (cat /etc/os-release | string split '=')
    else
      set -l splitOsRelease (cat /etc/lsb-release | string split '=')
    end
    set -l value $splitOsRelease[(math (contains --index $key $splitOsRelease)+1)]

    string trim --chars='"' $value | string lower
end`

I'm not sure if the math error is related to this or not, though

**Comment by IlanCosman** [comment]
Powerlevel10k actually treats Artix specially.
https://github.com/romkatv/powerlevel10k/blob/a3727dcaefbfba04484ba0f979c62d070850eeed/internal/wizard.zsh#L1069-L1071

I'll look into this and think about the best way to deal with it; I've never used a non-systemd distro. Thanks for the report 😄

**Comment by IlanCosman** [comment]
Hi @kudakeru, can you try installing Tide from the `lsb-release` branch to check if the issue has been fixed?

```console
curl -sL git.io/tide | source && tide_install lsb-release
```

**Comment by kudakeru** [comment]
Installed and tested. Everything looks like it's working now.

**Comment by IlanCosman** [comment]
Great to hear, thanks for filing this issue @kudakeru 😄

**Comment by tdcook** [comment]
This appears to have resurfaced after edcc4f0e.

**Comment by IlanCosman** [comment]
Thanks 👍
