### ISSUE TITLE
Color and shape mismatch

### ISSUE THREAD

**Issue by jisuoqing** [IlanCosman/tide#241]
Hi! I was using the font `mesloLGS_NF` but got mismatches in color and shape as attached... Did I miss something? Thanks!

<img width="650" alt="Screen Shot 2022-01-03 at 11 01 11 PM" src="https://user-images.githubusercontent.com/15147123/147946010-3ffddde8-e5ae-40bf-9676-88b28b0f7056.png">

**Comment by IlanCosman** [comment]
The color thing is caused by Terminal.app. For the shape, try changing your font size up or down by 1.

**Comment by jisuoqing** [comment]
Thanks! However, tried the font size to an even number, and didn't work. The `blurred` mode looks quite different from the example. I'm quite confused since I'm setting up a new MacBook, so I shouldn't have ruined anything up in my system.

**Comment by IlanCosman** [comment]
Let me know if you figure it out 😞 Maybe try a different terminal, check the font, idk 🤷‍♂️

**Comment by jisuoqing** [comment]
Thanks! I can confirm that with a different terminal, this works great, while it does not appear correctly in macOS terminal.

**Comment by alex-grover** [comment]
I'm seeing this in the macOS default terminal as well. Maybe the issue should remain open since it does seem to be a valid bug?

**Comment by alex-grover** [comment]
adding some context here for anyone that stumbles on this in the future, it seems like it's an issue with the way that Terminal.app renders colors (colors render differently with the default background color vs if you set one explicitly): https://apple.stackexchange.com/questions/282911/prevent-mac-terminal-brightening-font-color-with-no-background/446604

Not sure if there's an easy way to configure an explicit bg color (for example, black) for all of tide, but i've just stuck to using a different terminal emulator for now
