### ISSUE TITLE
How do the multiline prompts work?

### ISSUE THREAD

**Issue by mainrs** [IlanCosman/tide#243]
I am currently thinking about writing fish compatibility for a tool of mine and was wondering how the multiline rendering works. Would you mind giving me an overview on how you accomplished it?

On a side note, since you have a lot of fish knowledge: Is it possible to conditionally change the prompt like powerlevel10k does? For example it only shows some modules if the user is using a command that is tight to it. If you type `kubectl`, powerlevel10k notices it and displays a module to the right showing context information about kubernetes. It doesn't print it on a newline, it modifies the currently displayed prompt instead.

**Comment by IlanCosman** [comment]
> Would you mind giving me an overview on how you accomplished it?

Sure. I assume you mean right-prompt multiline, as Fish supports left-prompt multiline out of the box.
Basically we just fake having a multiline right prompt. We actually have a left prompt that has some stuff, then prints a bunch of spaces (or other characters), and then prints the right prompt. So the left prompt actually looks like:
`~/src main ?1  ----------------------------------------------------------------------------------------------- right-prompt
❯`
And then the second line of the right prompt is rendered by `fish_right_prompt`.

> Is it possible to conditionally change the prompt like powerlevel10k does?

Generally, yes, that is possible. `commandline -f repaint` re-runs the prompt in place. However, the specific example you mentioned is not. That specific example is #90.

**Comment by mainrs** [comment]
Thank you very much!
