### ISSUE TITLE
Using `set --global` for `tide_character_color` does not work

### ISSUE THREAD

**Issue by TastyPi** [IlanCosman/tide#247]
#### Describe the bug

in [the wiki](https://github.com/IlanCosman/tide/wiki/Configuration) it says "Modify variables using `set --universal` from the command line or `set --global` in your config.fish file". I tried adding `set --global tide_character_color magenta` in my `~/.config/fish/config.fish` but it doesn't change the prompt character's color. It is set correctly, i.e. `echo $tide_character_color` does output magenta, but the prompt color stays the default terminal text color (or whatever has been set in `fish_variables`, e.g. the default green).

#### Steps to reproduce

1. Add `set --global tide_character_color magenta` in config.fish
2. See that the prompt does not change color

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-kitty
os: Arch Linux
terminal emulator: Kitty
fish startup: 5.52 millis
fisher plugins: TeFiLeDo/fish-autoupdate-plugin, jorgebucaran/autopair.fish, gazorby/fish-abbreviation-tips, IlanCosman/tide
```

#### Additional context

It's not a big deal if this is not expected to work, but in that case the wiki should be updated.

**Comment by IlanCosman** [comment]
You're using `main`, which is a development branch and currently has that bug. You should instead install from the release branch like so: `fisher install ilancosman/tide@v5`.

**Comment by aral** [comment]
I’m currently experiencing this same issue (with `tide_os_icon`) in tide version 5.2.2. OK to reopen?
