### ISSUE TITLE
Only replace $HOME at beginning of $PWD

### ISSUE THREAD

**Issue by eoli3n** [IlanCosman/tide#250]
https://github.com/IlanCosman/tide#current-directory-that-just-works

??

```bash
/usr~                                                                                                               
❯ cd dotfiles

/usr~                                                                                                               
❯ [enter]

/usr~/dotfiles master                                                                                               
❯ 
```

**Comment by IlanCosman** [comment]
Not my most brilliant line of code 😅

**Comment by eoli3n** [comment]
The other problem is the fact that the "current-directory" is not updated, unless I return a newline.

**Comment by IlanCosman** [comment]
That is a problem, yah. Probably something with BSD, because I haven't gotten reports of this happening on Mac or Linux. I'll spin up a VM later and take a look 👍

**Comment by IlanCosman** [comment]
@eoli3n I did some testing and it seems the problem should go away with Fish 3.4, which should release sometime soon 👍

**Comment by IlanCosman** [comment]
Wait no, sorry, I was wrong 😞 The bug still appears.
