### ISSUE TITLE
Tide theme is lost after terminal restart

### ISSUE THREAD

**Issue by DestinyofYeet** [IlanCosman/tide#251]
As stated in the title, the theme is lost after opening a new terminal window. The configuration is being kept, it just isn't being applied.

Bug-report:

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: Arch Linux
terminal emulator: Konsole
```

**Comment by IlanCosman** [comment]
How are you setting the variables?

**Comment by DestinyofYeet** [comment]
If you mean custom variables, this is the way I have them in my config.fish

(at the very bottom)
![image](https://user-images.githubusercontent.com/57575330/152650687-9a43c44e-7f10-42cb-8d52-153cbdaa4184.png)

**Comment by SweepingBishops** [comment]
He probably meant the tide variables.
For eg the $tide_left_prompt_items.

**Comment by IlanCosman** [comment]
Yah, I meant tide variables. How are you setting the config? What do you mean by 
> The configuration is being kept, it just isn't being applied.

**Comment by DestinyofYeet** [comment]
> He probably meant the tide variables. For eg the $tide_left_prompt_items.

Ah, I didn't set any of those. I just followed the installation instructions and ran `fisher install IlanCosman/tide@v5`.



> Yah, I meant tide variables. How are you setting the config? What do you mean by
> 
> > The configuration is being kept, it just isn't being applied.

After opening a new console window, the theme isn't there. After running `fisher install IlanCosman/tide@v5`again, it's back with my custom configuration as in the first window.

**Comment by SweepingBishops** [comment]
So what is the prompt actually shown in the new window?
>After opening a new console window, the theme isn't there. After running fisher install IlanCosman/tide@v5again, it's back with my custom configuration as in the first window.

Do you have to configure it again?

**Comment by DestinyofYeet** [comment]
> So what is the prompt actually shown in the new window?
> 
> > After opening a new console window, the theme isn't there. After running fisher install IlanCosman/tide@v5again, it's back with my custom configuration as in the first window.
> 
> Do you have to configure it again?

This is the default prompt shown
![image](https://user-images.githubusercontent.com/57575330/152650896-115b5d9c-478f-4187-bffe-b721d86f1628.png)

Just reconfiguring doesn't apply it, I have to run the fisher install command again to get it

**Comment by IlanCosman** [comment]
Okay, so you have something that is overriding Tide's `fish_prompt` command. Either in your `config.fish`, or maybe you have oh-my-fish installed?

**Comment by DestinyofYeet** [comment]
As long as garuda Linux doesn't come with oh-my-fish, I shouldn't have it. Is there a way to tell if it's installed?

**Comment by IlanCosman** [comment]
In the new shell, the one where Tide isn't show, run `functions --details fish_prompt`. That will show you where the function is defined.

**Comment by DestinyofYeet** [comment]
![image](https://user-images.githubusercontent.com/57575330/152651099-9c3ba82d-d836-4099-94b8-c7857773952f.png)
hmmm....

**Comment by SweepingBishops** [comment]
Do you have a ~/.config/fish/functions/fish_prompt.fish file?

**Comment by IlanCosman** [comment]
I seem to recall that garuda uses starship by default. Do you see anything about starship in your `config.fish`?

**Comment by DestinyofYeet** [comment]
> 

yes
![image](https://user-images.githubusercontent.com/57575330/152651254-e46bffea-17c1-46d5-aaab-5fd246e9fa40.png)


> I seem to recall that garuda uses starship by default. Do you see anything about starship in your `config.fish` or `conf.d` files?

Ah, yes, found it 
![image](https://user-images.githubusercontent.com/57575330/152651411-91134235-584b-4339-8283-39410798ff2d.png)

**Comment by DestinyofYeet** [comment]
Should I comment it out?

**Comment by SweepingBishops** [comment]
Comment it out and see if it works.

**Comment by DestinyofYeet** [comment]
Yup worked, thanks a bunch!
