### ISSUE TITLE
Allow `pwd` in right prompt

### ISSUE THREAD

**Issue by dermetfan** [IlanCosman/tide#253]
#### Describe the bug

I have the `pwd` item in the right prompt. After updating to v5 it disappeared.

#### Steps to reproduce

```fish
set -U tide_right_prompt_items pwd # …
```

#### Screenshots

v4.3.4:

![2022-02-20T20:21:17,061611876+01:00](https://user-images.githubusercontent.com/4956158/154860415-598b2b72-22f4-4745-a17f-b33e3f7bc084.png)

v5.0.0 and v5.0.1:

![2022-02-20T20:23:30,515716949+01:00](https://user-images.githubusercontent.com/4956158/154860425-eeb93ac0-5191-4459-ad1e-a90356afbebf.png)

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: alacritty
os: NixOS 21.11
terminal emulator: Alacritty
```

#### Additional context

This could be related to #199.

**Comment by IlanCosman** [comment]
Yah PWD doesn't work in the right prompt at the moment. Not really a bug, as it wasn't unintentional, but rather not implemented.

**Comment by IlanCosman** [comment]
I don't really want to implement this, sorry 😞
It's more code/stuff to maintain, and no prompt I've ever seen has the pwd in the right prompt (at least no popular one).
