### ISSUE TITLE
Prompt does not take full screen width

### ISSUE THREAD

**Issue by napsa-4805** [IlanCosman/tide#254]
Hi, there. I think Tide is awesome. One little jarring effect.

When I open a new terminal, prompt does not occupy full screen width. This can look unpleasant when I have split terminals.

![image](https://user-images.githubusercontent.com/58021950/154904777-c9607df3-b7bb-401e-b7d6-7c1f3f9c7846.png)

![image](https://user-images.githubusercontent.com/58021950/154902025-7ba58cd3-5181-4240-8606-8f02ec264448.png)

I have to press enter or clear the screen to get the prompt to fill the width

![image](https://user-images.githubusercontent.com/58021950/154902136-78074a47-71c0-4ac7-957e-b12c25343b4d.png)

**Comment by willowia** [comment]
I'm also curious if anything can be done about this.

**Comment by IlanCosman** [comment]
Yah, actually super easy to fix 😄

**Comment by napsa-4805** [comment]
> Yah, actually super easy to fix smile

Good to know. Looking forward to the fix.
