### ISSUE TITLE
tide doesn't start when i start a new terminal

### ISSUE THREAD

**Issue by abdelmounim-dev** [IlanCosman/tide#256]
#### Describe the bug

I just installed tide, it looks great but whenever I start a new terminal it just shows the default fish shell, not the tide interface
#### Steps to reproduce
I installed it using fisher
configured it and it looks fine in the current terminal
opened a new terminal and it just shows default fish

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: garuda dragonized
terminal emulator: alacritty
```

**Comment by SweepingBishops** [comment]
https://github.com/IlanCosman/tide/issues/251#issuecomment-1030661829
I think it is the same issue.
Garuda overrides the tide prompt in config.fish

**Comment by abdelmounim-dev** [comment]
oh yeah,  my bad I didn't look at all the issues, should i delete this?

**Comment by SweepingBishops** [comment]
Nah, just mark it as solved.
