### ISSUE TITLE
Add git symbols and meaning to docs

### ISSUE THREAD

**Issue by wdfinch** [IlanCosman/tide#258]
#### Is your feature request related to a problem? Please describe

I just installed the tide prompt and love it. However, I don't know what the git symbols all mean and can't find any details in the docs. I tried looking for information on the [fish_git_prompt](https://fishshell.com/docs/current/cmds/fish_git_prompt.html) page but it looks like it doesn't translate over perfectly to this. 

#### Describe the solution you'd like

A table in the docs with each symbol and what it means (and maybe how to configure it differently as a third column).

#### Additional context

If this information is available somewhere else, then maybe just a link to that site would be fine.

**Comment by IlanCosman** [comment]
Yah, there should be something in the docs about this 👍

**Comment by wdfinch** [comment]
Thanks!

**Comment by IlanCosman** [comment]
[Done](https://github.com/IlanCosman/tide/wiki/What-do-the-git-icons-mean%3F)!

**Comment by wdfinch** [comment]
Awesome this is perfect. Thanks for adding this so quickly.
