### ISSUE TITLE
Path abbreviation support

### ISSUE THREAD

**Issue by DeeparthGupta** [IlanCosman/tide#260]
Tide doesn't seem to currently support the variable `fish_prompt_pwd_dir_length` because changing it does not abbreviate the tide prompt even though `prompt_pwd` shows the expected abbreviation. There seems to be no other way to do it either. I'd like this because prompts tend to get very large even without icons.

**Comment by IlanCosman** [comment]
That's correct, Tide does not respond to the `fish_prompt_pwd_dir_length` variable.

Tide does more intelligent shortening than `prompt_pwd`. If you're using a one-line prompt, you can use the `tide_prompt_min_cols` variable to tell Tide to give you more space. If you're using a two-line prompt, the pwd length shouldn't ever become a problem.
