### ISSUE TITLE
"in function 'fish_prompt' in command substitution disown: THERE ARE NO SUITABLE JOBS" Idk what that means! help!

### ISSUE THREAD

**Issue by mark-escosura** [IlanCosman/tide#261]
#### Describe the bug

Issue: I changed the path from /usr/local/bin/fish to /opt/homebrew/bin/fish after doing the which fish command and getting this error. Please help!

#### Screenshots

![Screen Shot 2022-03-08 at 9 16 28 PM](https://user-images.githubusercontent.com/88951042/157377657-41f5baef-6146-47e8-9e56-9e535f3632c5.png) 

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.3.1
tide version: 5.0.1
term: xterm-256color
os: macOS 12.2.1
terminal emulator: Terminal built-in MacOS

```

**Comment by IlanCosman** [comment]
It seems like you installed from the dev branch (`ilancosman/tide`) instead of from the release branch (`ilancosman/tide@v5`). Or did you use the manual installation? Either way, you should reinstall from the release branch and I think that should fix your problems.

**Comment by IlanCosman** [comment]
oh yah and you also need to have `fish` in your path. i.e running `fish` from the command line needs to work

**Comment by line-o** [comment]
```
fish version: 3.4.0
tide version: 5.0.1
term: xterm-256color
os: osx monterey 12.3
terminal emulator: iTerm2
```

**Comment by line-o** [comment]
`fish_add_path /opt/homebrew/bin` fixed it for me instantly
