### ISSUE TITLE
Spaces around character_icon  doesn't seem alright

### ISSUE THREAD

**Issue by buraksirma** [IlanCosman/tide#263]
#### Describe the bug

It looks like 2 spaces after character_icon and 0 space before. You can see the screenshots below.

#### Steps to reproduce

I've switched from zsh and was using PowerLevel10k so I thought its great to have same functionality in fish too.

Everything was fresh installation.

1-)Install fish & fisher & tide
2-)tide configure and 1-1-2-1-1-2-y

#### Screenshots

![image](https://user-images.githubusercontent.com/32032205/158033446-bbbc081f-f361-4524-91fa-7922f3f9522f.png)
![image](https://user-images.githubusercontent.com/32032205/158033475-73ce558f-717a-4a8a-86bb-f5af1a5710a3.png)

#### Environment

![image](https://user-images.githubusercontent.com/32032205/158033576-5b0675d0-9476-4931-85dc-021b6b966abe.png)

fish version: 3.4.0
tide version: 5.0.1
term: xterm-kitty
os: macOs Monterey 12.2.1
terminal emulator: Kitty
fish startup: 17.20 millis
fisher plugins: jorgebucaran/fisher, ilancosman/tide, jorgebucaran/nvm.fish, reitzig/sdkman-for-fish@v1.4.0, PatrickF1/fzf.fish, jorgebucaran/autopair.fish

**Comment by IlanCosman** [comment]
You're installing from the dev branch (`ilancosman/tide`), instead of the release branch (`ilancosman/tide@v5`) 👍
