### ISSUE TITLE
Can't run `tide configure` without having `clear` installed.

### ISSUE THREAD

**Issue by Bost** [IlanCosman/tide#265]
The `clear` command used by:
- `_tide_title` function from`fish/functions/_tide_sub_configure.fish`
- `finish` function from `fish/functions/tide/configure/choices/all/finish.fish`

may not be installed not some systems (e.g. Guix OS). The command is not necessary. If you comment it out the `tide configure` runs just fine.

Please consider removing it. Thx.

PS: and for the guix users: run `guix install ncurses` to get the `clear` installed.

**Comment by IlanCosman** [comment]
Fair enough. I added a check before using it to make sure it is installed.

**Comment by Bost** [comment]
Thx.
