### ISSUE TITLE
Last item on right prompt clipped/no padding

### ISSUE THREAD

**Issue by GladOSkar** [IlanCosman/tide#266]
#### Describe the bug

I just updated tide and my config. Everything is now working as before, except for the end of the right prompt, where the item seems cut off, see screenshots

#### Steps to reproduce

1. Set right prompt
3. See following screenshots

#### Screenshots

Before, the last item would have at least one space of padding on the right and reaching the end of the terminal window.

Now it looks clipped and doesn't reach the end of the terminal window:
![image](https://user-images.githubusercontent.com/9497832/158565369-fe75b97f-ac64-4dca-a346-96290803dca6.png)
![image](https://user-images.githubusercontent.com/9497832/158565802-29acb3fa-f7a1-4625-b2de-21c48536f0c0.png)

#### Environment

Output of `tide bug-report`:

```
fish version: 3.4.0
tide version: 5.0.1
term: xterm-256color
os: Solus 4.3
terminal emulator: Wezterm
fish startup: 52.61 millis
fisher plugins: jorgebucaran/fisher, jethrokuan/z, PatrickF1/fzf.fish, IlanCosman/tide
```

**Comment by IlanCosman** [comment]
You're installing from the dev branch (ilancosman/tide), instead of the release branch (ilancosman/tide@v5) 👍

**Comment by IlanCosman** [comment]
Don't know what the problem might be then, sorry 😞 Can't reproduce. We can leave this open for a bit.

**Comment by GladOSkar** [comment]
Just messed around with it a bit. The same thing happens in `alacritty`, `kitty` and `wezterm`.

But if i use `COLUMNS=(math $COLUMNS - 1)` in `fish_prompt.fish`, the item is not truncated anymore, but the last column is entirely unused instead:

![image](https://user-images.githubusercontent.com/9497832/158902511-870a9f17-625a-4e58-957e-937ade6e1bdb.png)

So this seems to be an issue with the last column not being usable.

However, trying something like this to print a background color **does** work:

![image](https://user-images.githubusercontent.com/9497832/158903182-ef753871-2950-4057-b5da-3996159c672f.png)

So i don't really know what's going on there either...

**Comment by IlanCosman** [comment]
Can you try installing from the `run-pwd-in-main-shell` branch? (that's the upcoming release).

**Comment by GladOSkar** [comment]
Yes that does fix it!

![image](https://user-images.githubusercontent.com/9497832/158905292-22d899aa-f1f6-4871-890b-4c1c919b4ebf.png)

Now i just have to figure out how to get the triangle back on my custom item :D

**Comment by IlanCosman** [comment]
Hmm, unfortunately it doesn't seem like that's possible anymore. I borked it, not sure whether that was by accident or not 😅

**Comment by GladOSkar** [comment]
Just found it. PR incoming

**Comment by otommod** [comment]
Unfortunately, this is still present.

![exhibit1](https://user-images.githubusercontent.com/2249516/173114884-855232b4-c8b9-4aa0-8a1b-81e4d9680bdc.png)

![exhibit2](https://user-images.githubusercontent.com/2249516/173114888-0be316e1-ff08-4cab-8016-f8212a3374c1.png)

**Comment by IlanCosman** [comment]
@otommod Could you file a new bug report? A bunch of stuff has changed since this report.
