### ISSUE TITLE
Prompt does not show

### ISSUE THREAD

**Issue by TheAifam5** [IlanCosman/tide#267]
#### Describe the bug

The prompt is not visible after fish update.

#### Steps to reproduce

1. Install tilde@v5.0.1
2. Run fish
3. See error :)

#### Screenshots

Upon fish start, shows only this message:
```
fish: Unknown command: fish_right_prompt
fish: 
    fish_right_prompt | read -z prompt
    ^


```

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.4.0
tide version: 5.0.1
term: xterm-kitty
os: Gentoo
terminal emulator: Kitty
```

**Comment by IlanCosman** [comment]
Something else is interfering with tide. Perhaps it's Kitty shell integration or something else. I'd suggest searching for `fish_right_prompt | read -z prompt` in your `~/.config/fish/`.

**Comment by TheAifam5** [comment]
`type fish_right_prompt` points me to
```
# Defined interactively
function fish_right_prompt
    set -l func fish_right_prompt
            test -e $__async_prompt_tmpdir'/'$fish_pid'_'$func
            and cat $__async_prompt_tmpdir'/'$fish_pid'_'$func
        
end
```

so it likely to be a fish async prompt plugin.

Will close this issue, I am sorry for making a trouble, still learning fish.
