### ISSUE TITLE
prompt head not shown correctly

### ISSUE THREAD

**Issue by hmei3** [IlanCosman/tide#269]
somehow the prompt separator and head aren't displayed correctly.
<img width="563" alt="Screen Shot 2022-03-21 at 8 53 08 PM" src="https://user-images.githubusercontent.com/32881956/159391522-5170619d-011a-4839-960a-d4805378b20d.png">

fisher, version 4.3.1
IlanCosman/tide@v5

**Comment by IlanCosman** [comment]
Please fill out a bug report. You probably don't have the correct font set in your terminal.

**Comment by hmei3** [comment]
Thank you, I changed the font to sauceCodePro Nerd Font and it works now.
