### ISSUE TITLE
Can't seem to get the hostname to show and other segments.

### ISSUE THREAD

**Issue by bjagasia** [IlanCosman/tide#270]
Hi all,

I've been trying to configure my Fish Shell to reflect a similar setup I have for my oh-my-posh shell (photo attached). I'm running Windows Terminal and the latest Ubuntu shell via WSL2.

![image](https://user-images.githubusercontent.com/73490434/159609995-db3c141c-da46-4c6b-94e8-030d83f884b7.png)

However, I've been trying to add weather and hostname to the prompts but they do not seem to be showing up. I've tried the following:

`set -p tide_right_prompt_items context`
`set --universal tide_right_prompt_items context`

and I decided to try the example too `set --universal tide_left_prompt_items context $tide_left_prompt_items` but neither worked. Could someone provide some guidance on how to go about adding the hostname/date/weather etc.? that would be awesome!

Thank you.

**Comment by IlanCosman** [comment]
You probably need to set the `tide_context_always_display` variable.

**Comment by IlanCosman** [comment]
Context was probably not the best example to give 😅 I'll change that.

**Comment by IlanCosman** [comment]
You'll have to create a custom item for weather, no such thing is bundled with tide (though I'd happily accept a PR 😄)

**Comment by bjagasia** [comment]
> You probably need to set the `tide_context_always_display` variable. https://github.com/IlanCosman/tide/wiki/Configuration#context

Ah-ha!!!! Thank you. That did it. :) -- In regards to changing the time format to include just the `date` as another item on the prompt -- is that possible? I looked through the code and I believe I noticed only being able to change the date from 12 hour format and 24 hour format. I'd like another item after the time showing the date in YYYY-MM-DD format.

Much appreciated !

**Comment by IlanCosman** [comment]
No, there's no way to style two instances of the `time` item differently. They both use the same variables. If you really want two, separate items on the cli, then you should create a custom item for one of the two. 

> only being able to change the date from 12 hour format and 24 hour format

However, this is not true. The `time` item accepts a format string, which just gets passed along to the unix `date` command. So, if you're ok with not having it be two, separate looking items, you would set `tide_time_format` to something like `"%T %F"`.

**Comment by bjagasia** [comment]
Thank you @IlanCosman !
