### ISSUE TITLE
java item produces unwanted output "Unrecognized option: --version"

### ISSUE THREAD

**Issue by line-o** [IlanCosman/tide#271]
#### Describe the bug

Since it is the very first time I post something here let me first thank you for that awesome prompt.
After recently updating to tide@5.1 something unexpected happened whenever I opened a directory with a maven project in it.

![Screenshot 2022-04-01 at 21 53 06](https://user-images.githubusercontent.com/657222/161332458-041a963f-93b4-49db-8186-8aae145c8b4e.png)

After a lot of poking around I finally found https://github.com/IlanCosman/tide/pull/244
and it all started to make sense.

```fish
function _tide_item_java
    test -e pom.xml && _tide_print_item java $tide_java_icon' ' (java --version | string split ' ')[2]
end
```

Does not in my case as I am still working with java8 which, unfortunately, does not support the sane version of a long argument.

I then tried the easy route and shortened it to just `-version` which should be supported also by the later versions of java.

```fish
function _tide_item_java
    test -e pom.xml && _tide_print_item java $tide_java_icon' ' (java -version | string split ' ')[2]
end
```

But this only led to a different output _after_ my prompt

![Screenshot 2022-04-01 at 21 57 50](https://user-images.githubusercontent.com/657222/161333046-540be8b5-3cf7-4a5d-9dbf-80010521cc84.png)

The version from the original PR, before it got simplified, nicely outputs what I would expect

![Screenshot 2022-04-01 at 22 01 13](https://user-images.githubusercontent.com/657222/161333393-dd7cb957-f76e-43a6-8d40-748ccd2d2514.png)

Here it is for anyone having the same issue:

```fish
function _tide_item_java
    test -e pom.xml && _tide_print_item java $tide_java_icon' ' (set jv (java -version 2>&1 | head -1 | string split ' ')[3]; echo $jv | string trim -c '"')
end
```

#### Steps to reproduce

1. select java8 as your current Java version
2.  open a directory with a pom-file
3. See error message output after the prompt

#### Screenshots

see above

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.4.1
tide version: 5.1.0
term: xterm-256color
os: macOS 12.3.1
terminal emulator: iterm2 Build 3.4.15
fish startup: 6.41 millis
fisher plugins: IlanCosman/tide@v5 jethrokuan/z jorgebucaran/nvm.fish PatrickF1/fzf.fish jhillyerd/plugin-git
```

**Comment by line-o** [comment]
I would be grateful if there is a way to still support java8, I know it is old but if all that it takes is to use the original version of the function maybe it is OK to have it.

**Comment by line-o** [comment]
Or, maybe there is a cheap way to fall back to java 8 support when `--version` does not work.

**Comment by line-o** [comment]
Side question: how would I override the default function in order to keep my workaround over future upgrades?

**Comment by IlanCosman** [comment]
Haha, this is beyond inconsistent.

1. Different flags (`-version` vs `--version`)
2. Different format (`openjdk version "1.8.0_332"` vs `openjdk 17.0.1 2021-10-19`)
3. Different output stream (stderr vs stdout)

I should be able to make this backwards compatible though, without any ugly code 😄 Thanks for the heads up.
