### ISSUE TITLE
Save configuration to file instead of fish variables.

### ISSUE THREAD

**Issue by bageljrkhanofemus** [IlanCosman/tide#272]
I want to track my tide configuration in a config file, which I can use a dotfile manager to synchronize. Currently, you can configure it from the command line tool, which saves to fish variables, or configure it via environment variables. 
Is there a way to run tide-config and have it save to some file (besides fish variables, which cannot be synchronized)? Ideally, it could support a toml file similar to starship.

**Comment by IlanCosman** [comment]
An official Tide config file is not currently something I'm interested in implementing.

You can read my recommendations for dotfile management here: #37

---

tldr: 

Manually go through the configuartion wizard (it takes like 30 seconds at most), and then have an install script in your dotfiles to change the few variables you actually want to change. That's the most flexible and future-proof way of doing things.
