### ISSUE TITLE
Two spaces between icon and command line after the last update tide

### ISSUE THREAD

**Issue by Zesko** [IlanCosman/tide#274]
#### Describe the bug

fish 3.4.1

Before the last update tide 5.1.1:
```
❯ tide --version
```

After the last update 5.1.1:
```
❯   tide --version
```

It looks like that two spaces between "❯" and command line, before there was only one space. I do not know if it is bug?

#### Steps to reproduce

No error, but why is number of space between "❯" and command line changed after the last update tide 5.1.1

#### Environment

Output of `tide bug-report`: 

```
❯  tide bug-report
fish version: 3.4.1
tide version: 5.1.1
term: xterm-256color
os: Manjaro KDE, Manjaro GNOME
terminal emulator: all
fish startup: 15.29 millis
fisher plugins: halostatue/fish-docker IlanCosman/tide@v5

```

**Comment by IlanCosman** [comment]
Can you paste the output of `string escape $tide_character_icon`?

**Comment by Zesko** [comment]
> Can you paste the output of string escape $tide_character_icon?
```
❯
```

**Comment by Zesko** [comment]
Only lean with one line has the problem.

**Comment by IlanCosman** [comment]
Hmm yah, I guess some code change messed that up 😄 You can fix this by setting `tide_left_prompt_suffix` to empty 👍

**Comment by Zesko** [comment]
It looks good.
