### ISSUE TITLE
"`$(...)` is not supported in fish" error

### ISSUE THREAD

**Issue by alphashuro** [IlanCosman/tide#276]
https://github.com/IlanCosman/tide/blob/eb4ab530dabf1d4e959be8e287d6c4ef8413dcf0/functions/_tide_item_git.fish#L45

I get an error when trying to install tide via `fisher install` on `arch` saying this line is not supported in fish, and suggesting that it should be `(...)` instead. Is the use of `$(...)` intended here? if so, what should I be doing differently to make this work?

**Comment by IlanCosman** [comment]
Your version of fish is too old.
