### ISSUE TITLE
why my little chameleon don't show up in prompt

### ISSUE THREAD

**Issue by mess-maker** [IlanCosman/tide#277]
I've updated Tide to the las version 5.2 and the OS logo don't show up on prompt, I'stuck with the default penguin

is there something to modify somewhere to enable this feature ?
![tide](https://user-images.githubusercontent.com/59267770/162613009-159d467a-c8c2-4fe1-b096-74b0419371a3.jpg)

**Comment by IlanCosman** [comment]
Try going through the configuration wizard again.

**Comment by mess-maker** [comment]
was done before reporting here
with no change :/
I'm on fish 3.4.1

**Comment by IlanCosman** [comment]
Could you paste your /etc/os-release in here please :)

**Comment by mess-maker** [comment]
it was in the screenshot above

```
bat /etc/os-release

   1   │ NAME="openSUSE Tumbleweed"
   2   │ # VERSION="20220408"
   3   │ ID="opensuse-tumbleweed"
   4   │ ID_LIKE="opensuse suse"
   5   │ VERSION_ID="20220408"
   6   │ PRETTY_NAME="openSUSE Tumbleweed"
   7   │ ANSI_COLOR="0;32"
   8   │ CPE_NAME="cpe:/o:opensuse:tumbleweed:20220408"
   9   │ BUG_REPORT_URL="https://bugs.opensuse.org"
  10   │ HOME_URL="https://www.opensuse.org/"
  11   │ DOCUMENTATION_URL="https://en.opensuse.org/Portal:Tumbleweed"
  12   │ LOGO="distributor-logo-Tumbleweed"
```

**Comment by tlusk** [comment]
@IlanCosman the fix only works for opensuse tumbleweed, not opensuse leap

```NAME="openSUSE Leap"
VERSION="15.4 Beta"
ID="opensuse-leap"
ID_LIKE="suse opensuse"
VERSION_ID="15.4"
PRETTY_NAME="openSUSE Leap 15.4 Beta"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:15.4"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
DOCUMENTATION_URL="https://en.opensuse.org/Portal:Leap"
LOGO="distributor-logo-Leap"
```

**Comment by IlanCosman** [comment]
Lovely 😄 I guess I could iterate over the ID_LIKE values, or just add "opensuse-leap" and "opensuse-tumbleweed" as their own thing to get it from ID. Fix incoming...
