### ISSUE TITLE
`string join: Unknown option`... when a directory name begins with `-`

### ISSUE THREAD

**Issue by Veraellyunjie** [IlanCosman/tide#278]
#### Describe the bug

Error messages `string join: Unknown option`... when a directory name begins with `-`.

Had tried to resurrect an old issue https://github.com/IlanCosman/tide/issues/88#issuecomment-1095269724 but was sent to open a new bug report.

#### Steps to reproduce
```
cd -- /tmp
mkdir -- -dir
cd -- -dir
```
Errors follow:
```text
string join: Unknown option '-dir'
```
_more output omitted_
#### Environment

Output of `tide bug-report`: 

```text
Your Fish version is out of date.
The latest is 3.4.1. You have 3.3.1.
Please update before submitting a bug report.
```
Can't update as `3.3.1` is the only one available from the repo.
But, in
https://github.com/IlanCosman/tide/blob/main/functions/_tide_pwd.fish
https://github.com/IlanCosman/tide/blob/dev/functions/_tide_pwd.fish
there are
2 `string join -- /`... with `--` and
2 `string join /`... without `--`,
so I presume that old `fish` version may be irrelevant and the issue might be fixed by making all 4 `string join` spelled with `--`, which seems to work on my older version.

**Comment by IlanCosman** [comment]
I can't reproduce 😞 directories with dashes work fine for me. I'm guessing you also have an out of date Tide version. Regardless however, Tide doesn't support old fish versions. https://github.com/IlanCosman/tide/wiki/Fish-version-compatibility
