### ISSUE TITLE
Weird Hex Values in MacOS

### ISSUE THREAD

**Issue by BriianPowell** [IlanCosman/tide#279]
#### Describe the bug

Using the tide theme in macOS Monterey 12.3.1

#### Steps to reproduce

1. Install Fish Shell
2. Install Tide
3. Use universal variables to set the Icon `set -U tide_os_icon (_tide_detect_os)`

#### Screenshots

<img width="597" alt="Screen Shot 2022-04-11 at 5 00 30 PM" src="https://user-images.githubusercontent.com/17599630/162852099-acfe59bc-a110-4604-bdfc-97f202a426ee.png">

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.4.1
tide version: 5.2.1
term: xterm-256color
os: macOS Monterey 12.3.1
terminal emulator: iTerm2
fish startup: 13.73 millis
fisher plugins:
- jorgebucaran/fisher
- IlanCosman/tide@v5
- jorgebucaran/nvm.fish
- rbenv/fish-rbenv
- oh-my-fish/plugin-osx
- dudeofawesome/plugin-node-binpath
- jorgebucaran/autopair.fish
```

#### Additional context

Hasn't been an issue I've noticed on any other operating system (openSUSE, Arch). Only seems to be happening on macOS. I have a configuration file that I use to make sure I use the same tide config for all OS and this is the first time I've ran into an issue like this.

**Comment by IlanCosman** [comment]
Going to close this as a question because there's nothing I want to change here.

**Comment by dudeofawesome** [comment]
For posterity, the new API outputs the OS icon as well as 2 color codes for theming. If you're looking to get just the icon, you could thus use `_tide_detect_os | head -n 1`.
