### ISSUE TITLE
posture correction

### ISSUE THREAD

**Issue by matthiasdebernardini** [IlanCosman/tide#28]
#### Is your feature request related to a problem? Please describe
As I begin to start working, my posture worsens (back slouches and shoulder curl inwards). This is bad for my health and an arguement could be made that its also bad for my focus. 

#### Describe the solution you'd like

I would like my prompt periodically to ask me how my posture is so that I correct it.

#### Additional context

Id like it to be a configuration option for my prompt to help me stay upright

**Comment by IlanCosman** [comment]
That's an _interesting_ request. 😂 I don't disagree with you, a posture reminder could be helpful, but I think that's outside the scope of this project.

However, you can use a really simple fish script to remind you about your posture:

```fish
function posture
    sleep 60
    echo "How's your posture doing?"
end
```

Then in your terminal:
```console
fish -c 'while true; posture; end' &
```

I'm going to label this as `wontfix` as close the issue, but I appreciate you opening it. Thanks for the suggestion 😄
