### ISSUE TITLE
Error after installing tide with fisher

### ISSUE THREAD

**Issue by a200411044** [IlanCosman/tide#280]
the configure prompt is fine, but once done and reload ubuntu i went into this error
currently using Ubuntu on WSL2

~/.config/fish/functions/_tide_item_pwd.fish (line 1): array indices start at 1, not 0.
string join -- '/' $splitPwd[1..$i] | string replace '~' $HOME
                                 ^
in command substitution
        called on line 18 of file ~/.config/fish/functions/_tide_item_pwd.fish
in function '_tide_item_pwd'
        called on line 1 of file ~/.config/fish/functions/_tide_left_prompt.fish
in command substitution
        called on line 11 of file ~/.config/fish/functions/_tide_left_prompt.fish
in function '_tide_left_prompt'
        called on line 13 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution
~/.config/fish/functions/_tide_item_pwd.fish (line 18): Unknown error while evaluating command substitution
        set -l parentDir (string join -- '/' $splitPwd[1..$i] | string replace '~' $HOME) # Use i from before increment
                         ^
in function '_tide_item_pwd'
        called on line 1 of file ~/.config/fish/functions/_tide_left_prompt.fish
in command substitution
        called on line 11 of file ~/.config/fish/functions/_tide_left_prompt.fish
in function '_tide_left_prompt'
        called on line 13 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution

**Comment by IlanCosman** [comment]
Could you paste the output of `tide bug-report` here?
