### ISSUE TITLE
Custom fetch script written in Python throwing BrokenPipeError exception after tide install

### ISSUE THREAD

**Issue by fybx** [IlanCosman/tide#282]
I have a [custom fetch script](https://github.com/fybx/scripts/blob/main/fetchpy) written in Python that uses [Rich](https://github.com/Textualize/rich). This script is called by config.fish resulting in printed text on screen. Every time I press enter, BrokenPipeError exception is thrown.

tide seems to cause a BrokenPipeError in my script, which is weird since the script is only called once, successfully prints its content and exits. However every time tide draws fish_prompt the error is raised again.

#### Steps to reproduce

Install tide with fisher
Add line to config.fish to call the custom script
Open a terminal, or if already open press enter

#### Environment
```text
fish version: 3.4.1
tide version: 5.2.2
term: xterm-kitty
os: Arch Linux
terminal emulator: Kitty
fish startup: 121.21 millis
fisher plugins: jorgebucaran/fisher IlanCosman/tide@v5
```

**Comment by fybx** [comment]
Moving the call to script into `if status is-interactive` block in config.fish magically solved my issue.

**Comment by IlanCosman** [comment]
Nothing magical about it 😄 Tide creates background Fish process for async processing. You should guard anything you only want to run in interactive shells.

```fish
if status is-interactive
    # interactive shell stuff
end
```
