### ISSUE TITLE
How do I bind default bash shortcut keys for text navigation in cli?

### ISSUE THREAD

**Issue by mateobencek** [IlanCosman/tide#284]
I know shortcuts work with default fish installation, but after I installed the theme they do not anymore.
By default text navigation shortcuts I mean for example:
- ctrl+a to go to the beginning of the line
- ctrl+e for the end
- and similar...

I am not able to find documentation on how to bind it.
Thanks in advance.

**Comment by IlanCosman** [comment]
Tide shouldn't have any impact on your key bindings. Something else is wrong with your Fish config, sorry.

**Comment by MrHighTech** [comment]
Well, it might be the default configuration. Because my fish configuration is quite short and it does not include any key bindings. And shortcuts work when I disable Tide

**Comment by IlanCosman** [comment]
Try `tide bug-report --clean`. You'll find that the bindings work there (or I really damn hope they should), which proves that it's not Tide messing things up 😄

**Comment by IlanCosman** [comment]
No. That command creates a perfectly clean fish instance with no customization at all, and then installs Tide. Thus demonstrating that Tide does not mess up the default bindings.

Are you absolutely, 100% sure that your bindings were working just fine, then you installed tide, and then your bindings didn't work? Can you repeat that occurrence? If so, I'd really appreciate a video or something like that.

**Comment by MrHighTech** [comment]
Alright, I will look try to reproduce it when I get the time. For know I at least know where is the problem. Thanks a lot.

**Comment by MrHighTech** [comment]
The problem is that there are multiple modes where you can bind the key. There are 6 modes when I list them:
- default
- insert
- paste
- replace
- replace_one
- visual
The problem is that the default one is not actually "default" for some reason. The default mode is "insert". When I bind the key I want for that mode it works. I haven't investigated how are modes created and why. Can you elaborate on that more?

**Comment by IlanCosman** [comment]
> Can you elaborate on that more?

You are in vi mode. https://fishshell.com/docs/current/interactive.html?highlight=vi#vi-mode-commands
