### ISSUE TITLE
Display “canonical” casing of CWD on macOS

### ISSUE THREAD

**Issue by lydell** [IlanCosman/tide#285]
#### Steps to reproduce

1. Use macOS, which by default has a case <strong>in</strong>sensitive file system.
2. `mkdir CAPITAL`
3. `cd capital` (I write in lowercase because I’m lazy, or can’t remember the casing)

Result: The prompt shows for example `~/stuff/capital` as CWD.

Expected: The prompt shows for example `~/stuff/CAPITAL` as CWD.

#### Screenshots

![image](https://user-images.githubusercontent.com/2142817/164503179-fae222df-3ce2-43ed-a473-13fc698203c4.png)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.4.1
tide version: 5.2.2
term: xterm-256color
os: macOS Monterey 12.3.1
terminal emulator: iTerm2
fish startup: 21.23 millis
fisher plugins: jorgebucaran/fisher IlanCosman/tide@v5
```

#### Additional context

`realpath .` seems to print the “canonical” casing. However, I don’t remember if `realpath` comes with macOS or if it comes from something I’ve installed with `brew`.

**Comment by IlanCosman** [comment]
This is a fish thing.
```console
ilan@Ilans-Air ~> rm -rf CAPITAL
ilan@Ilans-Air ~> mkdir CAPITAL
ilan@Ilans-Air ~> cd capital
ilan@Ilans-Air ~/capital> echo $PWD
/Users/ilan/capital
ilan@Ilans-Air ~/capital> realpath .
/Users/ilan/CAPITAL
```
Tide uses `$PWD` so Tide inherits this "bug" if you want to call it that. `$PWD` seems to change based on your `cd`.

```console
ilan@Ilans-Air ~> rm -rf CAPITAL
ilan@Ilans-Air ~> mkdir CAPITAL
ilan@Ilans-Air ~> cd capital
ilan@Ilans-Air ~/capital> echo $PWD
/Users/ilan/capital
ilan@Ilans-Air ~/capital> ..
ilan@Ilans-Air ~> cd CAPITAL
ilan@Ilans-Air ~/CAPITAL> echo $PWD
/Users/ilan/CAPITAL
```
You can open a fish bug if you'd like 🙂

**Comment by lydell** [comment]
Sorry, I should have checked plain fish without tide first! 😊
