### ISSUE TITLE
Show Android logo inside Termux

### ISSUE THREAD

**Issue by jose1711** [IlanCosman/tide#286]
#### Is your feature request related to a problem? Please describe

Currently `tide` displays generic Linux icon when running on a Termux system.

#### Describe the solution you'd like

It would be great if `tide` uses Android logo instead as it is included in recommended fonts.

#### Additional context

I made the following modification in `_tide_detect_os.fish` and it seems to be working for me:
```
..
case linux
  begin; uname -o | string match -eq Android && printf %s\n  FFFFFF A4C639; end ||
  _tide_detect_os_linux_cases /etc/os-release ID ||
  ..
```
Update prompt looks like this:
![obrázok](https://user-images.githubusercontent.com/1406222/164558589-16717bed-96a5-4b23-a648-b8916eb7b831.png)

**Comment by IlanCosman** [comment]
Yah sure. Could you submit a pull request? 🙂
