### ISSUE TITLE
https://github.com/IlanCosman/tide#extensible is showing outdated information (background color setting)

### ISSUE THREAD

**Issue by jose1711** [IlanCosman/tide#287]
#### Describe the bug

The example at https://github.com/IlanCosman/tide#extensible shows how user sets background color for custom item. As of `tide` version 5 this no longer works (and if a specific bg color is requested in must be set in the function itself). The steps are still valid for version 4.1.1 for instance.

#### Steps to reproduce

1. Follow steps at https://github.com/IlanCosman/tide#extensible with most recent version of `tide` installed
2. Get different results

Somewhat related to https://github.com/IlanCosman/tide/issues/83.

**Comment by IlanCosman** [comment]
Yah.., a bunch of the images are very outdated 😓

**Comment by IlanCosman** [comment]
updated readme
