### ISSUE TITLE
Git prompt counts no longer appear in submodules

### ISSUE THREAD

**Issue by lydell** [IlanCosman/tide#290]
#### Describe the bug

In git submodules, the git branch is shown but the counts (such as `*10 !1 ?1`) are missing.

It worked in v5.0.1, but newer versions are broken. Note: I’m not sure _exactly_ which version broke it (but I’m making a guess at the very end).

#### Steps to reproduce

```
~/stuff
❯ mkdir sub

~/stuff
❯ cd sub

~/stuff/sub
❯ git init
Initialized empty Git repository in /Users/lydell/stuff/sub/.git/

~/stuff/sub main
❯ git submodule add git@github.com:IlanCosman/tide.git
Cloning into '/Users/lydell/stuff/sub/tide'...
remote: Enumerating objects: 6942, done.
remote: Counting objects: 100% (1159/1159), done.
remote: Compressing objects: 100% (283/283), done.
remote: Total 6942 (delta 952), reused 1011 (delta 859), pack-reused 5783
Receiving objects: 100% (6942/6942), 6.20 MiB | 8.57 MiB/s, done.
Resolving deltas: 100% (4425/4425), done.

~/stuff/sub main +2
❯ cd tide

~/stuff/sub/tide main
❯ touch new_file

~/stuff/sub/tide main
❯ rm README.md

~/stuff/sub/tide main
❯ git -C (git rev-parse --git-dir)/.. --no-optional-locks status --porcelain
fatal: this operation must be run in a work tree
```

Notice how you got `+2` in the top repo, but no counts in the submodule. After creating `new_file`, it should be `?1` and after deleting `README.md` it should be `!1 ?1`.

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.4.1
tide version: 5.2.2
term: xterm-256color
os: macOS Monterey 12.3.1
terminal emulator: iTerm2
fish startup: 21.23 millis
fisher plugins: jorgebucaran/fisher IlanCosman/tide@v5
```

#### Additional context

Previous similar issue: https://github.com/IlanCosman/tide/issues/138

That issue says `fatal: this operation must be run in a work tree` is printed, but that’s not the case now. But that seems to be due to a [2>/dev/null](https://github.com/IlanCosman/tide/blob/5a6bf534f7eed87127f8ad0368c5aba58e1c99d1/functions/_tide_item_git.fish#L42).

That issue was fixed here: https://github.com/IlanCosman/tide/commit/85d1741f40f296172465b6de926f3439e0923edb

Notice how that commit introduces the `--is-inside-git-dir` flag. That flag was recently removed: https://github.com/IlanCosman/tide/commit/dccc5120f10751cbc397d4cb6dc1518cd10aeeb2. I’m not sure that’s the culprit, but in case it is I’m leaving this info here!

I haven’t noticed this issue until now, because I haven’t updated tide in a long time. I did so because `tide bug-report` told me yesterday (https://github.com/IlanCosman/tide/issues/285).

**Comment by IlanCosman** [comment]
Yup, I borked submodules, sorry 😄 Gotta add a submodule test.
