### ISSUE TITLE
Unclean git worktree dir no longer changes prompt background to yellow w/ local diff status icons

### ISSUE THREAD

**Issue by cap10morgan** [IlanCosman/tide#296]
#### Describe the bug

Until recently if I was in a git worktree directory (i.e. not the primary working directory but a worktree dir created off of one) that was unclean (i.e. `git status` reported something other than "working tree clean") the background of the git section of the prompt would change from green to yellow and show some status icons. But it now just stays green with no icons.

I tried running `tide configure` again but it didn't fix it.

#### Steps to reproduce

1. cd to clean git working directory
1. touch `foo`
1. observe background color of next prompt stay green w/ no status icons

#### Screenshots

Don't think I have a screenshot of the old behavior but here's one of the new (broken) behavior:

<img width="1003" alt="Screen Shot 2022-04-29 at 1 04 45 PM" src="https://user-images.githubusercontent.com/59748/166009796-e7761dc5-941f-4a5b-b11d-a2f67173ae6d.png">

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.4.1
tide version: 5.2.2
term: xterm-256color
os: macOS 12.3.1
terminal emulator: iTerm2 3.4.15
fish startup: 12.29 millis
fisher plugins: jorgebucaran/fisher oh-my-fish/plugin-aws IlanCosman/tide@v5
```

#### Additional context

I'm not sure when this broke, I just noticed it yesterday.

**Comment by IlanCosman** [comment]
I cant reproduce 😞 Can you try reproducing using `tide bug-report --clean`?

**Comment by cap10morgan** [comment]
> I cant reproduce 😞 Can you try reproducing using `tide bug-report --clean`?

It happens there too. This is using git version 2.36.0.

**Comment by IlanCosman** [comment]
Anything special about this git repo? Can you try creating a really simple repo and reproducing there?

**Comment by cap10morgan** [comment]
OH! It looks like it only happens in worktrees that aren't the main working directory (i.e. their `.git` is a file that contains a pointer back to the primary git working directory with the real `.git` dir in it).

**Comment by IlanCosman** [comment]
Ah, sounds like this is related to https://github.com/IlanCosman/tide/issues/290. Can you try installing from main to see if that fixes it? `fisher install ilancosman/tide`

5.3 should be released soon.

**Comment by cap10morgan** [comment]
> Ah, sounds like this is related to #290. Can you try installing from main to see if that fixes it? `fisher install ilancosman/tide`
> 
> 5.3 should be released soon.

Will do!

**Comment by cap10morgan** [comment]
Yep, fixed on main branch. Thanks @IlanCosman!
