### ISSUE TITLE
Multiple lines in left prompt

### ISSUE THREAD

**Issue by jose1711** [IlanCosman/tide#297]
Left prompt is supposed to have out of the box support for multiple lines. Could you please tell me (to someone quite new to `fish`) what I am doing wrong with
```console
$ type _tide_item_foo
_tide_item_foo is a function with definition
# Defined via `source`
function _tide_item_foo
  printf "line1\nline2"
end
set  _tide_left_items foo os
```
This results in
![obrázok](https://user-images.githubusercontent.com/1406222/166207904-4bc55ea3-11dd-4d9c-abc9-7ddd8474952f.png)
And furthermore it breaks PWD:
```console
set  _tide_left_items foo os pwd
```
![obrázok](https://user-images.githubusercontent.com/1406222/166208064-46a8023c-ccfb-40b7-88ae-84a11b29cbc0.png)

Thank you.

**Comment by IlanCosman** [comment]
A number of problems with this:

1. You would use the `newline` item to produce newlines. So have 1 item that says `line1` then have the `newline` item, then have an item that says `line2`.

2. You should be editing `tide_left_prompt_items`, not `_tide_left_items`. `_tide_left_items`, as inidicated by the underscore, is an internal Tide variable.

**Comment by jose1711** [comment]
> A number of problems with this:
> 
>     1. You would use the `newline` item to produce newlines. So have 1 item that says `line1` then have the `newline` item, then have an item that says `line2`.

Is there a solution if the value comes from a command - there can be 0, 1 or 2 lines of output?

>     2. You should be editing `tide_left_prompt_items`, not `_tide_left_items`. `_tide_left_items`, as inidicated by the underscore, is an internal Tide variable.

```console
# Defined in /home/jose/.config/fish/functions/_tide_item_taskwarrior.fish @ line 1
function _tide_item_taskwarrior
  printf "foo test"
end

set  tide_left_prompt_items taskwarrior newline os pwd
```
still results in `@PWD@`.

**Comment by IlanCosman** [comment]
> Is there a solution if the value comes from a command - there can be 0, 1 or 2 lines of output?

Not one that I feel like implementing.

> still results in @PWD@

Oh yah, I forgot to say that you should be using `_tide_print_item`. https://github.com/IlanCosman/tide/wiki/Custom-items-(prompt-segments)

**Comment by jose1711** [comment]
Still no luck.
```
function _tide_item_example
  _tide_print_item   example O' ' (uname | string split ' ')[2]
end
funcsave _tide_item_example # Save it to ~/.config/fish/functions
set tide_left_prompt_items example newline os pwd
```
Wonder what else may be wrong. 😐

**Comment by IlanCosman** [comment]
Oh, I remember. Yah, `pwd` doesn't work in the second line. Not documented anywhere haha 😅

Here are some thoughts on the subject: https://github.com/IlanCosman/tide/issues/199
