### ISSUE TITLE
`tide_left_prompt_items` and `tide_pwd_bg_color` stopped working

### ISSUE THREAD

**Issue by KnifeFed** [IlanCosman/tide#298]
#### Steps to reproduce

1. Set in config.fish:
```
set -g tide_left_prompt_items cmd_duration $tide_left_prompt_items character
set -g tide_pwd_bg_color 20252c
```
2. Changes not reflected in prompt.

#### Screenshots

![~ (iTerm2) - 2022-05-02 at 22 17 54@2x](https://user-images.githubusercontent.com/85502276/166319580-5e5b8d76-5cbe-44e5-946b-471c4d8ffa37.png)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.4.1
tide version: 5.3.0
term: xterm-256color
os: macOS 12.3.1
terminal emulator: iTerm2
fish startup: 18.22 millis
fisher plugins: franciscolourenco/done PatrickF1/fzf.fish jethrokuan/z decors/fish-colored-man jorgebucaran/autopair.fish IlanCosman/tide@v5
```

#### Additional context

This has worked for me before but broke after an update. I'm not sure which one, maybe 5.1.0 from Apr 01, 2022
 (there are two 5.1.0 releases, the other one being from Aug 14, 2021).

**Comment by IlanCosman** [comment]
Can't reproduce.

**Comment by KnifeFed** [comment]
Ok, I guess that's that then.

**Comment by AftDawn** [comment]
I'm also having this problem, i wanted to add the OS icon to Tide, but `set --universal tide_left_prompt_items os $tide_left_prompt_items` didn't work, so i had to modify the `fish_variables` file manually to add in the OS icon

**Comment by MisatoTremor** [comment]
I have a similar problem with `tide_right_prompt_items`. I can set that to whatever value I want, but it simply uses the default items.

**Comment by IlanCosman** [comment]
It should be noted that you have to restart your shell to see most changes. Tide caches various things.

**Comment by IlanCosman** [comment]
Yah I can reproduce this when I don't restart the shell after changing `config.fish`, but if I do restart then it goes away. It's just a caching thing.

**Comment by KnifeFed** [comment]
Yeah, I definitely restarted the shell, the terminal app and the computer, but it didn't fix the issue.
