### ISSUE TITLE
`tide_install --unattended` errors 404

### ISSUE THREAD

**Issue by drhayes** [IlanCosman/tide#30]
#### Is your feature request related to a problem? Please describe

I'm trying to make a series of scripts that re-build my environment from a fresh machine install. For example, doing something like `bash -c $(curl -fsSL https://setup.drhayes.io)` should install everything I care about and use daily.

I noticed your GitHub action uses the `--unattended` flag and thought it would work for me... but it doesn't, yet.

#### Describe the solution you'd like

Making the `--unattended` flag work and documenting it would be neato. But I'll take whatever you've got. 👍🏽 

I'm a fish newbie but I'm totally willing to help.

**Comment by IlanCosman** [comment]
Thanks for bringing this to my attention! I'll see what I can do to get it fixed.

**Comment by drhayes** [comment]
Sorry, my dumb fingers hit enter before I was done putting in the feature request. I put in more info now.

**Comment by drhayes** [comment]
Totally fixed! Thanks.
