### ISSUE TITLE
Can't install using the provided script and broke my fish shell

### ISSUE THREAD

**Issue by PhantomLel** [IlanCosman/tide#300]
Hi, there seems to be some issue in the provided manual installation script. I saw that it said it might not work, but after running it, I am encountering many error messages and can no longer use fish as shown below.
https://pastebin.com/CzL3T5bp
I am using the kitty terminal, but it doesn't work with other terminals either. I also just uninstalled Oh My Fish, so maybe that messed something up?
Also, after the errors show up the shell just crashes after any user input

**Comment by IlanCosman** [comment]
Old fish version.
