### ISSUE TITLE
tide is slow on remote filesystems

### ISSUE THREAD

**Issue by Conchylicultor** [IlanCosman/tide#301]
When navigating on remote file system (e.g. a Google Cloud bucket mounted locally), there's a ~0.5-1.5s delay each time the prompt is rendered. By comparison, navigating on local filesystem is fast (prompt is rendered instantly).

I'm very confident this delay is comming from `tide`:
If I replace `fish_prompt` by a [dummy one](https://fishshell.com/docs/current/cmds/fish_prompt.html#example), all delays goes away.

However, I have issues understanding where this delay is comming from.

For debugging, I removed all items, but there's still the long latency before prompt is displayed:

```fish
set --universal tide_left_prompt_items newline character
set --universal tide_right_prompt_items
```

I assume somewhere else hidden in tide code is a command which trigger slow RPC calls, slowing down the rendering. Any idea where this could be comming from ?

If this help, the problem also exists with the default `fish_prompt` implementation (from [fish-shell](https://github.com/fish-shell/fish-shell/blob/master/share/functions/fish_prompt.fish)). Here the delay is comming from the [`fish_vcs_prompt`](https://fishshell.com/docs/current/cmds/fish_git_prompt.html#cmd-fish-git-prompt) call, which is running git command looking at the file system, adding a noticable latency.

But with tide, I disabled all items so I don't understand why I still get the latency.
Any idea where this could be comming from ?

```
fish version: 3.4.0
tide version: 5.3.0
term: xterm-256color
os: debian
fish startup: 9.44 millis
fisher plugins: jorgebucaran/fisher IlanCosman/tide@v5
```

**Comment by Conchylicultor** [comment]
I believe I found the issue. It is due to the `test -w .` and ` test -e` executed in `_tide_pwd`.

Those trigger IO operation which have to be sent remotely, slowing down significantly `fish_prompt` execution.

It would be nice to add an option to disable those.

**Comment by Conchylicultor** [comment]
It seems that by setting `set --universal tide_pwd_markers` to empty (to disable the slow read) fixed my issue for now. `tide_pwd_markers` looks like an internal variable, but that seems the easiest fix now.

**Comment by IlanCosman** [comment]
tide_pwd_markers is not an internal variable.

I'm going to close this because it's a super niche problem with a solution (thanks for figuring that out 🙂)
