### ISSUE TITLE
Add AWS CLI item

### ISSUE THREAD

**Issue by aphillips19** [IlanCosman/tide#309]
#### Is your feature request related to a problem? Please describe

As an AWS user, I often switch between various AWS roles/accounts when running AWS CLI commands to build, deploy, and test projects. The AWS CLI provides various methods to assume a role, the ones I use most often being [named profiles](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-profiles.html), and in certain situations, by setting custom credentials with a script. Named profiles are used with either the `--profile` argument added to AWS CLI commands, or applied to all commands by setting the `AWS_PROFILE` environment variable.

Tide (and every other prompt that I know of) does not show the current AWS profile, nor does it show whether or not custom credentials have been set. This can lead to mistakes where the user thinks they have assumed a certain role or region, but actually run commands with another. It's easy to make this mistake because there are [so many different ways to assume a role](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html), and it's hard to remember which ones are set and which ones take precedence (though one can always check current status by running `aws configure list`).

#### Describe the solution you'd like

I would like to show the current AWS profile, region, and override status in the prompt.

For example, when I use a named profile `my-profile` by setting the AWS_PROFILE environment variable, I want the prompt to show:
```
~/dir aws:my-profile
```

but if if I change the region, I'd like to know:

```
~/dir aws:my-profile:us-west-2
```

and if no profile is set, but I have credentials anyways (because I set them with some other process, or because I overrode them with environment variables), I'd like to know that, too

```
~/dir aws:*
```

#### Additional context
* `aws configure list` prints the current profile, credentials, and region. It even prints where they come from, too. But it takes a couple seconds to complete on my machine, so it should probably happen async, or have cached results somehow. Example output below, after setting a named profile by env var:
```
      Name                    Value             Type    Location
      ----                    -----             ----    --------
   profile           my-profile                 env    ['AWS_PROFILE', 'AWS_DEFAULT_PROFILE']
access_key     ****************5PTY   custom-process
secret_key     ****************SsG2   custom-process
    region                us-west-2      config-file    ~/.aws/config
```

* It would be nice to be able to easily turn this prompt on and off. I personally would always keep it on, but I imagine that occasional AWS users wouldn't want it to clutter up their prompt all the time. Does Tide allow that to happen?

**Comment by IlanCosman** [comment]
> Tide (and every other prompt that I know of) does not show the current AWS profile,

Tide does [have an aws item](https://github.com/IlanCosman/tide/blob/defabdd772fd7dacfea324202f9394b2c6ffc719/functions/_tide_item_aws.fish) which should display `AWS_PROFILE` if it is not empty.

**Comment by aphillips19** [comment]
Oh, awesome! Embarrassing I missed that.

Would you accept a PR with the enhancement for showing overridden/dirty configuration?

**Comment by IlanCosman** [comment]
> Oh, awesome! Embarrassing I missed that.

No worries, I don't think I've updated the documentation to include that item yet 😅 

> Would you accept a PR with the enhancement for showing overridden/dirty configuration?

Sure 👍

**Comment by IlanCosman** [comment]
Going to close this as the major point of an AWS item is already resolved, and any further features would have to come from a PR, since I have no experience here.
