### ISSUE TITLE
Current directory not updating on change

### ISSUE THREAD

**Issue by jchilders** [IlanCosman/tide#31]
#### Describe the bug

When opening a new shell, the prompt correctly displays the current directory. After changing directories, however, it does not update

#### Steps to reproduce

1. Open shell:

```console
~ ❯

```

2. Change directories:

```console
~ ❯ cd workspace/

~ ❯ pwd
/Users/james.childers/workspace

~ ❯
```

3. Directory displayed in prompt does not update

#### Expected behavior

Directory displayed by prompt should update

#### Environment (please complete the following information)

- Operating System: Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64

- Output of `tide bug-report`: 

```console
fish, version 3.1.2
tide, version 2.4.0
screen-256color

```

#### Additional context

It doesn't appear that the `_tide_pwd` function is getting called when the directory is changed. I only see it get called when a new fish session is instantiated, and not at anytime thereafter.

**Comment by jchilders** [comment]
That seems to work just fine:

```console
~ ❯ function foo --on-variable PWD
            echo hello
    end

~ ❯ pwd
/Users/james.childers

~ ❯ cd workspace/
hello

~ ❯ cd ..
hello

~ ❯
```

**Comment by IlanCosman** [comment]
Interesting. I just noticed that your `$TERM` is `screen-256color`, not `xterm-256color`. You're using Tmux correct? I haven't ever used it so I can't guarantee it will work, but in https://github.com/IlanCosman/tide/issues/26, @matthiasdebernardini, said that Tide works fine with Tmux. Does Tide work for you in a normal terminal?

**Comment by jchilders** [comment]
Ok, I got it working, but it required uninstalling oh-my-fish. oh-my-fish is doing something to swallow PWD signals, but only for functions that are saved to a file. If you define the function in the shell itself, it works fine.

**Comment by IlanCosman** [comment]
Lovely. Maybe I should make that a part of the bug template. Tide has no vested interest in functioning alongside OMF.

**Comment by gokulsoumya** [comment]
I'm having the same problem, and I'm not using `oh-my-fish` (using `scuba` instead):

```
❯ tide bug-report
fish, version 3.1.2-1537-g4bfda4744
tide, version 2.4.0
alacritty
```
My findings:

- The check with a dummy functions for `--on-variable PWD` shows correct results on directory change, both when defined during the session and also when saved to `~/.config/fish/conf.d`.

- Another plugin, [zoxide](https://github.com/ajeetdsouza/zoxide), uses the same `PWD` variable change mechanism and it seems to work without any problems.

---
P.S. I uninstalled my original `tide` installation with `_tide_sub_uninstall` and reinstalled with scuba (alongside the uninstallation of `fisher`

**Comment by gokulsoumya** [comment]
Interestingly, the bug seems to completely disappear once I *manually* run `_tide_pwd` after starting the shell.

**Comment by IlanCosman** [comment]
Can you try a completely clean fish, with fisher 4.0? Tide just switched again, only 9 days with Scuba lol, but Fisher came out much earlier than was projected.

**Comment by gokulsoumya** [comment]
Ah yeah switching to fisher solves the problem. Thanks :tada:
