### ISSUE TITLE
Not working (macbook air 2017)(macos monterey)(alacritty terminal)

### ISSUE THREAD

**Issue by shadows1003929** [IlanCosman/tide#313]
#### Describe the bug

Run the command 
fisher install IlanCosman/tide@v5
immediately a wall of text pops up

Wall of text - 
Fetching https://api.github.com/repos/IlanCosman/tide/tarball/v5
Installing IlanCosman/tide@v5
           /Users/adviksharma/.config/fish/functions/_tide_1_line_prompt.fish
           /Users/adviksharma/.config/fish/functions/_tide_2_line_prompt.fish
           /Users/adviksharma/.config/fish/functions/_tide_cache_variables.fish
           /Users/adviksharma/.config/fish/functions/_tide_detect_os.fish
           /Users/adviksharma/.config/fish/functions/_tide_find_and_remove.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_aws.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_character.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_chruby.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_cmd_duration.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_context.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_docker.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_git.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_go.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_java.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_jobs.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_kubectl.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_node.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_os.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_php.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_private_mode.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_rustc.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_shlvl.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_status.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_terraform.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_time.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_toolbox.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_vi_mode.fish
           /Users/adviksharma/.config/fish/functions/_tide_item_virtual_env.fish
           /Users/adviksharma/.config/fish/functions/_tide_print_item.fish
           /Users/adviksharma/.config/fish/functions/_tide_pwd.fish
           /Users/adviksharma/.config/fish/functions/_tide_remove_unusable_items.fish
           /Users/adviksharma/.config/fish/functions/_tide_sub_bug-report.fish
           /Users/adviksharma/.config/fish/functions/_tide_sub_configure.fish
           /Users/adviksharma/.config/fish/functions/fish_mode_prompt.fish
           /Users/adviksharma/.config/fish/functions/fish_prompt.fish
           /Users/adviksharma/.config/fish/functions/tide
           /Users/adviksharma/.config/fish/functions/tide.fish
           /Users/adviksharma/.config/fish/conf.d/_tide_init.fish
           /Users/adviksharma/.config/fish/completions/tide.fish
~/.config/fish/functions/_tide_item_git.fish (line 46): $(...) is not supported. In fish, please use '(git)'.
        "$(git $_set_dir_opt stash list 2>/dev/null | count
         ^
from sourcing file ~/.config/fish/functions/_tide_item_git.fish
	called on line 187 of file /usr/local/share/fish/vendor_functions.d/fisher.fish
in function 'fisher' with arguments 'install IlanCosman/tide@v5'
source: Error while reading file '/Users/adviksharma/.config/fish/functions/_tide_item_git.fish'
~/.config/fish/functions/tide/configure/functions/_fake_tide_cache_variables.fish (line 4): $(...) is not supported. In fish, please use '(set_color)'.
    set -gx _fake_tide_color_truncated_dirs "$(set_color $fake_tide_pwd_color_truncated_dirs)"
                                             ^
from sourcing file ~/.config/fish/functions/tide/configure/functions/_fake_tide_cache_variables.fish
	called on line 14 of file ~/.config/fish/functions/_tide_sub_configure.fish
from sourcing file ~/.config/fish/functions/_tide_sub_configure.fish
	called on line 187 of file /usr/local/share/fish/vendor_functions.d/fisher.fish
in function 'fisher' with arguments 'install IlanCosman/tide@v5'
source: Error while reading file '/Users/adviksharma/.config/fish/functions/tide/configure/functions/_fake_tide_cache_variables.fish'
Updated 1 plugin/s
string length: Unknown option '-V'

~/.config/fish/functions/fish_prompt.fish (line 1):
string length -V "$_tide_prompt_14071[1]$_tide_prompt_14071[2]"
^
in command substitution
	called on line 13 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution

(Type 'help string' for related documentation)
math: Expected at least 1 args, got 0
set: Unknown option '-f'

~/.config/fish/functions/_tide_pwd.fish (line 5):
        set -f icon
        ^
in function '_tide_pwd'
	called on line 1 of file ~/.config/fish/functions/fish_prompt.fish
in command substitution
	called on line 14 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution

(Type 'help set' for related documentation)
string length: Unknown option '-V'

~/.config/fish/functions/_tide_pwd.fish (line 14):
    string join / $split_output | string length -V | read -g _tide_pwd_len
    ^
in function '_tide_pwd'
	called on line 1 of file ~/.config/fish/functions/fish_prompt.fish
in command substitution
	called on line 14 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution

(Type 'help string' for related documentation)
set: Unknown option '-f'

~/.config/fish/functions/_tide_print_item.fish (line 2):
    var=tide_"$item"_bg_color set -f item_bg_color $$var
    ^
in function '_tide_print_item' with arguments 'pwd @PWD@'
	called on line 18 of file ~/.config/fish/functions/_tide_1_line_prompt.fish
in function '_tide_item_pwd'
	called on line 4 of file ~/.config/fish/functions/_tide_1_line_prompt.fish
in function '_tide_1_line_prompt'
in command substitution

(Type 'help set' for related documentation)
~/.config/fish/functions/_tide_item_git.fish (line 46): $(...) is not supported. In fish, please use '(git)'.
        "$(git $_set_dir_opt stash list 2>/dev/null | count
         ^
from sourcing file ~/.config/fish/functions/_tide_item_git.fish
	called on line 1 of file ~/.config/fish/functions/_tide_1_line_prompt.fish
in command substitution
	called on line 4 of file ~/.config/fish/functions/_tide_1_line_prompt.fish
in function '_tide_1_line_prompt'
in command substitution
source: Error while reading file '/Users/adviksharma/.config/fish/functions/_tide_item_git.fish'
fish: Unknown command: _tide_item_git
~/.config/fish/functions/_tide_1_line_prompt.fish (line 4):
        _tide_item_$item
        ^
in function '_tide_1_line_prompt'
in command substitution
set: Unknown option '-f'

~/.config/fish/functions/_tide_print_item.fish (line 2):
    var=tide_"$item"_bg_color set -f item_bg_color $$var
    ^
in function '_tide_print_item' with arguments 'node ⬢\  16.14.0'
	called on line 2 of file ~/.config/fish/functions/_tide_item_node.fish
in function '_tide_item_node'
	called on line 11 of file ~/.config/fish/functions/_tide_1_line_prompt.fish
in function '_tide_1_line_prompt'
in command substitution

(Type 'help set' for related documentation)
string length: Unknown option '-V'

~/.config/fish/functions/fish_prompt.fish (line 1):
string length -V "$_tide_prompt_14071[1]$_tide_prompt_14071[2]"
^
in command substitution
	called on line 13 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution

(Type 'help string' for related documentation)
math: Expected at least 1 args, got 0
set: Unknown option '-f'

~/.config/fish/functions/_tide_pwd.fish (line 5):
        set -f icon
        ^
in function '_tide_pwd'
	called on line 1 of file ~/.config/fish/functions/fish_prompt.fish
in command substitution
	called on line 14 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution

(Type 'help set' for related documentation)
string length: Unknown option '-V'

~/.config/fish/functions/_tide_pwd.fish (line 14):
    string join / $split_output | string length -V | read -g _tide_pwd_len
    ^
in function '_tide_pwd'
	called on line 1 of file ~/.config/fish/functions/fish_prompt.fish
in command substitution
	called on line 14 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution

(Type 'help string' for related documentation)

#### Steps to reproduce

1. Set ... to ...
2. Run ...
3. See error

#### Environment

Output of `tide bug-report`: 

```text

```

**Comment by IlanCosman** [comment]
Old fish version.
