### ISSUE TITLE
Tide Theme

### ISSUE THREAD

**Issue by Papigoe** [IlanCosman/tide#316]
I have installed Fisher, removed OMF, and installed and configured Tide prompt.  After all is said and done, and a reboot, this is what I get for a prompt.  Again, I went through all the configuration questions/steps for Tide. 
![Screenshot_8](https://user-images.githubusercontent.com/46576390/180077020-6b8ac869-b152-4b9c-945b-228455bffc5c.png)

**Comment by IlanCosman** [comment]
I assume that is not what you configured Tide to look like.

In that case, it seems you are using Garuda linux (?), so make sure that starship isn't being loaded somewhere in your `config.fish` or other config directories.

**Comment by Papigoe** [comment]
Aye I am using Garuda/KDE and I do have the Starship file and Fish calls for renamed in .config/starfish.toml to starfish.toml.old
[keithcrestcolour.jpg][Keith Roebuck.png]﻿
[image]

[image]

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by Papigoe** [comment]
It's NAE completed, but your action tells me that Github just cannae be bothered.  Nae surprised.

[keithcrestcolour.jpg][Keith Roebuck.png]﻿
[image]

[image]

Sent with Proton Mail secure email.

------- Original Message -------
