### ISSUE TITLE
Cannot install tide on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by heisablekvay** [IlanCosman/tide#318]
After manual installation of Tide I get this log messages:

<details><summary>Log</summary>
<pre>
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current<br>
                                 Dload  Upload   Total   Spent    Left  Speed<br>
100 35362    0 35362    0     0  89751      0 --:--:-- --:--:-- --:--:-- 89751<br>
status: Subcommand 'dirname' is not valid<br>
status: Subcommand 'dirname' is not valid<br>
~/.config/fish/conf.d/_tide_init.fish (line 5): <br>
    _load_config lean<br>
    ^<br>
in function '_tide_init_install'<br>
in event handler: handler for generic event “_tide_init_install”<br>
~/.config/fish/conf.d/_tide_init.fish (line 6): <br>
    _tide_finish<br>
    ^<br>
in function '_tide_init_install'<br>
in event handler: handler for generic event “_tide_init_install”<br>
Welcome to fish, the friendly interactive shell<br>
Type `help` for instructions on how to use fish<br>
Configure tide prompt? [Y/n] y<br>
~/.config/fish/functions/tide.fish (line 9): Invalid index value<br>
        _tide_sub_$argv[1] $argv[2..]<br>
                                    ^<br>
in function 'tide' with arguments 'configure'<br>
    called on line 18 of file ~/.config/fish/conf.d/_tide_init.fish<br>
in function '_tide_init_install'<br>
in event handler: handler for generic event “_tide_init_install”<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query aws'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query chruby'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query docker'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query git'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query go'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query java'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query kubectl'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query node'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query php'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query rustc'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query terraform'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query toolbox'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
type: Unknown option “--query”<br>
/usr/share/fish/functions/type.fish (line 7): <br>
    argparse -n type -x t,p,P $options -- $argv<br>
    ^<br>
in function 'type' with arguments '--query python python3'<br>
    called on line 10 of file ~/.config/fish/functions/_tide_remove_unusable_items.fish<br>
in function '_tide_remove_unusable_items'<br>
    called on line 5 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
set_color: Expected argument for option b<br>
<br>
~/.config/fish/functions/_tide_pwd.fish (line 1): <br>
set_color normal -b $tide_pwd_bg_color; set_color $tide_pwd_color_dirs<br>
^<br>
in command substitution<br>
    called on line 3 of file ~/.config/fish/functions/_tide_pwd.fish<br>
from sourcing file ~/.config/fish/functions/_tide_pwd.fish<br>
    called on line 1 of file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
    called on line 1 of file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
    called on line 7 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
<br>
(Type 'help set_color' for related documentation)<br>
set_color: Expected argument for option b<br>
<br>
~/.config/fish/functions/_tide_pwd.fish (line 1): <br>
set_color normal -b $tide_pwd_bg_color; set_color $tide_pwd_color_dirs<br>
^<br>
in command substitution<br>
    called on line 3 of file ~/.config/fish/functions/_tide_pwd.fish<br>
from sourcing file ~/.config/fish/functions/_tide_pwd.fish<br>
    called on line 7 of file ~/.config/fish/functions/fish_prompt.fish<br>
from sourcing file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
<br>
(Type 'help set_color' for related documentation)<br>
string length: Unknown option “-V”<br>
<br>
~/.config/fish/functions/fish_prompt.fish (line 1): <br>
string length -V "$_tide_prompt_2143338[1]$_tide_prompt_2143338[2]"<br>
^<br>
in command substitution<br>
    called on line 13 of file ~/.config/fish/functions/fish_prompt.fish<br>
in function 'fish_prompt'<br>
in command substitution<br>
<br>
(Type 'help string' for related documentation)<br>
math: Expected at least 1 args, got 0<br>
set: Unknown option “-f”<br>
<br>
~/.config/fish/functions/_tide_pwd.fish (line 5): <br>
        set -f icon <br>
        ^<br>
in function '_tide_pwd'<br>
    called on line 1 of file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
    called on line 14 of file ~/.config/fish/functions/fish_prompt.fish<br>
in function 'fish_prompt'<br>
in command substitution<br>
<br>
(Type 'help set' for related documentation)<br>
~/.config/fish/functions/_tide_pwd.fish (line 10): Invalid index value<br>
        set -l split_output "$icon$split_pwd[1]" $split_pwd[2..] ||<br>
                                                                  ^<br>
in function '_tide_pwd'<br>
    called on line 1 of file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
    called on line 14 of file ~/.config/fish/functions/fish_prompt.fish<br>
in function 'fish_prompt'<br>
in command substitution<br>
set: Array index out of bounds<br>
string length: Unknown option “-V”<br>
<br>
~/.config/fish/functions/_tide_pwd.fish (line 14): <br>
    string join / $split_output | string length -V | read -g _tide_pwd_len<br>
    ^<br>
in function '_tide_pwd'<br>
    called on line 1 of file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
    called on line 14 of file ~/.config/fish/functions/fish_prompt.fish<br>
in function 'fish_prompt'<br>
in command substitution<br>
<br>
(Type 'help string' for related documentation)<br>
string replace: Expected at least 2 args, got 1<br>
string length: Unknown option “-V”<br>
<br>
~/.config/fish/functions/fish_prompt.fish (line 1): <br>
string length -V "$_tide_prompt_2143338[1]$_tide_prompt_2143338[2]"<br>
^<br>
in command substitution<br>
    called on line 13 of file ~/.config/fish/functions/fish_prompt.fish<br>
in function 'fish_prompt'<br>
in command substitution<br>
<br>
(Type 'help string' for related documentation)<br>
math: Expected at least 1 args, got 0<br>
set: Unknown option “-f”<br>
<br>
~/.config/fish/functions/_tide_pwd.fish (line 5): <br>
        set -f icon <br>
        ^<br>
in function '_tide_pwd'<br>
    called on line 1 of file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
    called on line 14 of file ~/.config/fish/functions/fish_prompt.fish<br>
in function 'fish_prompt'<br>
in command substitution<br>
<br>
(Type 'help set' for related documentation)<br>
~/.config/fish/functions/_tide_pwd.fish (line 10): Invalid index value<br>
        set -l split_output "$icon$split_pwd[1]" $split_pwd[2..] ||<br>
                                                                  ^<br>
in function '_tide_pwd'<br>
    called on line 1 of file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
    called on line 14 of file ~/.config/fish/functions/fish_prompt.fish<br>
in function 'fish_prompt'<br>
in command substitution<br>
set: Array index out of bounds<br>
string length: Unknown option “-V”<br>
<br>
~/.config/fish/functions/_tide_pwd.fish (line 14): <br>
    string join / $split_output | string length -V | read -g _tide_pwd_len<br>
    ^<br>
in function '_tide_pwd'<br>
    called on line 1 of file ~/.config/fish/functions/fish_prompt.fish<br>
in command substitution<br>
    called on line 14 of file ~/.config/fish/functions/fish_prompt.fish<br>
in function 'fish_prompt'<br>
in command substitution<br>
<br>
(Type 'help string' for related documentation)<br>

</pre>
</details>

Next fish launch is not available, fish crushes.
To resolve the trouble I had to remove everything from ~/.config/fish directory except config.fish.
Still, I cannot install your cool Tide prompt. Please help me.

I can provide additional information about my system if needed

**Comment by IlanCosman** [comment]
Old fish version.
