### ISSUE TITLE
Unknown command path on pwd

### ISSUE THREAD

**Issue by rReyvn** [IlanCosman/tide#319]
#### Describe the bug

I got error message 'Unknown command path' this issue related to 

> commit  132dff7

so i fallback any changes on _tide_pwd.fish and its working fine

#### Steps to reproduce

1. Type any command
2. See error

#### Screenshot
![image](https://user-images.githubusercontent.com/87917880/182011795-0db1c753-9f8c-4ed2-9ddd-c4bb91d37a38.png)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.4.1
tide version: 5.4.0
term: xterm-kitty
os: Manjaro
terminal emulator: Kitty
fish startup: 12.32 millis
fisher plugins: jorgebucaran/fisher jorgebucaran/nvm.fish ilancosman/tide@v5 jethrokuan/z gazorby/fish-exa takashabe/fish-fzf
fish: Unknown command: path
~/.config/fish/functions/_tide_pwd.fish (line 17): 
        if path is $parent_dir/$dir_section/$tide_pwd_markers
           ^
in function '_tide_pwd'
	called on line 1 of file ~/.config/fish/functions/fish_prompt.fish
in command substitution
	called on line 14 of file ~/.config/fish/functions/fish_prompt.fish
in function 'fish_prompt'
in command substitution

**Comment by IlanCosman** [comment]
Old fish version.

**Comment by rReyvn** [comment]
oww, my bad. i thought i use the latest one since i reinstalled everything
