### ISSUE TITLE
Unknown Command path

### ISSUE THREAD

**Issue by an-dutra** [IlanCosman/tide#320]
#### Describe the bug

When enter 2 directories, I receive the error: 
```
fish: Unknown command: path
~/.config/fish/functions/_tide_pwd.fish (linha 17): 
        if path is $parent_dir/$dir_section/$tide_pwd_markers
           ^
in function '_tide_pwd'
	chamado na linha 1 do arquivo “~/.config/fish/functions/fish_prompt.fish”
na substituição de comando
	chamado na linha 14 do arquivo “~/.config/fish/functions/fish_prompt.fish”
in function 'fish_prompt'
na substituição de comando
```

#### Steps to reproduce

1. mkdir -p test/test
2. Run cd test/test
3. See error

#### Screenshots

![image](https://user-images.githubusercontent.com/40439091/182129919-fb53cf09-e1ea-4ecb-8730-4ecc9b6eb712.png)

#### Environment

```
fish version: 
tide version: 5.4.0
term: xterm-256color
os: Manjaro Linux
terminal emulator: Terminator
fish startup: 15.79 millis
fisher plugins: jorgebucaran/fisher jethrokuan/z ilancosman/tide@v5

```

**Comment by IlanCosman** [comment]
Old fish version. I forgot that Manjaro is a bit slower than Arch, sorry about that.

**Comment by an-dutra** [comment]
Thanks for the quick answer, I will update fish manually.
