### ISSUE TITLE
Showing the version of different languages.

### ISSUE THREAD

**Issue by Greed058** [IlanCosman/tide#325]
So I noticed that tide only shows my node version and no other languages' version 

So what I'm suggesting is if I'm on a folder with lots of python file, it should show my python version......

**Comment by IlanCosman** [comment]
> So I noticed that tide only shows my node version and no other languages' version

That's not correct. Tide shows various language's versions when a relevant file is nearby. e.g. rust version when `cargo.toml` is present, go version when `go.mod` is present.

As for python, Tide doesn't show the version, but it will show the virtualenv if one is being used.
