### ISSUE TITLE
Fish sometimes crashes when using vi key bindings

### ISSUE THREAD

**Issue by phisko** [IlanCosman/tide#326]
#### Describe the bug

When using `fish_vi_key_bindings`, `fish` sometimes crashes with the following output:

```
assertion "event_storage_.empty() && "event_storage_ should be empty"" failed: file "/c/S/fish/src/fish-3.5.0/src/input.cpp", line 370, function: void inputter_t::function_push_args(readline_cmd_t)
      0 [main] fish 2318 cygwin_exception::open_stackdumpfile: Dumping stack trace to fish.exe.stackdump
Terminate batch job (Y/N)?
```

#### Steps to reproduce

1. Add `fish_vi_key_bindings` to `~/.config/fish/config.fish`
2. Type a command, such as `git branch -r --merged`
3. Press ESC to enter normal mode
4. Press `F` and then `m` to move back to the `m` in `merged`
5. Press `c`, then `t`, then `r` to change all characters until the `r` in `merged`
6. Notice `fish` sometimes crashes

#### Environment

```text
fish version: 3.5.0
tide version: 5.4.0
term: xterm-256color
os: Windows 10
terminal emulator: Windows Terminal
fish startup: 62.79 millis
fisher plugins: jorgebucaran/fisher PatrickF1/fzf.fish ilancosman/tide@v5.4.0
```

#### Additional context

This doesn't occur with the default prompts. This also occurs on other terminals such as the default MSYS2 MinTTY.

**Comment by IlanCosman** [comment]
Can't reproduce on macOS. Btw you only have to run `fish_vi_key_bindings` once interactively. No need to run it in config.fish.

**Comment by phisko** [comment]
The repro isn't 100% unfortunately. It seems like it maybe happens more often when using a `c-t-<char>` combination to "change 'til <char>". After the repro steps listed above, try this:

5. Press `c`, then `t`, then `r` to change all characters until the `r` in `merged`

I've edited the original repro steps to reflect this
