### ISSUE TITLE
How do I determine what the pieces of the prompt are

### ISSUE THREAD

**Issue by cjappl** [IlanCosman/tide#328]
Hi,

Just installed today, and it seems great!

I was wondering what the best way is to determine "What is that in my prompt?"

I have a prompt that looks like:

```
 master ?6 ❯
```

What is the ?6? and further, how would I figure it out on my own? 

Thanks!

**Comment by IlanCosman** [comment]
There isn't really an easy way, sorry. 

You can see which items are active on either side of the prompt with `echo $tide_left_prompt_items` or right_prompt_items respectively. Generally the names, symbols, and context of whatever you're doing should help out.

As for this specific question: https://github.com/IlanCosman/tide/wiki/What-do-the-git-icons-mean%3F
