### ISSUE TITLE
Distrobox distro indicator similar to powerlevel10k

### ISSUE THREAD

**Issue by daudix-UFO** [IlanCosman/tide#332]
#### Is your feature request related to a problem? Please describe

In Tide there is a indicator that displays if user currently work in Toolbox, but there is no that indicator for [Distrobox](https://github.com/89luca89/distrobox), it would be good to have this indicator, because now it imposible to know if you are in distrobox or not.

#### Describe the solution you'd like

Add a indicator similar to toolbox one

## Tide in Toolbox

![Снимок экрана от 2022-08-21 20-00-35](https://user-images.githubusercontent.com/77155297/185802562-89bfd40f-3a96-44c2-a6c5-3a2fcf78ea7a.png)

## Tide in Distrobox (arch)

![Снимок экрана от 2022-08-21 20-00-44](https://user-images.githubusercontent.com/77155297/185802583-2334ffc5-5dd5-43f1-bb9e-5b32ce608615.png)

## Powerlevel10k in Distrobox (arch)

![Снимок экрана от 2022-08-21 20-01-33](https://user-images.githubusercontent.com/77155297/185802597-6475595e-7291-46db-af9a-fb39cf8bcbda.png)

**Comment by IlanCosman** [comment]
I'd be happy to accept a PR 🙂 Won't be actively pursuing this.

**Comment by daudix-UFO** [comment]
Will try to do this!

**Comment by mt190502** [comment]
https://github.com/IlanCosman/tide/pull/337/files#diff-284d7fb5d575e17bbb32ce1eca5d5213e306c78a26e0fcab8740c27c0a9eba04R2

This file is not found in podman. @daudix-UFO Look this:
![image](https://user-images.githubusercontent.com/62564400/192941783-3ae1fd8d-4e8c-41f2-92d4-d20c0d1dcba4.png)
