### ISSUE TITLE
Prevent truncation of branch name

### ISSUE THREAD

**Issue by hgiesel** [IlanCosman/tide#333]
Unfortunately long branch names are typically truncated in an unhelpful way.
For example if I have a branch name `topic/sub-topic/feature-name`, the branch may be truncated to `topic/sub-top...`, even though the feature name is the most important part.

Is there a way to prevent truncation of the branch name?

(If no, I will open a feature request)

**Comment by IlanCosman** [comment]
You can effectively disable branch truncation by setting `tide_git_truncation_length` to a very large number.
