### ISSUE TITLE
How do I uninstall the thing?

### ISSUE THREAD

**Issue by raveren** [IlanCosman/tide#334]
It takes ages, AGES to load (I think it's because the totally useless albeit nice NPM+PHP inline version display)
![image](https://user-images.githubusercontent.com/364220/186092609-60b6ce77-11e6-432e-a252-14bc71535c7a.png)
and there's no documentation how to **remove** items.

So for up to around a minute when I open up fish shell I don't even know which directory I'm on, it's hampering my work process, please tell me how to delete it from my system - and I don't use and don't want to use fisher.

**Comment by IlanCosman** [comment]
Sure, to remove all of your plugins (such as Tide and fisher) run `fisher list | fisher remove`.

**Comment by IlanCosman** [comment]
There isn't a simple way then, sorry. Delete all files in your `functions`, `conf.d`, and `completions` directories that have `tide` in the name. Plus `fish_prompt` and `fish_mode_prompt`.

**Comment by raveren** [comment]
okay then, is there a way to remove an item from the Powerline instead? I think the php & version checks are what make Tide lag so much.

**Comment by raveren** [comment]
I can't find it in the wiki and `tide config`

**Comment by IlanCosman** [comment]
Run `_tide_find_and_remove <NAME OF ITEM> <NAME OF LIST>`.

So if `php` was in your `tide_right_prompt_items` you would run `_tide_find_and_remove php tide_right_prompt_items`.

**Comment by raveren** [comment]
I guess it's just some incompatibility with the JetBrains `Terminal` tool window. It still takes a minute+ to load the crumbs AND there's this:
![image](https://user-images.githubusercontent.com/364220/186159507-29a6733d-254b-43e9-87de-9432823ceb6d.png)
Just a FYI, I appreciate your help very much, it's an amazing tool you created, wish it worked for me.

**Comment by raveren** [comment]
I'm on WSL2 by the way and Tide seems to work great on Windows Terminal running WSL
