### ISSUE TITLE
Unexpected string "default" on the right.

### ISSUE THREAD

**Issue by ostanislaw** [IlanCosman/tide#339]
#### Describe the bug

In fresh install&config I see unexpected string "default" on the right. I don't know what it means and how to remove it.

#### Steps to reproduce

1. fresh fish config (remove all from ~/.config/fish/)
2. install fisher
3. fisher install IlanCosman/tide@v5
4. configure

#### Screenshots

![Screenshot from 2022-08-29 09-00-01](https://user-images.githubusercontent.com/52103381/187142647-8194fba3-da25-4d69-a70b-3ac26127a0ca.png)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.5.1
tide version: 5.4.0
term: xterm-256color
os: Ubuntu 22.04
terminal emulator: gnome-terminal
fish startup: 7.73 millis
fisher plugins: jorgebucaran/fisher ilancosman/tide@v5
```

**Comment by IlanCosman** [comment]
That item is the `kubectl` item, which shows your context and namespace.
It runs `kubectl config view --minify --output 'jsonpath={.current-context}/{..namespace}'`.

**Comment by ostanislaw** [comment]
Correct, you are right:
kubectl config view --minify --output 'jsonpath={.current-context}/{..namespace}'
default/

I'm surprised that it's indicated. I have a kubectl configuration but I rarely use that, it's waste of prompt space for me actually.
From my perspective such global indicator should be considered disabled by default, but then most of people wouldn't notice the functionality at all I guess ;)

**How should I permanently disable the kubectl indicator?
Edit some text config?
Set some fish variable?**

I've now only found some configuration for colors of that:
https://github.com/IlanCosman/tide/wiki/Configuration#kubectl

And I see there is example how to add item
https://github.com/IlanCosman/tide/wiki/Configuration#items

So the question is how items should be removed.

Ultimately, as for "ultimate fish prompt" these add/remove items should maybe be considered to be configured by `tide configure` somehow

**Comment by ostanislaw** [comment]
I've found how to see a list of items on right prompt. Then I need to find a way to remove item 12 from this list. And actually the change would unfortunately be reverted after `tide configure`.
```
set --show tide_right_prompt_items
$tide_right_prompt_items: set in universal scope, unexported, with 16 elements
$tide_right_prompt_items[1]: |status|
$tide_right_prompt_items[2]: |cmd_duration|
$tide_right_prompt_items[3]: |context|
$tide_right_prompt_items[4]: |jobs|
$tide_right_prompt_items[5]: |node|
$tide_right_prompt_items[6]: |virtual_env|
$tide_right_prompt_items[7]: |rustc|
$tide_right_prompt_items[8]: |java|
$tide_right_prompt_items[9]: |php|
$tide_right_prompt_items[10]: |chruby|
$tide_right_prompt_items[11]: |go|
$tide_right_prompt_items[12]: |kubectl|
$tide_right_prompt_items[13]: |toolbox|
$tide_right_prompt_items[14]: |terraform|
$tide_right_prompt_items[15]: |aws|
$tide_right_prompt_items[16]: |nix_shell|
```

**Comment by ostanislaw** [comment]
So I found a way to remove single item:
`set -e tide_right_prompt_items[(contains -i kubectl $tide_right_prompt_items)]`
Is it the most recommended way to do that or any other suggestions?
Is it ok to add this example to the wiki page?

Additionally maybe worth mentioning how to list currently set items
`set --show tide_right_prompt_items`

**Comment by IlanCosman** [comment]
Yah, that remove snippet could be a useful addition. 
Ultimately though, these are basic functionalities of Fish variables, and I don't want to be teaching Fish.
E.g. you don't need to run `set --show tide_right_prompt_items`, you can also just run `echo $tide_right_prompt_items`.
