### ISSUE TITLE
Strange offsets on prompt

### ISSUE THREAD

**Issue by ferologics** [IlanCosman/tide#34]
#### Describe the bug

I just installed the prompt and I'm seeing strange offsets / visual defects in terminal. 
Is there anything I overlooked in the setup process other than getting the font?
Do you see how the slanted/pointer shapes are misaligned ever so slightly?

#### Screenshots

<img width="990" alt="image" src="https://user-images.githubusercontent.com/5576161/95904242-8525c580-0d97-11eb-862a-3ff2b0703ce9.png">

#### Environment (please complete the following information)

- Operating System: macOS Catalina 10.15.7 (19H2)
- Output of `tide bug-report`: 
```console
fish, version 3.1.2
tide, version 2.4.0
xterm-256color
```

**Comment by ferologics** [comment]
I have font smoothing disabled but I have checked with/without and haven't spotted a difference.
The screenshot is from Terminal but I tried to check if it's present in iTerm2 without avail.

**Comment by IlanCosman** [comment]
Unfortunately this is a Terminal issue. Powerlevel10k+Zsh has the same problem in Terminal, and Tide in iTerm2 does not have this problem. I can't offer any guidance outside of "use iTerm2. Sorry 😞

**Comment by ferologics** [comment]
Ah, I see, then that's settled. Still the prompt ROCKS! I will stick with the pure one.
