### ISSUE TITLE
The right time lost one char when using WSL

### ISSUE THREAD

**Issue by NextAlone** [IlanCosman/tide#342]
#### Steps to reproduce

1. Set ... to ...
2. Run ...
3. See error

#### Screenshots

![image](https://user-images.githubusercontent.com/12210746/188780368-12ea91ee-3f52-44c5-a8e8-7493dabf8058.png)

#### Environment

Output of `tide bug-report`: 

```text

```

**Comment by NextAlone** [comment]
What useful info can i provice?

**Comment by IlanCosman** [comment]
Please run `tide bug-report` and copy its output into the issue.

**Comment by NextAlone** [comment]
> Please run `tide bug-report` and copy its output into the issue.

➜ tide bug-report
Tide does not work with oh-my-fish installed.
Please uninstall it before submitting a bug report.

**Comment by IlanCosman** [comment]
Duplicate of #310
