### ISSUE TITLE
Parent Directory Quotation

### ISSUE THREAD

**Issue by Henni** [IlanCosman/tide#346]
#### Describe the bug
#323 is a great feature, but seems to have introduced a bug when working in directories with whitespace. This especially surfaces with a ` - ` in `$PWD`.

#### Steps to reproduce

1.  mkdir 'test - test'
2. cd 'test - test'
3. See error

#### Screenshots
```
~/OneDrive - Personal
❯ path is: -/pom.xml: unknown option

~/.config/fish/functions/_tide_item_java.fish (line 2):
    path is $_tide_parent_dirs/pom.xml &&
    ^
in function '_tide_item_java'
        called on line 15 of file ~/.config/fish/functions/_tide_2_line_prompt.fish
in function '_tide_2_line_prompt'
in command substitution
```

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.5.1
tide version: 5.5.0
term: screen-256color
os: MacOS (M1)
terminal emulator: iterm
fish startup: 165.46 millis
fisher plugins: oh-my-fish/plugin-brew oh-my-fish/plugin-extract oh-my-fish/plugin-grc ilancosman/tide@v5 patrickf1/fzf.fish drphil/kubectl-fish-abbr
```

### Additional comments
I suspect this line:
https://github.com/IlanCosman/tide/blob/2613a448912ab63c930932fde25f520f8c0710f7/functions/_tide_parent_dirs.fish#L4
Each joined string should probably be quoted.

**Comment by IlanCosman** [comment]
![2x](https://user-images.githubusercontent.com/6318351/190219405-8ca6814d-c4a2-41ef-a506-e60d0cb7a3e0.gif) I HATE WEIRDLY FORMED DIRECTORIES, STOP MAKING THEM PLEASE

---

Yah I'll fix it when I get a chance 😩
