### ISSUE TITLE
tide not showing up on new terminal windows

### ISSUE THREAD

**Issue by Spleenftw** [IlanCosman/tide#347]
#### Steps to reproduce

After configuring tide with ``fisher install IlanCosman/tide@v5``, prompt is working as intended. If I open a new window, it's my old prompt. I have to reconfigure it to have it working, for every single terminal.

#### Screenshots

We can see there that i opened a new terminal after configuring the prompt (2scd after), and it's not showing.

![Screenshot_(date +%0y%0m%0d_%0H%0M%0S)](https://user-images.githubusercontent.com/57947900/191807482-772d7779-5be8-468e-b853-18edcdfd16eb.png)

#### Environment

Output of `tide bug-report`: 

```
fish version: 3.5.1
tide version: 5.5.1
term: xterm-kitty
os: Debian 11
terminal emulator: Kitty
fish startup: 81.79 millis
fisher plugins: jorgebucaran/fisher jorgebucaran/fish-bax danhper/fish-ssh-agent jorgebucaran/autopair.fish patrickf1/fzf.fish ilancosman/tide@v5
```

**Comment by IlanCosman** [comment]
You have something running on every shell startup that overrides Tide's `fish_prompt`. Likely in your `config.fish`. Perhaps `source`ing something.

**Comment by Spleenftw** [comment]
oh. yeah. lmao. thanks
