### ISSUE TITLE
System appearance compatibility

### ISSUE THREAD

**Issue by ferologics** [IlanCosman/tide#35]
I'm curious if you have any configuration for light/dark mode?
When running the "pure" version and the background is dark the text is also dark color.
Is there a way to make the items more responsive to system appearance?

<img width="229" alt="image" src="https://user-images.githubusercontent.com/5576161/96047388-5251ff00-0e75-11eb-86f4-e8c87a0498e7.png">

**Comment by IlanCosman** [comment]
Tide doesn't have separate configs for light and dark backgrounds, though that might be something I'd look into adding. As for making Tide responsive to the system appearance, that is unlikely to be possible. As far as I know terminal colors aren't exposed to shell, and therefore can't be accessed by Tide. I've never heard of a prompt changing depending on the terminal colors.
It might be possible through some convoluted Xterm escape codes or whatnot, but isn't worth the energy, as people rarely change their terminal colors, and can adapt their prompt to fit them.

I'd recommend using the _lean_ prompt style as it shows significantly more information, and uses more vibrant colors. _Pure_ style is meant to provide a comfortable experience for users coming from that specific prompt.

**Comment by ferologics** [comment]
If I use the rainbow then the background for the info views makes everything legible. I’ll fiddle around with Lean mode too, thx for the tip again 🙏
