### ISSUE TITLE
How git prompt show upstream auto ?

### ISSUE THREAD

**Issue by KoryChiu** [IlanCosman/tide#354]
I don't want to go to my project directory and execute `git fetch` command every time.

**Comment by KoryChiu** [comment]
Is it possible to have this variable like the following :

```
function fish_prompt
    # ...
    set -g __fish_git_prompt_showupstream auto
    printf '%s %s$' $PWD (fish_git_prompt)
end
```
https://fishshell.com/docs/current/cmds/fish_git_prompt.html

**Comment by IlanCosman** [comment]
What information are you missing in Tide? How far behind/ahead you are from the remote is already shown.

**Comment by KoryChiu** [comment]
Is it possible to cd the project directory to display the remote behind/ahead , without execute `git fetch` command  again?
