### ISSUE TITLE
diff: unrecognized option `--old-line-format' Bug since upgrading to MacOS Ventura

### ISSUE THREAD

**Issue by eddyekofo94** [IlanCosman/tide#358]
#### Describe the bug
I keep getting this error on my prompt 

#### Screenshots
<img width="964" alt="image" src="https://user-images.githubusercontent.com/12385031/199525360-8978ad58-15eb-440c-8a96-028dd3c091dc.png">

#### Environment
<img width="747" alt="image" src="https://user-images.githubusercontent.com/12385031/199528228-86836007-d23a-4ffd-88a5-3a74929bc5d2.png">

**Comment by IlanCosman** [comment]
Not a Tide bug. Tide doesn't use `diff` anywhere.

**Comment by eddyekofo94** [comment]
> Not a Tide bug. Tide doesn't use `diff` anywhere.

It's no longer there when I uninstall tide 👀
