### ISSUE TITLE
Spacing after the pointy end of the prompt

### ISSUE THREAD

**Issue by ferologics** [IlanCosman/tide#36]
#### Describe the solution you'd like

I'd like to add a teeny tiny bit of padding after the > prompt
At the moment the cursor/indicator is very close to the tip of the prompt and it looks off.
Is there a way to make some space between so that the tip doesn't touch/hug the text?

#### Additional context

<img width="171" alt="image" src="https://user-images.githubusercontent.com/5576161/96050390-d312fa00-0e79-11eb-806b-7b83b7a62d15.png">

**Comment by IlanCosman** [comment]
You can add a space with `set tide_left_prompt_suffix $tide_left_prompt_suffix' '`, but there is no way to increase the spacing by a slight amount.

**Comment by ferologics** [comment]
Yup, this is what I wanted. Thank you 🙏
