### ISSUE TITLE
Custom items evaluate after inbuilt items

### ISSUE THREAD

**Issue by Russell-Accurx** [IlanCosman/tide#361]
#### Describe the bug

I'm trying to create a custom item that has knowledge of my company's monorepo project structure, so I can show a short description of the location instead of the output of `cwd`, which is not as helpful when in a deeply nested project structure (it collapses a lot of the previous path, but I just don't want it to show at all).

I've got something basic working, but it's slow, because it seems to only run once the existing, inbuilt items - in particular the `git` item - have already completed. It's possible I may be doing something wrong - is this expected, or should the items be run in parallel? Or in the order in which they appear in the prompt?

#### Steps to reproduce

1. Create a custom item that does something quick and inexpensive, e.g.

```fish
function _tide_item_custompwd
   echo $PWD |
   sed -e "s|$HOME|~|" |
   sed -e "s|~/Code/||"
end
```
2. Set it as part of your prompt: `set -U tide_left_prompt_items pwd git newline custompwd character`
3. `cd` into a git repo directory
4. See that your custom item isn't run until after the git item is run

#### Screenshots

https://user-images.githubusercontent.com/116583129/203778820-8cc540fb-c2c8-4c9a-bc02-76f435c14514.mov

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.5.1
tide version: 5.5.1
term: xterm-256color
os: Mac 13.0.1 (22A400)
terminal emulator: iTerm2
fish startup: 34.18 millis
fisher plugins: jorgebucaran/fisher ilancosman/tide@v5
```

**Comment by IlanCosman** [comment]
Items are indeed run serially in the order the appear in the prompt. But this doesn't really matter because the prompt is only updated when all items have finished running.

**Comment by Russell-Accurx** [comment]
It's less than ideal, because as you can see from the video above, which includes both the built in `pwd` item and my custom one, the `pwd` item updates immediately, showing the correct directory, while the `custompwd` waits till git is done. This is less than ideal because it means the prompt shows the wrong directory for a while, and because the directory path is variable length while the git branch name stays consistent, it means the prompt jumps around after I've already started typing. Is there any workaround I might be able to use to get the directory name of a custom command to update before the git one does? Thanks!

**Comment by IlanCosman** [comment]
Unfortunately not. I agree it would be nice for every item to run in parallel, but sadly that's not possible with fish right now :(

**Comment by Russell-Accurx** [comment]
no worries, thank you!
