### ISSUE TITLE
Checking settings into dotfiles

### ISSUE THREAD

**Issue by patrickf3139** [IlanCosman/tide#37]
Hi @IlanCosman, how do you recommend checking in our tide prompt settings to our dotfiles?

**Comment by IlanCosman** [comment]
That's a good question. To a certain extent, I don't. The configuration wizard already allows for selecting most of what people want to customize. If you're reinstalling your dotfiles, you can just go through the configuration wizard again, it only takes a few seconds.

Some people, like yourself I'd guess, want to do more advanced configuration. For them I'd recommend having a basis in the configuration wizard, and then either an install script like

```fish
set -U tide_var1 foo
set -U tide_var2 bar
```

or a startup conf.d snippet that sets variables globally. 

If you really want your configuration to be entirely locked in stone, you can get your current tide configuration with `tide bug-report -v`. Copy that into your install script/conf.d snippet and add the appropriate `set`s before each key value pair. `tide bug-report` also lists the fish version, tide version, and $TERM even when using `-v`, so you'll have to delete those.

I've considered adding a `tide export` command for situations like this, but I don't it's necessary. I really think the best options are 
1. Just use the configuration wizard - good for 90% of people
2. Use the configuration wizard and then change the few variables you want. - good for another 8%

Hope that clears things up for you 😄 If you have any thoughts on this I'd love to hear them.

**Comment by patrickf3139** [comment]
Thanks for the in-depth explanation! I think I'll just add code to set the universal variables to my install script. I wouldn't mind just running `tide configure` again because it does only take 10 seconds. However, I have greatly customized my items, e.g. removing git because I regularly work on super large git repos.
