### ISSUE TITLE
"* custom" field added in the right prompt - how can I remove it

### ISSUE THREAD

**Issue by vfiftyfive** [IlanCosman/tide#370]
Hi,
After installing and configuring tide on my mac with homebrew, it looks like I've got an extra item on the right prompt, as displayed below. I'm running fish 3.5.0 and tide 5.5.1
![image](https://user-images.githubusercontent.com/7715763/212993537-e0b3c7ec-b490-43d4-b170-84ef041a091c.png)

How can I remove "* custom"?

Thank you,

Nic

**Comment by IlanCosman** [comment]
That's the kubectl item, you can remove it with `_tide_find_and_remove kubectl tide_right_prompt_items` and then restart your shell.
