### ISSUE TITLE
Constant changes to fish_variables makes versioning difficult with Tide in use

### ISSUE THREAD

**Issue by amonshiz** [IlanCosman/tide#374]
Hi! I'm really enjoying using Tide. However, I have one issue: I use git to version my fish configuration, including `fish_variables`. I made a change to my configuration and went to commit the changes and noticed that every time I staged changes there would be a new change in `fish_variables` on a `_tide_prompt_<pid>` line. This is was really surprising.

How can I effectively version `fish_variables` while using Tide?

Thank you!

**Comment by IlanCosman** [comment]
> How can I effectively version fish_variables while using Tide?

You can't, sorry. I'd recommend using an install script with `set -U` invocations instead of saving the fish_variables file itself.
