### ISSUE TITLE
Spaces/SOH in fish_variables

### ISSUE THREAD

**Issue by adamhl8** [IlanCosman/tide#376]
I don't think this is an issue with tide or fish (not sure if it's an "issue" at all), but maybe someone can help me understand what's going on here.

I wanted to remove `aws` from my right prompt so I did this:

```
set -U tide_right_prompt_items (echo $tide_right_prompt_items | string replace 'aws ' '')
```

That seemingly works fine. However, upon restarting fish I get hit with this error:

```
fish: Unknown command: '_tide_item_status cmd_duration context jobs node virtual_env rustc java php chruby go kubectl toolbox terraform nix_shell crystal time'
~/.config/fish/functions/_tide_1_line_prompt.fish (line 11):
        _tide_item_$item
        ^~~~~~~~~~~~~~~^
in function '_tide_1_line_prompt'
in command substitution
```

Looking at `fish_variables` before and after setting the variable, I can see that `tide_right_prompt_items` (and `_tide_right_items`) went from
```
SETUVAR tide_right_prompt_items:status\x1ecmd_duration\x1econtext\x1ejobs\x1enode\x1evirtual_env\x1erustc\x1ejava\x1ephp\x1echruby\x1ego\x1ekubectl\x1etoolbox\x1eterraform\x1eaws\x1enix_shell\x1ecrystal\x1etime
```
to
```
SETUVAR tide_right_prompt_items:status\x20cmd_duration\x20context\x20jobs\x20node\x20virtual_env\x20rustc\x20java\x20php\x20chruby\x20go\x20kubectl\x20toolbox\x20terraform\x20nix_shell\x20crystal\x20time
```

So the SOH characters (`\x1`) were replaced with spaces (`\x20`).

If I instead do (note that I'm using normal spaces here)
```
set -U tide_right_prompt_items status cmd_duration context jobs node virtual_env rustc java php chruby go kubectl toolbox terrafor
m nix_shell crystal time
```

This works fine. What's strange to me is that if I look in `fish_variables` after running this, it saved using `\x1` instead of `\x20`.

A couple questions:
- What are the purpose of the SOH (`\x1`) characters in `fish_variables`? (as opposed to spaces)
- Why does my command substitution cause the variable to be saved with spaces? Or I suppose better question, why does typing it out (with normal spaces) save with SOH characters?

Any help is appreciated. Thanks!

**Comment by faho** [comment]
>I don't think this is an issue with tide or fish (not sure if it's an "issue" at all)

Absolutely nothing to do with tide, and not a bug in fish.

>What are the purpose of the SOH (\x1) characters in fish_variables? (as opposed to spaces)

The SOH here is the element delimiter.

When you store a list like `set -U foo 1 2 3`, it has three separate elements - "1", "2" and "3". So these are stored as `1\x12\x13`.

So if you had `set -U foo "bar baz"` it would be saved as `bar\x20baz`, and reconstructed as one element of `bar baz`, if you had `set -U foo bar baz` it would be stored as `bar\x1baz`.

>Why does my command substitution cause the variable to be saved with spaces?

```fish
set first (echo foo bar)
set second foo bar

set -S first second
```

This prints:

```
$first: set in global scope, unexported, with 1 elements
$first[1]: |foo bar|
$second: set in global scope, unexported, with 2 elements
$second[1]: |foo|
$second[2]: |bar|
```

Fish only split command substitutions on newlines, not spaces. Your command prints one line, so the variable gets one element.

**Comment by adamhl8** [comment]
Ahh, makes perfect sense, thanks!

With that it mind it seems like a good solution in this case is to just split the string on spaces:

```
set -U tide_right_prompt_items (echo $tide_right_prompt_items | string replace 'aws ' '' | string split ' ')
```

**Comment by faho** [comment]
>With that it mind it seems like a good solution in this case is to just split the string on spaces:

I am fairly certain you can do better - you want to remove the "aws" item from $tide_right_prompt_item? Try this:

```fish
set -l ind (contains -i -- aws $tide_right_prompt_items)
and set -e tide_right_prompt_items[$ind]
```

This has the advantage that it doesn't split and resplit and won't we confused if you had an element "jaws".

**Comment by adamhl8** [comment]
That's definitely a lot better. Thanks again.
