### ISSUE TITLE
Add setting to configure if the git branch is shortened from beginning or from end

### ISSUE THREAD

**Issue by primeapple** [IlanCosman/tide#377]
#### Is your feature request related to a problem? Please describe

I prefix my git branches with the ticketnumber I'm working on. So most of the time it looks like `GH-302-add-nice-button-layout`. Currently what happens is that the branch is shortened to `... button-layout`. This is bad, because I would like to remember the number and not the words at the end.

#### Describe the solution you'd like

I'd like to have an option like `$tide_git_truncat_end` that is by default unset.
If it is set, the truncation happens from the end, otherwise from the start.

#### Additional context

The implementation which part of the branch should be truncated changed before in this commit: https://github.com/IlanCosman/tide/commit/ae7aa9bb470881053e7cef4ff6a3440fbdb51d96

This looks like a good first issue. I'm open in helping solve this.

**Comment by IlanCosman** [comment]
Yah this'll be coming in the next version of Tide, whenever that is 👍

**Comment by primeapple** [comment]
I'll try to open an PR, let's see.

**Comment by primeapple** [comment]
Added two PRs. Review would be nice :)

**Comment by IlanCosman** [comment]
Done. This is the new default. The old default can be achieved by setting the new `tide_git_truncation_strategy` variable to `l` :)
