### ISSUE TITLE
"is-inside-git-dir" doesn't show up in prompt, intentionally?

### ISSUE THREAD

**Issue by Markuzcha** [IlanCosman/tide#379]
Is saw in the commit history that this was "brought back", but how ?
When I enter the .git dir nothing changes.

The vanilla fish git module shows "GIT_DIR!" instead of branch name inside the .git dir and probably "BARE" inside the same.

I wrote a new item for myself for the moment...

**Comment by IlanCosman** [comment]
https://github.com/IlanCosman/tide/commit/6e10b89fc0b486fe307b8ada71baa56d2fd90811 was fix for git submodules. There isn't currently any plan to have a warning that you are in the `.git` directory.
