### ISSUE TITLE
Config Tide via Config file

### ISSUE THREAD

**Issue by DeeGeeMan** [IlanCosman/tide#38]
Allow users to change the prompt via JSON config file.  If I need to change on feature, I have to go through the `tide configure` process again.

It would be helpful if `tide configure` save the settings to JSON config file.  Therefore, a new command `tide restore --configFile` can be use to reimport Fish variables.

**Comment by IlanCosman** [comment]
Hi @DeeGeeMan, thanks for opening this issue 😄 You don't _need_ to go through `tide configure` again to change features, though it's often the most convenient way. As with nearly everything in fish, Tide uses variables to to control its features. 

For example, if you wanted to enable the prompt frame on the right, you would use `set --universal tide_right_prompt_frame_enabled true`. Or if you wanted to add the `git_prompt` item to the beginning of your left prompt, you would use `set --prepend tide_left_prompt_items git_prompt`.

A related issue is https://github.com/IlanCosman/tide/issues/37.
