### ISSUE TITLE
out of date readme

### ISSUE THREAD

**Issue by CouldBeThis** [IlanCosman/tide#383]
#### Describe the bug

The readme states in part:

> ### System Requirements
> 
> - The **latest** version of Fish, currently 3.5.1. [...]
> 
> Install with Fisher:
>
> ```console
> fisher install IlanCosman/tide@v5
> ```

This is out of date. The wiki page [Fish version compatibility](https://github.com/IlanCosman/tide/wiki/Fish-version-compatibility) *does* have the correct information. 

Since as the wiki suggests, everyone should be running the current version of `fish`, perhaps getting rid of the version specification in the suggested command would be better? That way it does not need to be updated.

**Comment by IlanCosman** [comment]
Sure, thanks :)
