### ISSUE TITLE
pwd not refresh when change dir by alt + left/right

### ISSUE THREAD

**Issue by NextAlone** [IlanCosman/tide#392]
#### Steps to reproduce

1. Press alt + left or alt + right to call prevd or nextd
2. Pwd not refresh as expected
3. See error

#### Screenshots

![image](https://user-images.githubusercontent.com/12210746/227736859-d284359f-1a11-4fe2-9beb-3025f04e5e4b.png)

#### Environment

Output of `tide bug-report`: 

```text

```

**Comment by IlanCosman** [comment]
I can't reproduce this with fish 3.6.1 and Tide master on either MacOS or Arch Linux.

**Comment by NextAlone** [comment]
Sorry, I am unable to replicate the issue neither on `fish, version 3.6.1-265-gb8189da01`. Please accept my apologies for any inconvenience caused.
