### ISSUE TITLE
Theme looks weird.

### ISSUE THREAD

**Issue by FormalSnake** [IlanCosman/tide#405]
I installed: https://github.com/catppuccin/fish using fisher.

![image](https://user-images.githubusercontent.com/90651091/235533569-4c6e7426-b3af-4887-80ed-25b006332472.png)

Is this the theme's fault? Or are the colours wrong?

**Comment by lumynou5** [comment]
If you mean Tide's colors don't match to the theme, I think you can set the colors manually. Try `set -U tide_git_bg_color DBCD9D` for example.

**Comment by FormalSnake** [comment]
does it just use hex colours? And how do I determine what the colour gets put on?
like tide_git_bg_color

**Comment by lumynou5** [comment]
> 

I think this [list](https://github.com/IlanCosman/tide/blob/main/functions/tide/configure/configs/rainbow.fish) contains all the variables.

**Comment by FormalSnake** [comment]
Thanks! This should be in the readme
