### ISSUE TITLE
how do i uninstall tide?

### ISSUE THREAD

**Issue by cbpanchal** [IlanCosman/tide#406]
I have tried but not able to do

**Comment by IlanCosman** [comment]
If you installed with fisher, then it'd be `fisher remove ilancosman/tide@v5`. If you installed with the install snippet, then you'll have to do it manually by removing tide files in your `~/.config/fish`.

**Comment by cbpanchal** [comment]
@IlanCosman  so you mean need to remove all the tide files manually?

**Comment by SurajMeena** [comment]
there should be two folders named `completions` and `functions` you will need to remove both folders to uninstall it if you have installed tide using install script manually

**Comment by KnifeFed** [comment]
> remove both folders

Do _not_ do that if there's anything else in those folders other than files with `tide` in their name. Only remove those files.

**Comment by SubordinalBlue** [comment]
No.

Removing all tide files from `.config/fish/` after using the "manual" install results in a fish prompt so broken one has to to open a terminal with a different shell to delete `functions/fish_prompt.fish`.

Would recommend _not_ including the "manual" method in the README.
