### ISSUE TITLE
Tide not working on 2nd shell

### ISSUE THREAD

**Issue by 7i7o** [IlanCosman/tide#408]
I have installed Tide via fisher install, then run tide configure, and it works in the shell I installed it.

Whenever I close that shell or even starting another, tide is gone and I have my default prompt. Even if I run tide configure in my second shell, nothing changes.

**Comment by IlanCosman** [comment]
Somewhere, for example in your `~/.config/fish/config.fish` file or `~/.config/fish/conf.d` directory, you are overwriting the `fish_prompt` function.

**Comment by 7i7o** [comment]
Thanks! I had forgotten to disable starship in config.fish
