### ISSUE TITLE
BrokenPipeError on hitting enter/return quickly a few times on M1 mac book pro

### ISSUE THREAD

**Issue by krisctl** [IlanCosman/tide#409]
#### Describe the bug

With Tide installed and configured on my M1 MacBook Pro, when I click enter/return a few times quickly, I see the following error:

│ main  Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>0:22:23 
BrokenPipeError: [Errno 32] Broken pipe

#### Environment

MacOS, Apple Macbook M1 Pro

**Comment by pvsmpraveen** [comment]
This is true in my linux as well

**Comment by federicotorrielli** [comment]
This is not due to tide but it's a known fish+anaconda bug
