### ISSUE TITLE
Is anyone else having this issue

### ISSUE THREAD

**Issue by XxHiroTTVxX** [IlanCosman/tide#411]
I install tide and configure it but the prompt doesn't line up properly I'm using the alacritty terminal
![idk](https://github.com/IlanCosman/tide/assets/101534563/b78376d9-7765-427a-9255-adbd1aa350c8)

**Comment by IlanCosman** [comment]
It means your font isn't patched well enough. Try the recommended font, or I think a newer version of the nerd font should work. Fira Code Nerd Font works.
