### ISSUE TITLE
Fonts are fine, but not monospaced - is that creating spacing issue?

### ISSUE THREAD

**Issue by cekvenich2** [IlanCosman/tide#413]
<img width="174" alt="Screenshot 2023-06-04 at 1 37 01 PM" src="https://github.com/IlanCosman/tide/assets/76924532/404b429c-fcc9-4e30-9b6c-a0d9299388f8">

See how icons are half?
Am I required to use monospaced font?
HELP.

**Comment by IlanCosman** [comment]
Yes you must be using a monospace font. Any nerd font _should_ work, but try it with the recommended just to be sure.

**Comment by cekvenich2** [comment]
Let me try my font but mono. The font you recommend does not do
'ligatures', eg => should be one char in 'my' nerd font.  (Fira)
