### ISSUE TITLE
Release new tag

### ISSUE THREAD

**Issue by primeapple** [IlanCosman/tide#417]
Hi @IlanCosman ,

how do you think about releasing a new version?
There were multiple bugfixes since the last one. It is important, since the preferred install via `fisher` installs only the latest tag. So it would be nice of you to release one :)

Thanks for reading and considering

**Comment by IlanCosman** [comment]
Damnit I forgot. Honestly this week is a really bad time since I'm traveling. I'll get it done when I get back on the weekend. Sorry 😞

**Comment by primeapple** [comment]
I'll remind you :)

**Comment by IlanCosman** [comment]
Done! A little late, but on a good day 🦅 🇺🇸 😄
