### ISSUE TITLE
error installing and configuring

### ISSUE THREAD

**Issue by aldopareja** [IlanCosman/tide#418]
#### Steps to reproduce

I'm following the usual things:
1. download the recommended fonts and putting them in `.local/shared/fonts/`
2. install fisher with `curl -sL https://raw.githubusercontent.com/jorgebucaran/fisher/main/functions/fisher.fish | source && fisher install jorgebucaran/fisher`
3. `fisher install IlanCosman/tide`

then when it asks to configure it gives me an error.

this is it:

<img width="912" alt="image" src="https://github.com/IlanCosman/tide/assets/7622817/e6968860-a866-492f-b152-8c680b7dce46">

**Comment by IlanCosman** [comment]
Your fish version is too old.

**Comment by aldopareja** [comment]
indeed, fixed with:

```
sudo apt-add-repository ppa:fish-shell/release-3
sudo apt update
sudo apt install fish
```
