### ISSUE TITLE
Fish hangs when there are a lot of subdirectories due to inefficient pwd truncation in _tide_pwd

### ISSUE THREAD

**Issue by kaysond** [IlanCosman/tide#420]
### Describe the bug

**Context:** I have a very large "project" directory mounted over nfs with 4000+ subdirs. Each of those subdirs, including the particular one I am working in can have several hundred subdirs themselves, and so on, going down 10+ levels.

**Bug:** Because of the way tide truncates the path (using a `while` loop around a glob), it's checking directory contents potentially hundreds or even thousands of times. Compounded with the generally slow performance of nfs, this means the _tide_pwd call hangs for minutes. Because it's not run in the background shell, it causes fish to freeze.

#### Issue 1: `_tide_pwd` gets called whether you have pwd as an item or not
https://github.com/IlanCosman/tide/blob/ff88ca7182520b6cbde35b51f55fa79ddb1f3829/functions/fish_prompt.fish#L52

https://github.com/IlanCosman/tide/blob/ff88ca7182520b6cbde35b51f55fa79ddb1f3829/functions/fish_prompt.fish#L80

This is really only a problem because it makes debug hard. I one-by-one removed each tide item, and nothing fixed the hanging, so it took quite a bit of digging to sort out the issue.

#### Issue 2: `_tide_pwd` gets called outside of the background shell

Same code lines as above. Since it's not in the background, fish completely freezes, instead of the prompt just not getting updated.

#### Issue 3: glob in while loop

https://github.com/IlanCosman/tide/blob/ff88ca7182520b6cbde35b51f55fa79ddb1f3829/functions/_tide_pwd.fish#L30

Because the glob is in a while loop, fish is grabbing the directory contents for every iteration in the loop. Ideally, fish or the filesystem would cache the results but that doesn't seem to be the case. This means that when the minimum non-ambiguous truncation is very long, it takes forever because it's checking every directory's contents multiple times.

### Steps to reproduce

1. Create a deeply nested directory structure with thousands of subdirectories in each directory, with very similar and long names
2. Run `_tide_pwd` with a very big `min_cols` to trigger truncation

### Environment

Output of `tide bug-report`: 

```text
fish version: 3.6.1
tide version: 5.6.0
term: xterm-256color
os: SLES 12
terminal emulator: Windows Terminal
fish startup: 31.60 millis
fisher plugins: jorgebucaran/fisher danhper/fish-ssh-agent patrickf1/fzf.fish jorgebucaran/autopair.fish ilancosman/tide@v5
```

**Comment by kaysond** [comment]
Happy to submit a PR for this, if you're open to it. Not sure why the pwd is currently not in the background job (I'm guessing so you can get the length of the rest of the prompt?) but it could be moved in there. Then it would just be a matter of doing the glob once and saving it in a variable to avoid the repetition.

I'd also like to request, in addition to the bugfix, that this "smart" truncation (meaning the disambiguating) be put behind an option that's on by default. That way people like me could turn it off and not have any globs run, but you just always get a single character per directory if its truncated.

**Comment by IlanCosman** [comment]
Thanks for your great writeup! I'm absolutely open to improving this.

I don't want to move the pwd to the background shell, because it is by far the most important element of the prompt, and should never be slowed down by, e.g. a long git call.

I am definitely open to improving performance. Initial idea would be to run the glob once and then use string match I suppose? 

If the performance is not good enough even with the improvements, then I'll be open to a configuration switch here.

**Comment by kaysond** [comment]
> I don't want to move the pwd to the background shell, because it is by far the most important element of the prompt, and should never be slowed down by, e.g. a long git call.

Ah! That definitely makes sense.

> Initial idea would be to run the glob once and then use string match I suppose?

Yeah that should be much faster since it only hits the disk once per directory piece

Happy to help implement and/or test. Let me know!

**Comment by IlanCosman** [comment]
@kaysond I just commited a single-glob version to the `dev` branch. Could you test it out on your machine?

**Comment by kaysond** [comment]
@IlanCosman 

Old:
![image](https://github.com/IlanCosman/tide/assets/1147328/e4f87107-9c5d-4e7f-8d76-5cafd9ad0255)

New:
![image](https://github.com/IlanCosman/tide/assets/1147328/76e24283-b03f-4db0-91ee-0755e3cc2ace)

Eliminating all the extra globbing definitely has helped. From my testing I think there is some caching that happens that was speeding up the subsequent globs, which is why it didn't drop a lot. The very first glob still takes 120s on my machine! Unfortunately the caching doesn't seem to persist between command calls....

I raised an issue for the poor globbing performance, since that's obviously not tide-related: https://github.com/fish-shell/fish-shell/issues/9891

For the sake of completeness, I tried a version of the function where it just uses the first letter of every dir, and it runs within 1s, since it just uses pwd. I would really appreciate an option that turns off the globbing!

**Comment by IlanCosman** [comment]
@kaysond How does the single-glob tide perform with the fish update?

**Comment by kaysond** [comment]
I just spent an hour trying to build it and wasn't (yet) successful. Unfortunately I work on a machine with an old OS and no internet access, so things are a pain. Next thing I need to do would be compile a newer version of g++ and its dependencies which will take some time.

Judging by the comment in that fish issue that it should be on par with `ls`, I think I'd still be looking at a worst case of 10-15s, since that's how long a stale `ls` takes.

I'll try to tackle the g++ compilation Monday, since I'll have to get that all set up for the next version of fish anyway.

**Comment by IlanCosman** [comment]
Ok. To be honest, I'm leaning away from adding a simplified, no-globbing pwd. 

Simply put, there have been no other complaints about performance here, and your system is just kind of ridiculous. `ls` taking 10 seconds is insane. I think your situation is just such an outlier than it's not worth the effort of supporting.

I don't want to ignore your problem but creating a second mode of operation is also not something I really want to do. If there are more complaints I will reconsider but for now I'm sorry to say Tide might not be for you 😞

**Comment by kaysond** [comment]
> Ok. To be honest, I'm leaning away from adding a simplified, no-globbing pwd.
> 
> Simply put, there have been no other complaints about performance here, and your system is just kind of ridiculous. `ls` taking 10 seconds is insane. I think your situation is just such an outlier than it's not worth the effort of supporting.
>
> I don't want to ignore your problem but creating a second mode of operation is also not something I really want to do. If there are more complaints I will reconsider but for now I'm sorry to say Tide might not be for you 😞

It is ridiculous indeed, but unfortunately not uncommon in enterprise setups. Lucky for me, tide works great at home! (and most directories at work too actually).

I get it. But also I don't think you need a big change to support fixed single-letter truncation. From what I was thinking, you could just wrap these lines in a conditional that tests the value of the config var. I can give it a shot on Monday (and submit a PR, if you want). Worst case I can also just keep my own fork, but I wouldn't be surprised if other people want the option too. Other prompts do the "dumb" truncation by default, since its shorter.

LMK...

https://github.com/IlanCosman/tide/blob/69c3c24e3c3a004da56a3c829592194c2d96a23b/functions/_tide_pwd.fish#L31-L35
