### ISSUE TITLE
Is it possible to force synchronous update of a specific prompt section or entire prompt?

### ISSUE THREAD

**Issue by yanshay** [IlanCosman/tide#424]
I want to have prompts time show when commands were actually executed.
To achieve this I did the following:

`bind -M insert [ repaint execute
`

So upon key press (my plan to eventually use enter) the prompt will repaint so time will be updated and command will be executed.

This work with Starship but not with Tide, my guess because of the async execution.
Is there a way to force tide (maybe by setting some variable temporarily) to run in sync, at least the time section?
Or maybe some way to wait after the repaint to the end of the prompt async redraw?
BTW - I think such behavior would be great to have built in with tide.

**Comment by IlanCosman** [comment]
I've never seen this workflow. Why do you want this?

1. If it's to view how long a command took, we already have the `cmd_duration` item
2. If it's to have a history, there's the `history` builtin or better yet a nice viewer like https://github.com/PatrickF1/fzf.fish
3. If it's to have a nice scrollback, then yah it's a bit nicer than just pressing <kbd>enter</kbd> again. But you're exchanging the almost as important information about when the command ended (which actually isn't retrievable from history).

**Comment by yanshay** [comment]
Many times I need to know when I issued various commands to tell when they were executed and at to what time the results shown are valid.
Currently I need to look at the following prompt to know when the results are valid, if its a lengthy output it isn't easy, and if it is a long running command I don't have a reliable way to know when it started because the start time is actually the time the command previous to that ended.
With this approach, together with cmd_duration I can deduce all information I need. I have both start time execution length for every command. Otherwise I have the execution end at the end of the results and execution length which is more complex to use.

**Comment by yanshay** [comment]
I looked deeper into the code and managed to get this to work.
Writing it here in case someone is interested:

```
function fish_user_key_bindings
    bind -M insert \r my_func
    bind -M default \r my_func
end


function my_func
    set -l prompt_var _tide_prompt_$fish_pid
    set _tide_prompt_$fish_pid (string replace -r '\d\d:\d\d:\d\d' (date +$tide_time_format) $$prompt_var)
    # set -g _tide_repaint
    # commandline -f repaint
    commandline -f execute
end
```
Initially I thought I'd need `set _tide_repaint` and the `commandline -f repaint`, but it works w/o that. 
Leaving it there remarked in case it doesn't under some situations.
