### ISSUE TITLE
Tide outputs all logs, making it unusable

### ISSUE THREAD

**Issue by GeekOfTheWild** [IlanCosman/tide#426]
#### Tide outputs all logs, making it unusable

I have installed Tide using Fisher, but whenever I hit enter, Tide outputs all of its logging information to stderr. I know it's stderr, because running FIsh using fish 2> /dev/null will stop all of the output, but also stop all errors, which can be quite annoying. A remember solving this a few days ago, when I first switched to Tide, but I have since broken my install (Bedrock Linux)

#### Steps to reproduce

1. Install Tide using Fisher
2. Run Fish
3. See large amounts of logging information

#### Environment

Output of `tide bug-report`: 

fish version: 3.6.1
tide version: 5.6.0
term: alacritty
os: Bedrock 0.7 poki (Artix + nothing else yet)
terminal emulator: Alacritty
fish startup: [I] wallpaper: Set the new wallpaper.
fisher plugins: ilancosman/tide@v5

**Comment by IlanCosman** [comment]
Tide doesn't have any logging information. My guess is you're exporting the `fish_trace` variable somehow, which is causing the fish subshell that Tide spawns to display everything. You can see which variables are exported using `set --export`.

**Comment by GeekOfTheWild** [comment]
Okay, so turns out it was Pywal that was doing all of that logging, so in my config.fish I changes it to wal -R 2> /dev/null. The other bit was it trying to find omf/init.fish, so I just created that and added "Echo, "Hello, World!"". I don't know why Pywal wasn't logging when I was using Starship, but it was, so that problem's fixed. Thanks for the pointers!
