### ISSUE TITLE
Theme. Is it possible to keep this behaviour like this:

### ISSUE THREAD

**Issue by Mekam1** [IlanCosman/tide#427]
<img width="1277" alt="Screenshot 2023-07-29 at 02 29 09" src="https://github.com/IlanCosman/tide/assets/139581582/e5ed3b90-5e70-4ee3-9721-501ca1a215f2">
Is it possible to keep this behaviour? 
I was playing around with colours and managed to get frame and arrow at the same time but it works only ones before reloading.

**Comment by IlanCosman** [comment]
Yah just add the `character` item to `tide_left_prompt_items`.

**Comment by Mekam1** [comment]
Thank you for help, but unfortunately when Im restarting it with the wizard, I'm getting this bug
<img width="1292" alt="Screenshot 2023-07-29 at 09 15 59" src="https://github.com/IlanCosman/tide/assets/139581582/3be81e45-5dd3-4890-a0a6-80c831e46299">
Probably I need to restart it manually, however I don't know how to do it

**Comment by IlanCosman** [comment]
> Thank you for help, but unfortunately when Im restarting it with the wizard, I'm getting this bug

I'm not sure what you mean by "restarting it with the wizard".

Go through the wizard, and select the prompt frame on the left option.

Finish the wizard. Then, run `set --append tide_left_prompt_items character`.

Restart the shell. You should now have what you want.

**Comment by Mekam1** [comment]
thank you! 🤍
