### ISSUE TITLE
Is there a way to override the path (pwd) so that it displays only the last/current folder?

### ISSUE THREAD

**Issue by well1791** [IlanCosman/tide#428]
I've tried to understand how `tide_left_prompt_items` works but still don't get it, I even tried to create my own custom function called `tide_items_my_prompt`  so to override the items I'll do `set tide_left_prompt_items os my_pwd git newline character` but it doesn't seem to work as I expected.

Just to be clear, I'm looking for a way to only display the last/current folder, nothing else.

**Comment by IlanCosman** [comment]
Sorry, no. The PWD is the most critical part of the prompt so it is baked in in various ways.

The items list is simple to use though. You'd have a function like so:

```fish
function _tide_item_my_item
    _tide_print_item my_item hello
end
```

and add it to the items list as `my_item`.

**Comment by well1791** [comment]
I'll leave this comment for future reference, since I'm looking for a way to display just the parent and current folder.

This code change worked for me

```diff
// https://github.com/IlanCosman/tide/blob/main/functions/_tide_pwd.fish#L10
-if set -l split_pwd (string replace -r '^$HOME' '~' -- \$PWD | string split /)
+if set -l split_pwd (string replace -r '^$HOME' '~' -- \$PWD | string split /)[-2..]
```

Notice the `[-2..]` at the end of the line, hope it helps to other people
