### ISSUE TITLE
[Question/Workaround] Make cursor shape changable in vi mode

### ISSUE THREAD

**Issue by ruslanSorokin** [IlanCosman/tide#442]
# Environment

fish version: `fish, version 3.6.1`
wezterm version: `wezterm 20230712-072601-f4abf8fd`
tide version: `tide, version 5.6.0`
OS version: `macOS 11.6.4`

# Question

I'm encountering an issue with the cursor - its shape does not change either in vanilla fish or with the tide plugin.

### Vanilla mode
<img width="360" alt="image" src="https://github.com/IlanCosman/tide/assets/88016602/d97bafc1-13b5-48d8-a7c1-4b742efa3640">
<img width="360" alt="image" src="https://github.com/IlanCosman/tide/assets/88016602/cbea2d7b-94f3-42fb-ad3d-adfb0e52383f">

`_` is the default shape of the wezterm terminal.

---

I've found a [workaround](https://github.com/fish-shell/fish-shell/issues/7458#issuecomment-756295678) that works for me in the vanilla mode:

### Vanila mode with custom `fish_mode_prompt`
<img width="360" alt="image" src="https://github.com/IlanCosman/tide/assets/88016602/5a9ebcdb-9c20-4547-a185-e7ad83dcbf80">
<img width="360" alt="image" src="https://github.com/IlanCosman/tide/assets/88016602/2cd17fdb-2b09-4ed8-8574-2bab65689bbe">
<img width="360" alt="image" src="https://github.com/IlanCosman/tide/assets/88016602/73e34712-9eeb-4a93-b9b7-dd942973d79a">
<img width="360" alt="image" src="https://github.com/IlanCosman/tide/assets/88016602/6bda3a48-2afc-40c3-97bc-1ffcdf494e05">

---

But this workaround seems to be not suitable for the tide - it doesn't update the builtin tide's vi mode indicator and in visual mode cursor gets broken:

### Tide with custom `fish_mode_prompt`
<img width="360" alt="image" src="https://github.com/IlanCosman/tide/assets/88016602/9eab169e-0ace-4513-9c7a-bfe7f8b9f835">
<img width="360" alt="image" src="https://github.com/IlanCosman/tide/assets/88016602/c34cb116-04b6-4384-b193-24e9bee37266">
<img width="360" alt="image" src="https://github.com/IlanCosman/tide/assets/88016602/b2c51373-08c1-49b3-81fc-e03ce4e672b3">
<img width="360" alt="image" src="https://github.com/IlanCosman/tide/assets/88016602/da4c2bdf-c1a3-40c5-89b8-ad8437839584">

---

So, I've tried to inject this logic that changes the cursor into the tide's logic for the indicator:

```fish

# ~/.config/fish/functions/_tide_item_vi_mode

function _tide_item_vi_mode
    test "$fish_key_bindings" != fish_default_key_bindings && switch $fish_bind_mode
        case default
      echo -en "\e[2 q"
            tide_vi_mode_bg_color=$tide_vi_mode_bg_color_default tide_vi_mode_color=$tide_vi_mode_color_default \
                _tide_print_item vi_mode $tide_vi_mode_icon_default
        case insert
      echo -en "\e[6 q"
            tide_vi_mode_bg_color=$tide_vi_mode_bg_color_insert tide_vi_mode_color=$tide_vi_mode_color_insert \
                _tide_print_item vi_mode $tide_vi_mode_icon_insert
        case replace replace_one
      echo -en "\e[4 q"
            tide_vi_mode_bg_color=$tide_vi_mode_bg_color_replace tide_vi_mode_color=$tide_vi_mode_color_replace \
                _tide_print_item vi_mode $tide_vi_mode_icon_replace
        case visual
      echo -en "\e[2 q"
            tide_vi_mode_bg_color=$tide_vi_mode_bg_color_visual tide_vi_mode_color=$tide_vi_mode_color_visual \
                _tide_print_item vi_mode $tide_vi_mode_icon_visual
    end
end

```

It works properly, but I don't think it's the best solution. I believe, that there are better ways to implement this, but I have 0 experience with debuging shell rendering. So, If someone who also uses vi mode with tide and has more experience in debuging shell stuff can look at this and share their thoughts, solutions - I would appreciate it.

**Comment by IlanCosman** [comment]
Afaict this would be the proper way of doing the workaround in Tide. The VI mode item is the perfect place to run those escape codes that change the cursor shape.

**Comment by glyh** [comment]
Is it possible to have this included in tide? I don't know how to both keep tide up to date and having this feature.
