### ISSUE TITLE
Missing space before command in tide v6.0 with transient prompt enabled

### ISSUE THREAD

**Issue by alissonlauffer** [IlanCosman/tide#448]
#### Describe the bug

When I used tide v5 + `zzhaolei/transient.fish`, there was a space before the command, but now using tide's own transient prompt, there's no space, which seems odd.

#### Steps to reproduce

1. `tide configure --auto --style=Lean --prompt_colors='True color' --show_time=No --lean_prompt_height='One line' --prompt_spacing=Compact --icons='Many icons' --transient=Yes`
2. Run any command
3. See the issue

#### Screenshots

Tide v6 + transient on:
![Tide v6 + transient on](https://github.com/IlanCosman/tide/assets/29029632/bf2dfdb9-8253-4e2b-bebf-c51b3e74db1f)

Tide v6 + transient off + `zzhaolei/transient.fish` (desired behavior):
![Tide v6 + transient off + zzhaolei/transient.fish](https://github.com/IlanCosman/tide/assets/29029632/92a5f551-08ee-4d79-8704-24b1c9f8ad62)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.6.1
tide version: 6.0.0
term: xterm-256color
os: Arch Linux
terminal emulator: gnome-console
fish startup: 16.51 millis
fisher plugins: ilancosman/tide
```

**Comment by IlanCosman** [comment]
v6.0.1 ty
