### ISSUE TITLE
transient prompt doesn't work if next command is typed in during output

### ISSUE THREAD

**Issue by PatrickF1** [IlanCosman/tide#455]
#### Describe the bug

If, while you wait for a command to finish its output to the terminal, you type in the next command with enter into the buffer, Tide does not go back to the previous prompt to collapse it.

#### Steps to reproduce

I personally first saw while running git commit, and while waiting for the git commit hooks to run, I typed in git push. That's my particular use case that I admit many people probably don't have. However, to repro this easily, you can:

1. run `sleep 5`
2. while the sleep command is running, quickly type in `ls` and hit enter
4. observe that while the prompt for `sleep 5` DOES collapse, the `ls` prompt does not

#### Screenshots
![Screenshot 2023-10-08 at 9 21 39 PM](https://github.com/IlanCosman/tide/assets/1967248/cd1c7a7c-7f1f-4ba0-b896-8cc6a7638e10)

#### Environment

```text
What operating system are you using? (e.g Ubuntu 20.04): macOS 13.6
What terminal emulator are you using? (e.g Kitty): ghostty (still in private beta)

Please copy the following information into the issue:

fish version: 3.6.1
tide version: 6.0.1
os: macOS 13.6
fish startup: 8.97 millis
fisher plugins: jorgebucaran/fisher jorgebucaran/bax.fish oh-my-fish/plugin-wifi-password patrickf1/fzf.fish jorgebucaran/fishtape ilancosman/clownfish ilancosman/tide@v6
```

**Comment by zzhaolei** [comment]
@IlanCosman You can bind the `new line` shortcut key to solve this problem. Like [this](https://github.com/zzhaolei/transient.fish/blob/aac6ffad18f76afd58ff58ac6d3fe684e04ce307/functions/__transient.fish#L28): `bind --user --mode default \cj __transient_execute`

**Comment by PatrickF1** [comment]
Thanks for fixing it!
