### ISSUE TITLE
Unknown command: fzf_key_bindings

### ISSUE THREAD

**Issue by fkrause98** [IlanCosman/tide#457]
Hi!

I've recently re-installed tide, but I'm coming across this error message each time the prompt shows:
```bash
fish: Unknown command: fzf_key_bindings
~/.nix-profile/share/fish/vendor_conf.d/load-fzf-key-bindings.fish (line 1): 
fzf_key_bindings
^~~~~~~~~~~~~~~^
from sourcing file ~/.nix-profile/share/fish/vendor_conf.d/load-fzf-key-bindings.fish
	called on line 248 of file /nix/store/pldynq1amrmvsdyqlvv87d08srkc8i52-fish-3.6.1/share/fish/config.fish
from sourcing file /nix/store/pldynq1amrmvsdyqlvv87d08srkc8i52-fish-3.6.1/share/fish/config.fish
	called during startup
```

It happens if I install tide with either fisher or through nix, I'm on MacOS, any ideas on how to fix this?

**Comment by fgardt** [comment]
see: https://github.com/NixOS/nixpkgs/issues/261777

**Comment by fkrause98** [comment]
Thanks!

That last comment helped: https://github.com/NixOS/nixpkgs/issues/261777#issuecomment-1780834548

Closing this 👍 .
