### ISSUE TITLE
string: shorten: invalid subcommand

### ISSUE THREAD

**Issue by rackodo** [IlanCosman/tide#458]
#### Describe the bug
Entire prompt broken by invalid subcommand

Upon making a newline, this error block appears.
```
string: shorten: invalid subcommand

~/.config/fish/functions/_tide_item_git.fish (line 2):
    if git branch --show-current 2>/dev/null | string shorten -"$tide_git_truncation_strategy"m$tide_git_truncation_length | read -l location
       ^
in function '_tide_item_git'
	called on line 4 of file ~/.config/fish/functions/_tide_2_line_prompt.fish
in function '_tide_2_line_prompt'
in command substitution
```

#### Steps to reproduce

1. Install using fisher.
2. See error

#### Screenshots

![Screenshot 2023-10-23 at 8 54 37 am](https://github.com/IlanCosman/tide/assets/42397332/a966389b-3b03-4dbc-b0ea-10e16157b54e)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.5.1
tide version: 6.0.1
term: xterm-256color
os: macOS Sonoma 14.0
terminal emulator: iTerm
fish startup: 19.34 millis
fisher plugins: jorgebucaran/fisher dracula/fish ilancosman/tide@v6
```

**Comment by IlanCosman** [comment]
Old fish version

**Comment by rackodo** [comment]
My fish version is 3.6.1. Isn't that the latest version?

**Comment by IlanCosman** [comment]
Your `tide bug-report` says 3.5.1.

**Comment by rackodo** [comment]
My mistake. Reinstalled fish, now it's fine. Thanks 👍🏻
