### ISSUE TITLE
Should the Pure emulator show Python virtual environment info?

### ISSUE THREAD

**Issue by willfrey** [IlanCosman/tide#46]
Right now, I don't see any info about the virtual environment once its activated. Should I be seeing anything?

In `$HOME/.config/fish/functions/tide/configure/configs/pure.fish`, I see

```fish
tide_virtual_env_bg_color normal
tide_virtual_env_color 00AFAF
tide_virtual_env_display_mode 'projectName'
tide_virtual_env_icon ''
```

which would suggest that the project name should show up, at a minimum.

I also can confirm that these are set as universal variables for my shell with

```fish
❯ set -U | grep "virtual_env"                                                                                                     
tide_virtual_env_bg_color normal
tide_virtual_env_color 00AFAF
tide_virtual_env_display_mode projectName
tide_virtual_env_icon 
```

Thanks!

**Comment by IlanCosman** [comment]
Woops, forgot to add that, thanks for pointing that out 😄

**Comment by willfrey** [comment]
Thank you for fixing that! Do I need to wait for another release to get these changes?

**Comment by IlanCosman** [comment]
Nope. It'll be there if you run `fisher update`. Tide's `main` branch should always be fine, though more comprehensive testing might be useful 😅. If you want to ensure that it's stable, you can always use the latest release.
