### ISSUE TITLE
Android logo shows an indian character instead

### ISSUE THREAD

**Issue by Dario48true** [IlanCosman/tide#460]
#### Describe the bug

I installed fish, fisher and tide on termux and set it up with icons, but I get an Indian looking character instead of the android logo

#### Steps to reproduce

1. Install on termux on android
2. Set the icons setting to 'Many icons'
3. Get wrong character

#### Screenshots

![Screenshot_20231031_180354_Termux](https://github.com/IlanCosman/tide/assets/118165619/ed657c87-0cfa-4ed0-bb00-09063c83b336)

Expected output would be (from different, now closed, issue)

![164558589-16717bed-96a5-4b23-a648-b8916eb7b831](https://github.com/IlanCosman/tide/assets/118165619/986c4ad5-c977-4aca-af64-3b4ec0415e64)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.6.1                                           tide version: 6.0.1
term: xterm-256color                                          os: Android
terminal emulator: Termux                                     fish startup: 28.29 millis
fisher plugins: ilancosman/tide@v6
```

#### Additional context

My nerdfont is gohu nerd font

**Comment by lens0021** [comment]
btw, I am suspecting that is an Indian character. It is maybe Arabic according to https://en.m.wiktionary.org/wiki/%D9%86%D9%8A
