### ISSUE TITLE
Using `tide configure --auto xxx` in `config.fish` causes tide prompt not showing immediately in new shell

### ISSUE THREAD

**Issue by wrvsrx** [IlanCosman/tide#461]
#### Describe the bug

Using `tide configure --auto xxx` in `config.fish` causes tide prompt not showing immediately in new shell. Prompt appears normally if I open fish by terminal (wezterm), this problem only occurs when open fish in another shell such as `bash` or `fish`.

#### Steps to reproduce

1. I create a minimal example: [tide-prompt.tar.gz](https://github.com/IlanCosman/tide/files/13371792/tide-prompt.tar.gz)
2. Download the example file, extract to `~/.config/fish`
3. `bash --norc`, then execute `fish` in `bash`. 
4. Prompt doesn't appear until I press enter.

#### Screenshots

![image](https://github.com/IlanCosman/tide/assets/42770726/d4ccd4d7-d6d8-470e-870f-491c658e7d88)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.6.1
tide version: 6.0.1
term: xterm-256color
os: NixOS
terminal emulator: wezterm
fish startup:
fisher plugins:
```

**Comment by IlanCosman** [comment]
`tide configure --auto` is not intended to be used in `config.fish`. It sets universal variables, so you just need to run it once :)

**Comment by wrvsrx** [comment]
I thought the `tide configure --auto` command was meant for declaring configuration (#304). Since it is not used for declarative configuration, do we still need to wait for #304 to be resolved?

**Comment by IlanCosman** [comment]
> I thought the `tide configure --auto` command was meant for declaring configuration (#304). Since it is not used for declarative configuration, do we still need to wait for #304 to be resolved?

This just comes down to a semantics question over what 'declarative configuration' is. Perhaps I have the definition wrong 🤷‍♂️ . But the idea is that you run the command once, and there's no plan to change that.
