### ISSUE TITLE
Right prompt position changed unexpectly. How to disable right prompt?

### ISSUE THREAD

**Issue by thomjiji** [IlanCosman/tide#464]
There is a problem: the right prompt of previous commands will change unexpectly when zoom in/out (effectively increase/decrease font size) in Konsole, so I wanna disable right prompt completely, but it seems it's not possible currently?

The current command's right prompt is just fine, it will stay unchange when zoom in/out. The problem is for the previous executed commands, when zoom in/out, right prompt will move.

![Screenshot_20231201_111751](https://github.com/IlanCosman/tide/assets/95394713/cc065b4b-4188-46c5-b765-7655c260d7ec)

**Comment by IlanCosman** [comment]
Yah, the right prompt for previous prompts won't change position. You can disable the right prompt by setting it to empty, like so: `set tide_right_prompt_items`.

**Comment by thomjiji** [comment]
Thanks! It works well. ^^
