### ISSUE TITLE
Path is not updated

### ISSUE THREAD

**Issue by smokephil** [IlanCosman/tide#47]
#### Describe the bug

The path in the command prompt is not updated.

#### Steps to reproduce

1. cd \<any directory\>

#### Expected behavior

Tide shows the actual path in the prompt.

#### Screenshots

![image](https://user-images.githubusercontent.com/1980055/99103861-83daf900-25e0-11eb-974e-1943a9648912.png)

#### Environment (please complete the following information)

- Operating System: ArchLinux
- Output of `tide bug-report`:

```console
fish, version 3.1.2
tide, version 2.4.0
xterm-256color

```

#### Additional context

It works on the current terminal when I reconfigure tide.
![image](https://user-images.githubusercontent.com/1980055/99114929-eab4de00-25f1-11eb-919d-d1b020000ff3.png)

**Comment by IlanCosman** [comment]
damnit, this bug is haunting me. Are you using OMF by any chance?

**Comment by smokephil** [comment]
I have found issue #19. After uninstalling omf it worked again.

**Comment by IlanCosman** [comment]
Oh wonderful 😅 I'm gonna add a big NO OMF sign to the readme to make it clear I guess

**Comment by smokephil** [comment]
Yes, that would be a good idea.
