### ISSUE TITLE
Prompt switches to transient prompt prematurely when selecting autosuggestion with Enter key

### ISSUE THREAD

**Issue by jaminthorns** [IlanCosman/tide#472]
#### Describe the bug

When the transient prompt is enabled, selecting an autosuggestion using the Enter key transforms the prompt to its transient version even though a command hasn't been run.

#### Steps to reproduce

1. Start typing a command.
2. Press Tab to trigger autosuggest options to display.
3. Select an autosuggestion with Tab or arrow keys.
4. Hit Enter to select an autosuggestion.
5. Prompt is transformed into transient even though a command has not been run.

#### Screenshots

https://github.com/IlanCosman/tide/assets/6618434/73f1e0a0-f250-479a-b96e-0670cc38a3a4

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.6.4
tide version: 6.0.1
term: xterm-256color
os: macOS 14.2.1 (23C71)
terminal emulator: WezTerm
fish startup: 31.99 millis
fisher plugins: jorgebucaran/fisher decors/fish-colored-man dracula/fish ilancosman/tide@v6 jorgebucaran/autopair.fish marcransome/pond patrickf1/fzf.fish
```

**Comment by IlanCosman** [comment]
Yah, it's a problem. I've asked about it here: https://github.com/fish-shell/fish-shell/discussions/10167
