### ISSUE TITLE
Background jobs cause problem if the threshold is not set

### ISSUE THREAD

**Issue by lumynou5** [IlanCosman/tide#474]
#### Describe the bug

The `tide_jobs_number_threshold` variable introduced in 6.1.0 causes errors if the variable is not set. This happens after update to 6.1.0.

#### Steps to reproduce

1. Install an older version of tide.
2. Update to 6.1.0, so the new variable is not set.
3. Run a job in background.
4. See error.

#### Screenshots

![image](https://github.com/IlanCosman/tide/assets/84374077/a1e63a08-88a5-4a1f-a139-e5ec4b032336)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.6.4
tide version: 6.1.0
term: xterm-kitty
os: Arch
terminal emulator: Kitty
fish startup: 26.22 millis
fisher plugins: jorgebucaran/fisher jorgebucaran/autopair.fish nickeb96/puffer-fish meaningful-ooo/sponge decors/fish-colored-man lumynou5/homeshick.fish lumynou5/eza.fish ilancosman/tide@v6 jethrokuan/z
```

#### Additional context

Please consider to set the variable on updating if it's not set.

**Comment by IlanCosman** [comment]
Thanks, it's been a while since I've changed old items I guess 😅forgot how to be careful.
