### ISSUE TITLE
Path is printed in console before rendering the prompt

### ISSUE THREAD

**Issue by KeithBrown39423** [IlanCosman/tide#475]
#### Describe the bug

Every time I go to run a command inside a project directory, the path (as well as other stuff is printed to the console) I have attached a screenshot because I don't know how else to describe this.

#### Screenshots

![Screenshot_20240103_130533_JuiceSSH](https://github.com/IlanCosman/tide/assets/74946768/eeced26e-93a9-479b-8fa1-fa81c563b92d)

#### Environment

Output of `tide bug-report`: 

```text
fish version: 3.6.4
tide version: 6.1.1 term: linux
os: 22.04.3 ~ x86_64
terminal emulator: Alacritty / JuiceSSH
fish startup: 76.18 millis
fisher plugins: jorgebucaran/fisher jhillyerd/plugin-git jorgebucaran/nvm.fish ilancosman/tide@v6
```

**Comment by KeithBrown39423** [comment]
I don't know if this is a bug or user error, but any help would be appreciated

**Comment by KeithBrown39423** [comment]
![image](https://github.com/IlanCosman/tide/assets/74946768/917bb1de-7443-48e4-8e8c-1980154c9043)
Here is a screenshot from alacritty

**Comment by KeithBrown39423** [comment]
Nevermind. This issue was created by the path containing spaces

**Comment by IlanCosman** [comment]
> Nevermind. This issue was created by the path containing spaces

Wait what? Paths containing spaces works on my machine and are tested for...

**Comment by KeithBrown39423** [comment]
i honestly dont know. i found issue 330 and 329 and thought that might've been the issue but now I don't know

**Comment by KeithBrown39423** [comment]
i had this issue the first time I installed it too, but I don't remember what I did to fix it

**Comment by KeithBrown39423** [comment]
it doesnt seem print a bunch of stuff if I'm not in a project directory, but still has this
![image](https://github.com/IlanCosman/tide/assets/74946768/4804cf1b-d2fa-4921-9b65-3bde2dd6c5cb)

**Comment by KeithBrown39423** [comment]
![image](https://github.com/IlanCosman/tide/assets/74946768/c891971c-c12d-4d3f-9e92-5ebef6b78d4e)
here is my path if it helps

**Comment by KeithBrown39423** [comment]
nevermind. the issue was with an alias I set

apparently this `alias path="string replace -a : \n \"$PATH\""` created this whole issue

**Comment by IlanCosman** [comment]
Oh, yah that would explain it 😄 `path` is a new fish builtin from fish 3.5.0. Apparently it can be aliased tho lol
