### ISSUE TITLE
Prompt showing up everywhere when resizing window

### ISSUE THREAD

**Issue by TheEvilSkeleton** [IlanCosman/tide#48]
#### Describe the bug

Resizing the window of a terminal will make the terminal look super ugly. The prompt will show up everywhere every time it gets resized.

#### Steps to reproduce

1. Set tide up
2. Resize the window

#### Expected behavior

It should look clean.

#### Screenshots

![fish](https://user-images.githubusercontent.com/50847364/99743022-c5691980-2aa2-11eb-8c92-7bd7aa81e47b.gif)

#### Environment (please complete the following information)

- Operating System:  Fedora
- Output of `tide bug-report`: 

```console
fish, version 3.1.2
tide, version 2.4.0
xterm-256color
```

**Comment by IlanCosman** [comment]
Thanks for filing this issue @TheEvilSkeleton, I really appreciate you taking the time to create such a nice gif demonstrating the issue (nice wallpaper btw). Unfortunately, this is an upstream issue with multi-line left prompts. 

To demonstrate this, try the following:

```fish
function fish_prompt
    echo foo
    echo bar
end
```

```fish
function fish_right_prompt
    echo blah
end
```

You'll see the same window resizing issue.

**Comment by TheEvilSkeleton** [comment]
I opened an issue in case you're interested: https://github.com/fish-shell/fish-shell/issues/7491.

---

For the image, in case you're interested, here you go:
- https://www.reddit.com/r/wallpaper/comments/bt38r4/1920x1080_hyper_beast_dark_mode_so_you_dont_get/
- https://wallpaperaccess.com/hyperbeast

Here's the artist: https://brockhoferart.com/projects

**Comment by IlanCosman** [comment]
Upon closer inspection this might not be an upstream issue, only very similar 😅
