### ISSUE TITLE
🌊 Add support for Warp Terminal

### ISSUE THREAD

**Issue by Soromeister** [IlanCosman/tide#480]
#### Is your feature request related to a problem? Please describe

TIDE is not working with [Warp Terminal](https://github.com/warpdotdev/Warp).

#### Describe the solution you'd like

There is [a corresponding issue on Warp's end](https://github.com/warpdotdev/Warp/issues/3358) where it states that `Tide has a few UI conflicts with Warps blocks`.

#### Additional context

N/A

**Comment by IlanCosman** [comment]
Yah, just tried Warp, there are simply too many incompatibilities right now.
