### ISSUE TITLE
Support for Bun

### ISSUE THREAD

**Issue by will-stone** [IlanCosman/tide#484]
Thanks for Tide. I was a die-hard Starship user until I saw the light of your async 😄 

#### Is your feature request related to a problem? Please describe

When using the [Bun](https://bun.sh/) runtime, over node.js, the node version is shown on the right (of my lean) prompt.

#### Describe the solution you'd like

Would be great if the Bun version was shown when a `bun.lockb` file is detected.

#### Additional context

I have tried my hardest to make this work locally, by copying and adapting the node integration. For some reason I can't get the version number to display. No idea what I'm doing wrong. I even looked at the recent Zig PR, and my changes were pretty much the same. Is there a command I need to run to refresh it, or a cache I need to invalidate? If so, I'm happy to PR this in myself.

Thanks,

Will.

**Comment by IlanCosman** [comment]
Hey there, glad to hear you're enjoying tide :)

Please do submit a PR with the changes you've made, it'll be easier for me to tell where you're going wrong. There are indeed a lot of tiny little edits required for making a new item.

**Comment by will-stone** [comment]
Okay, will do. Thanks. Hopefully have that with you tomorrow.

**Comment by will-stone** [comment]
@IlanCosman I've added a PR, please feel free to demand or make changes 😄 https://github.com/IlanCosman/tide/pull/485
