### ISSUE TITLE
Give ability to shorten the current path

### ISSUE THREAD

**Issue by joaolrpaulo** [IlanCosman/tide#49]
#### Is your feature request related to a problem? Please describe
Sometimes when navigating through nested folders it can get nasty looking at the path

#### Describe the solution you'd like
Have a way to shorten the path of the current directory

**Comment by IlanCosman** [comment]
If I'm understanding your question correctly, I believe you're looking for something like [tide_pwd_max_dirs](https://github.com/IlanCosman/tide/blob/main/docs/Configuration.md#pwd).

**Comment by joaolrpaulo** [comment]
Hey @IlanCosman 

Thanks for the fast answer, I was looking into something like:

If my `pwd` is `/home/joaopaulo/coding/dotfiles/configs` to have a option to produce `~/c/d/configs`

**Comment by IlanCosman** [comment]
Then set `truncate_margin` to a very large number.

**Comment by joaolrpaulo** [comment]
That worked :tada: 

May I suggest add an example on documentation for future reference?

Thanks for this :pray:

**Comment by IlanCosman** [comment]
I'm not sure how to add examples that would be useful while not taking up a huge amount of space. Something like:

Before: `~/coding/dotfiles/configs`
`set tide_pwd_truncate_margin 10000`
After: `~/c/d/configs`

for each variable would be a bit ridiculous, especially when they already have descriptions.
