### ISSUE TITLE
follow color scheme of fish/terminal

### ISSUE THREAD

**Issue by GregDMeyer** [IlanCosman/tide#50]
Sorry if I missed this in the documentation somewhere---it seems that on my machine, "pure" is the only prompt whose color scheme matches the one that I have set via `fish_config`. Is there a way to make the colors of the other prompts track that? I would prefer to not have to set each of the colors individually to match my color scheme :) thanks!

**Comment by IlanCosman** [comment]
Unfortunately not. Pure is the only one that uses the user's color scheme (`black`, `red` , `brgreen`) etc. The other styles should fit in quite well with most color schemes though. Sorry 😞

**Comment by GregDMeyer** [comment]
ok! thanks for the response anyway :)
