### ISSUE TITLE
Used the configuration wizard, love it but still too noisy, how come disable some info?

### ISSUE THREAD

**Issue by esn89** [IlanCosman/tide#508]
I installed Tide and set up a compact and light prompt.

Right now, I am still getting a lot of information thrown at me such as which git modified lines, Google Project I'm logged in to and the current Kubernetes cluster context.

Is there a way to turn things on and off?

**Comment by clarksonator** [comment]
I removed x1ekubectl from "tide_right_prompt_items" in .config/fish/fish_variables and I am not seeing the kubernetes info anymore.

**Comment by esn89** [comment]
Thanks a million, this helps alot.
