### ISSUE TITLE
default setting

### ISSUE THREAD

**Issue by idkjs** [IlanCosman/tide#51]
What would I need to set to get these icons to to look right?

Also, is there a default setting?

<img width="976" alt="Screen Shot 2020-11-29 at 10 50 42 AM" src="https://user-images.githubusercontent.com/2370391/100538555-c03d6480-3230-11eb-8dff-822d82650eb7.png">

![Screen Shot 2020-11-29 at 10 58 58 AM](https://user-images.githubusercontent.com/2370391/100538751-ed3e4700-3231-11eb-952b-896556b33569.png)

Thank you and thanks for sharing this project.

**Comment by idkjs** [comment]
Apparently the answer is:

```
- Update font settings to use a Menslo font
  - iTerm
    - `Preferences -> Profiles -> Text -> Change Font`
```

<img width="943" alt="Screen Shot 2020-11-29 at 11 07 56 AM" src="https://user-images.githubusercontent.com/2370391/100538950-288d4580-3233-11eb-8b0d-3fc317044e26.png">

Any additional comments are welcome.

**Comment by idkjs** [comment]
prompts for defaults: 

```
3 2 3 1 3 2 3 4 2 2 1 y
```

**Comment by idkjs** [comment]
In messing around with this, I tried to override the colors with the falling commands. How do I get the colors back to the defaults?

```
set -U tide_git_prompt_bg_color 99C794
set -U tide_jobs_color 99C794
set -U tide_status_success_color 99C794
```

I tried reinstalling but that didnt work.

Thanks.

**Comment by IlanCosman** [comment]
It's great to see that you solved the font issue on your own! I just woke up 😄 Go through the configuration wizard again to reset everything. Open it with `tide configure`.
