### ISSUE TITLE
Not configuring tide or executing fish directly causes a "math: Expected at least 1 args, got 0" error

### ISSUE THREAD

**Issue by ThoriumTextile** [IlanCosman/tide#52]
#### Describe the bug

Whenever i open a terminal or run fish, this error shows up:
`math: Expected at least 1 args, got 0`

#### Steps to reproduce

1. Install tide with fisher
2. Skip the configuration ("N" when asked) / Launch fish directly from the terminal
3. See error.

#### Screenshots

![sample](https://user-images.githubusercontent.com/75760340/101697999-14d6b000-3a79-11eb-8802-5bb1aae5c133.png)

**Comment by IlanCosman** [comment]
I can't reproduce this with a clean fish on MacOS or Arch. Do you have Oh My Fish installed? Also, can you paste the output of `tide bug-report` here?

**Comment by ThoriumTextile** [comment]
- Do you have Oh My Fish installed?
No i do not.

```
fish, version 3.1.2
tide, version 2.5.0
xterm-256color
```

**Comment by IlanCosman** [comment]
Can you try the following? This will create a perfectly clean fish instance, install fisher in it, and then install tide.

```console
sh -c 'env HOME=$(mktemp -d) fish'
curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher
fisher install IlanCosman/tide
```

**Comment by ThoriumTextile** [comment]
Just tried. Nothing changed. (both after skipping the configuration and starting fish manually)

**Comment by IlanCosman** [comment]
Not sure what to tell you then 😞I can't reproduce it on my side using the same methodology. I'm working on a v3 (hopefully releasing today) so perhaps that will fix things.

**Comment by jorgebucaran** [comment]
@ThoriumTextile What does `$COLUMNS ` output for you?

**Comment by ThoriumTextile** [comment]
> @ThoriumTextile What does `$COLUMNS` output for you?

`fish: Unknown command: 107`

**Comment by jorgebucaran** [comment]
@ThoriumTextile Sorry, I mean do this:

```fish
echo $COLUMNS
```

and post the result here. Thanks.

**Comment by ThoriumTextile** [comment]
> @ThoriumTextile Sorry, I mean do this:
> 
> ```fish
> echo $COLUMNS
> ```
> 
> and post the result here. Thanks.

- echo $COLUMNS
`107`

**Comment by IlanCosman** [comment]
@ThoriumTextile Are you still running into this with the latest version of Tide?

**Comment by ThoriumTextile** [comment]
![Schermata del 2020-12-23 20-44-01](https://user-images.githubusercontent.com/75760340/103032198-668e3880-4557-11eb-9c05-56a4f012b489.png)
Works perfectly now! There's still the same error after you skip the configuration, at least it doesn't nag you every time you exit tide or start a terminal!

**Comment by abbsi** [comment]
![image](https://user-images.githubusercontent.com/470499/104127126-ce2aed00-5379-11eb-9bf8-0387c4f556c0.png)

Hi, I was am seeing this issue on my setup. To try and trouble shoot:

-  if it was another plugin/omf I moved the full ~/.config/fish to start fresh and issue persists
- tried a few random `tide configure` setups with the same results
- Also tried multiple terminals (kitty, alacritty, xterm, tty)

`echo $COLUMNS` outputs a number correctly

Let me know if there's anything I can do/provide to help troubleshoot :)

**Comment by abbsi** [comment]
I realize now that ThoriumTextile's issue might have been somewhere else and maybe should have opened a new issue.

I believe I have narrowed down which function is causing the error in my case. The function `_tide_detect_os_linux_cases` in `_tide_detect_os.fish` throws the math error if my distribution ID does not have a case?

Content of `/etc/os-release`
```
NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://garudalinux.org/"
DOCUMENTATION_URL="https://wiki.garudalinux.org/"
SUPPORT_URL="https://forum.garudalinux.org/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
LOGO=garudalinux
```

Content of `/etc/os-release`
```
NAME="Garuda Linux"
PRETTY_NAME="Garuda Linux"
ID=garuda
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://garudalinux.org/"
DOCUMENTATION_URL="https://wiki.garudalinux.org/"
SUPPORT_URL="https://forum.garudalinux.org/"
BUG_REPORT_URL="https://gitlab.com/groups/garuda-linux/"
LOGO=garudalinux
```

Other details:

- fish, version 3.1.2
- tide, version 3.1.0

**Comment by IlanCosman** [comment]
Thanks for doing my job for me 😂 You're absolutely correct. The issue is that your `/etc/os-release` doesn't have an `ID_LIKE` line, and `detect_os` doesn't have a way of handling that. I'll get that fixed 😄 

Garuda linux really _should_ have an `ID_LIKE` with Arch though, since it is a derivative distribution. Perhaps you could open an issue/pr for that.

**Comment by IlanCosman** [comment]
Fixed! Yah in general it's best to open new issues, especially for an error as generic as this one. 👍 Thanks a ton for practically solving this on your own though.
