### ISSUE TITLE
Current dir always show "~", not matter what ever pwd is

### ISSUE THREAD

**Issue by jheroy** [IlanCosman/tide#54]
#### Steps to reproduce

Use default setting.

After execute `tide configure`, it's woks fine. But it's not working when I open a new shell.

#### Expected behavior

Current dir should show that the `pwd` command output.

#### Screenshots

<img width="665" alt="image" src="https://user-images.githubusercontent.com/504766/102684192-5dc4fc00-4211-11eb-88e6-f3b0e88da4d3.png">

#### Environment (please complete the following information)

- Operating System:  macOS 10.15.7
- Output of `tide bug-report`:
fish, version 3.1.2
tide, version 2.5.0
xterm-kitty
```console

```

**Comment by jheroy** [comment]
Sorry, I remove omf, it's works.

**Comment by IlanCosman** [comment]
Alright, this convinced me 😅I'm going to add a "Does not work with OMF" warning for Tide 3.0.

**Comment by IlanCosman** [comment]
Ahahah, ironically, async in Tide 3.0 fixes the issue with OMF, which was about conflicting on-change `$PWD` handlers I believe. I guess I think I'll hold off on that warning.
