### ISSUE TITLE
How to change the prompt char from `>` to `$` ?

### ISSUE THREAD

**Issue by sgon00** [IlanCosman/tide#550]
Hi, I am new to fish and tide. Thanks a lot for this excellent async tool, it's very fast.
I am just wondering how to change the prompt char from `>` to `$` ? Thanks.

**Comment by xlspring** [comment]
Hello. I went through the files of this prompt and noticed that it takes a prompt character from the `tide_character_icon` global variable. So, to change it to `$`, you'd want to execute `set -Ux tide_character_icon '$'` in your fish shell.
![image](https://github.com/user-attachments/assets/8712a591-0d9c-4cb2-a9e0-10fecd15dc14)

**Comment by sgon00** [comment]
@xlspring Thank you very much for your help. ^_^
