### ISSUE TITLE
Tide prompt leaks subprocesses (Increase in zombie/defunct subshells over time)

### ISSUE THREAD

**Issue by vamega** [IlanCosman/tide#60]
#### Describe the bug

Installation of the tide prompt creates lots of defunct/zombie processes.

#### Steps to reproduce

1. Install tide
2. Run `ps axc -o pid,ucomm,tty | grep 'fish <defunct>' | wc -l` and observe the number
3. Run `ps axc -o pid,ucomm,tty | grep 'fish <defunct>' | wc -l` and observe that the number is higher.

You can also see the increase in number of subprocesses in `htop`.

#### Expected behavior

I would expect the number of zombie processes to be 0. Prior to the installation of `Tide` I had no zombie processes. The removal of `Tide` removed all the Zombie processes

#### Environment (please complete the following information)

- Operating System: Arch Linux
- Fish Version: 3.1.2
- Tide Version: 3.0.0
- Fisher version: 4.1.0
- Fisher plugins installed:
  - jorgebucaran/fisher
  - PatrickF1/fzf.fish
  - IlanCosman/tide
- FZF version: 0.24.4 (f502725)

- Output of `tide bug-report`: 

```console
╰─tide bug-report
fish, version 3.1.2
tide, version 3.0.0
xterm-256color

```

#### Additional context

I wasn't sure the best way to figure out what the best way of tracking what the processes are doing, or why they're not being reaped appropriately. I tried attaching via strace to see if I could discern what the processes were being spawned for and what they were doing, but the output was very large. I'd need to filter to the appropriate syscalls, and thought I'd try to post this bug report before I spent too much more time on that approach.

It seems like that I'm seeing an increase of two zombie processes per invocation of the `ps` command detailed above. Maybe that's a hint of what's happening?

I'd be happy to try other approaches that you suggest if it would help fix the issue.

**Comment by IlanCosman** [comment]
Thanks for this very thorough bug report 😄Yah this is a known bug that I decided to overlook for the v3 release since zombie processes don't hurt anything. Thanks for reminding me about this though, I'll look into it.

**Comment by vamega** [comment]
Thanks for making this, I'm really liking what I see so far.
I'm pretty sure the issue is right here: https://github.com/IlanCosman/tide/blob/main/functions/fish_prompt.fish#L14

I think the simplest way to solve this is to simply remove the `disown` command there.
By disowning the child process fish doesn't seem to ever call waitpid on it.

I see this issue on the fish repo: https://github.com/fish-shell/fish-shell/issues/5342
However it's marked as fixed, so perhaps the issue is only slightly related.
I can tell that the subprocess is still marked as parented to fish, but the presence of the zombie means that fish isn't reaping it.

Is there a downside to not removing the disown command from here?
I'll file a bug against fish-shell later tonight if I can verify what's going on there outside of tide.

**Comment by IlanCosman** [comment]
> Is there a downside to not removing the disown command from here?

1. Adds Tide's jobs to the `jobs` list of the user. This is a bit annoying for the user, because it obscures the jobs they actually created. It's also a bit annoying for Tide, as we also want to know if the user created jobs. We can get around our side of the problem by filtering the job list and ignoring anything Tide created.
2. Can prevent the user from immediately exiting the shell. I don't think this is solvable.

Neither of these are super important, but problem 1 would add more code, and both of them reduce Tide's "polish" so to speak.

> I'll file a bug against fish-shell later tonight if I can verify what's going on there outside of tide.

I have been trying to reproduce the issue without Tide, but I haven't gotten it yet. If you manage to do so, that'd be great 😄

**Comment by IlanCosman** [comment]
As you expected, the problem was in fact the disown: https://github.com/fish-shell/fish-shell/issues/7581

**Comment by vamega** [comment]
Thank you.

I’ll try to fond a workaround so that for Tide so that I’m not forced to
run the Madurese branch of fish until the next branch is released.

**Comment by IlanCosman** [comment]
Hopefully fish 3.2 will come out soon and fix this bug. You can also just ignore the zombie processes though, they're not harmful at all.

**Comment by mknj** [comment]
i still get one permanent zombie after installing tide. Is this a a design choice?

The zombie vanishes when uninstalling tide.

fish, version 3.3.1

**Comment by IlanCosman** [comment]
> i still get one permanent zombie after installing tide

Thanks for bringing this up again! I also get a zombie. I guess the bug in fish reappeared.

> Is this a a design choice?

Certainly not 😄
