### ISSUE TITLE
"ls" spacing messed up with nerdfonts

### ISSUE THREAD

**Issue by jeremymeyers** [IlanCosman/tide#61]
Seemingly regardless of the window size or typeface, the ls function seems to display all messed up
<img width="1532" alt="Screen Shot 2020-12-28 at 7 03 31 PM" src="https://user-images.githubusercontent.com/3514095/103250014-e5141d00-493f-11eb-9234-886a420ce63d.png">

**Comment by IlanCosman** [comment]
Can you verify that this is related to Tide? i.e if you have a perfectly stock fish, does this still happen? 
Run `sh -c 'env HOME=$(mktemp -d) fish'` and then try to recreate the problem.

P.S. Try using iterm2. You won't have those discolored prompt heads.

**Comment by jeremymeyers** [comment]
hmm... doing a restart of terminal seems to have cleared it out. very strange. looks like it was moving a line down for each tab. sorry to bother!
