### ISSUE TITLE
The prompt char affects fish's syntax highlighting

### ISSUE THREAD

**Issue by peng1999** [IlanCosman/tide#64]
#### Steps to reproduce

1. copy an arbitrary command text. 
2. open a terminal and paste the text, usually using <kbd>Shift</kbd>+<kbd>Ins</kbd> or <kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>V</kbd>.
3. See error

#### Expected behavior

Expected: (the style of `echo` should be bold while)
<img width="244" alt="Screenshot_20201231_101408" src="https://user-images.githubusercontent.com/12483662/103390723-eec09f00-4b50-11eb-92da-f624a810fc51.png">

Actual: (the color of `echo` becomes the same as the prompt char)
<img width="223" alt="Screenshot_20201230_213637" src="https://user-images.githubusercontent.com/12483662/103354751-5b9f4f00-4ae7-11eb-8007-c5468df3e036.png">

#### Environment (please complete the following information)

- Operating System: Manjaro Linux
- Output of `tide bug-report`: 

```console
❯ tide bug-report
fish, version 3.1.2
tide, version 3.0.0
alacritty
```

#### Additional context
Tested in alacritty, konsole, tmux in alacritty, and tmux in konsole. The described behaviour is consistent.

**Comment by IlanCosman** [comment]
Could you provide the output of `echo $fish_color_command`?

**Comment by peng1999** [comment]
It’s `—bold`:

```console
❯ echo $fish_color_command 
--bold
```

**Comment by IlanCosman** [comment]
So the problem here is that your `fish_color_command` isn't actually a color, so Fish just lets Tide's color continue. For example, if you changed your `fish_color_command` to `--bold white` instead of allowing the `white` to be assumed, this bug wouldn't appear. I suppose Tide ought to be self contained here, but this is a very niche reason. I'll have a change to request on the PR, thanks for reporting this 😄

**Comment by kidonng** [comment]
This also happens when you enter nested shells, and close the terminal tab containing the nested shells.

> I think it's unavoidable that we might orphan some variables since you can have multiple shells open. ... It's unfortunate, but not really a major issue if we leave a variable or two in this fairly uncommon case. Thanks for reporting this 😄

Agreed, but still pretty annoying. Maybe someday I will write a function to check the variables list and remove the pids which aren't running.

**Comment by kidonng** [comment]
Oops, wrong issue to comment. 😅 Sorry for the disturb!
