### ISSUE TITLE
right prompt has a margin in tmux

### ISSUE THREAD

**Issue by peng1999** [IlanCosman/tide#66]
#### Describe the bug

The right prompt is misplaced in tmux.

#### Steps to reproduce

1. execute `tmux`

#### Expected behavior

The right prompt is expected to well aligned with terminal's right border.
<img width="519" alt="Screenshot_20210102_205419" src="https://user-images.githubusercontent.com/12483662/103457724-b54c8700-4d3c-11eb-8fd0-9bac5c492ffc.png">

#### Screenshots

But it's not the case in tmux:
<img width="517" alt="Screenshot_20210102_205553" src="https://user-images.githubusercontent.com/12483662/103457747-edec6080-4d3c-11eb-8338-98607aa28a1c.png">

#### Environment (please complete the following information)

- Operating System: Manjaro Linux
- Output of `tide bug-report`: 

```console
❯ tide bug-report
fish, version 3.1.2
tide, version 3.1.0
tmux-256color
```

**Comment by IlanCosman** [comment]
Setting `$TERM` to `xterm` or `xterm-256color` solves the problem. Not much else I can say unfortuntely😞

**Comment by IlanCosman** [comment]
Fixed!
