### ISSUE TITLE
prompt fails when trying to shorten one letter directories

### ISSUE THREAD

**Issue by peng1999** [IlanCosman/tide#67]
#### Describe the bug

When I enter a directory which is long enough, the prompt stops update.
It seems that the background process stuck in the following while loop and never return.

https://github.com/IlanCosman/tide/blob/main/functions/_tide_item_pwd.fish#L44-L47

#### Steps to reproduce

1. `cd /tmp`
1. `mkdir -p /tmp/and/a/long/enough/deep/nested/directory`
2. `cd /tmp/and/a/long/enough/deep/nested/directory`
3. The prompt pwd is still `/tmp`

#### Expected behavior

The prompt should work as normal in long directories.

#### Environment (please complete the following information)

- Operating System: Manjaro Linux
- Output of `tide bug-report`: 

```console
❯ tide bug-report
fish, version 3.1.2
tide, version 3.1.0
xterm-256color
```

**Comment by IlanCosman** [comment]
Here's a quick patch for this. It's caused by the `/a/` in your pwd. I think I'm going to do a full rewrite of the pwd item, I didn't think it out well enough from the start, so it's been consistently flaky.
