### ISSUE TITLE
Current directory not displayed

### ISSUE THREAD

**Issue by bluebyt65** [IlanCosman/tide#68]
#### Describe the bug (Sorry another thread about this!)
    Open shell:
~ ❯
    Change directories:

~ ❯ cd Downloads

~ ❯ pwd
/home/bluebyt/Downloads
~ ❯
    Directory displayed in prompt does not update
#### Screenshots
![image](https://user-images.githubusercontent.com/18442224/103593082-d7701180-4ec2-11eb-9cfb-6102a4b97011.png)

I removed OMF completely as advised in other treads about this, but the problem still occur. I did saw that I maybe need to reinstall Tide, but I don't know how to do it.
 
#### Environment (please complete the following information)
- Operating System: Archlinux
- Output of `tide bug-report`: 

```
fish, version 3.1.2
tide, version 3.1.0
xterm-256color
```

**Comment by IlanCosman** [comment]
You probably don't need to reinstall Tide. Try a `fisher update`.

**Comment by IlanCosman** [comment]
Could you run this:

```fish
HOME=(mktemp -d) fish -C 'curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher ilancosman/tide'
```

This will create a temporary new home directory (meaning that Fish will be clean), insteall Fisher, and install Tide.

If the bug doesn't happen there, then it's something to do with your Fish configuration, perhaps OMF related.

**Comment by bluebyt65** [comment]
Yes it's working, Ok I am gonna try to see what is wrong with my Fish shell configuration. Thank you to help me on this! any other advise is welcome.

**Comment by IlanCosman** [comment]
The simplest option is to just start over from scratch, though if you have an extensive configuration that might be annoying. Personally, Fish offers so much out of the box that I don't have any configuration to speak of, just a few plugins installed with Fisher.

**Comment by bluebyt65** [comment]
I found the problem, I have a line in my config.fish file that caused the problem:
cd ~
Thank you for your help!

**Comment by IlanCosman** [comment]
Oh, yeah, that makes sense. Tide creates a new Fish process with every prompt and that instance would always be in the home directory. I'll work on seeing if I can ignore the user config by setting `__fish_config_dir` or `HOME` or something.
