### ISSUE TITLE
Tide universal variables orphaned after uninstall

### ISSUE THREAD

**Issue by PatrickF1** [IlanCosman/tide#69]
#### Steps to reproduce

1. Fresh install tide: `fisher install ilancosman/tide` (after manually removing whatever universal variables were left behind)
2. configure tide by hitting 1 1 1 1 1 .... y
3. `fisher remove ilancosman/tide`
4. Open new fish session
5. Check universal variables
```
$ set | rg tide
_tide_left_prompt_display_77962 \e\[38\;2\;108\;108\;108m\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \…
_tide_right_prompt_display_77962 \e\(B\e\[m\e\(B\e\[m\e\(B\e\[m\ \e\(B\e\[m\e\[38\;2\;135\;13…

$ set -S _tide_left_prompt_display_77962
$_tide_left_prompt_display_77962: not set in local scope
$_tide_left_prompt_display_77962: not set in global scope
$_tide_left_prompt_display_77962: set in universal scope, unexported, with 0 elements
```

**Comment by PatrickF1** [comment]
Btw, I am not leaving tide, just experimenting with other prompts since there are so many good ones now.
Also, I was gonna fix it myself but then I realized it probably has to do with `_tide_var_list` and then I decided it's better left up to you to fix.

**Comment by IlanCosman** [comment]
Oh, yeah, that's really obvious in retrospect 😂

**Comment by PatrickF1** [comment]
Happens to the best of us! What was so obvious about it?

**Comment by IlanCosman** [comment]
Well I never added them to `_tide_var_list`, so they won't get removed. I just had it so that on fish exit, they are erased. But if you uninstall, then that `on_fish_exit` function gets removed.

**Comment by IlanCosman** [comment]
I think it's unavoidable that we might orphan some variables since you can have multiple shells open. With async, `_tide_left_prompt_display_$fish_pid` might get set after you've uninstalled Tide in another shell. It's unfortunate, but not really a major issue if we leave a variable or two in this fairly uncommon case. Thanks for reporting this 😄

**Comment by IlanCosman** [comment]
Oh, actually, no we can have it taken care of! I just need to ensure that the `_tide_on_fish_exit` function isn't erased when uninstalling!

**Comment by PatrickF1** [comment]
Nice work! You're welcome.

**Comment by jorgebucaran** [comment]
Just erase functions last?

**Comment by PatrickF1** [comment]
Wow we keep bumping into each other, Jorge!

**Comment by jorgebucaran** [comment]
🏓

**Comment by IlanCosman** [comment]
> Just erase functions last?

Tide already does this. The problem is that the universal variables may be set again afterwards by another shell for example. So we need something that has effect even after uninstalling Tide.

**Comment by kidonng** [comment]
This also happens when you enter nested shells, and close the terminal tab containing the nested shells.

> I think it's unavoidable that we might orphan some variables since you can have multiple shells open. ... It's unfortunate, but not really a major issue if we leave a variable or two in this fairly uncommon case. Thanks for reporting this 😄

Agreed, but still pretty annoying. Maybe someday I will write a function to check the variables list and remove the pids which aren't running.

**Comment by IlanCosman** [comment]
> function to check the variables list and remove the pids which aren't running

That's a good idea! We could run it on interactive startup. I'll look into it for v5 😄
