### ISSUE TITLE
Fish 3.2 - Prompt doesn't update after changing directory until you press a key

### ISSUE THREAD

**Issue by imabuddha** [IlanCosman/tide#72]
#### Describe the bug

After changing to a directory the new prompt still shows the previous path until any key is pressed.

#### Steps to reproduce

1. note the current path displayed in the tide prompt
2. cd to a different path
3. observe that the tide prompt still shows the previous path
4. press any key, for example `<space>`
5. now the tide prompt path is updated to the correct path

#### Expected behavior

The tide prompt should always display the current path.

#### Screenshots

This shows step 3:
![2021-01-13_14:13:02_467x281](https://user-images.githubusercontent.com/168539/104409394-85f21180-55a9-11eb-9d12-edf2ec9c0fc1.png)

This shows step 5:
![2021-01-13_14:13:07_467x281](https://user-images.githubusercontent.com/168539/104409408-8b4f5c00-55a9-11eb-9f72-4c1b2d538475.png)

#### Environment (please complete the following information)

- Operating System: Raspberry Pi OS (debian based)
- Output of `tide bug-report`: 

```console
fish, version 3.1.2-1906-gc76074b1d
tide, version 3.2.0
xterm-256color
```

#### Additional context

1. I did search through open & closed issues (found some similar but closed as fixed).
2. I had to build fish from source to use tide as the version in my distro is only 3.0.2 (no problems with build or operation thus far).
3. Another odd thing is that when opening a fish shell the prompt doesn't appear until any key is pressed.
4. If I uninstall tide fish's prompt always displays the current path (and appears in a new shell).

**Comment by IlanCosman** [comment]
Yah, this is a problem with the bleeding edge version of Fish, thanks for taking the time to report this 😄

**Comment by IlanCosman** [comment]
Also, it's worth noting that you didn't need to build Fish from source, there's an [official PPA](https://launchpad.net/~fish-shell/+archive/ubuntu/release-3) with the latest version 3.1.2.

**Comment by imabuddha** [comment]
Not a problem, thanks for your work on this plugin! I've just started trying out fish, haven't switched full time yet. So if I were to build against the latest tagged release then I shouldn't observe this behavior? If so I'll do that since I'd need to build again when 3.2 is released.

Re the PPA, I'm not sure if they support the Pi's cpu. I'm on a Pi 4 currently 32 bit (64 os is still beta) so architecture is armv7l. I don't mind building from source.

**Comment by imabuddha** [comment]
I just built fish against the 3.1.2 tag, installed it, and I can confirm that tide's prompt now appears & updates properly. 🥳

**Thanks again!**

**Comment by IlanCosman** [comment]
Ah ok, yeah I'm not sure about PPAs on the Pi. Good to hear everything's working as expected on 3.1.2 😄

**Comment by a-glapinski** [comment]
I have this problem as well on macOS, despite using 3.1.2 fish version (installed through brew). I also have the problem that the prompt doesn't appear until any command is executed when opening new terminal tab/window (I use default macOS terminal app).
Here is the output of `tide bug-report`:
```
fish, version 3.1.2
tide, version 3.2.0
xterm-256color
```
Screenshot:
![obraz](https://user-images.githubusercontent.com/49104470/105091506-39726e80-5aa0-11eb-8c5b-0dd6baa6640a.png)

**Comment by IlanCosman** [comment]
The second problem is known, I don't really plan on tracking it down soon since it's so minor. You definitely shouldn't be having the first issue though 😕 I haven't gotten any other reports of 3.1.2 having that issue.

**Comment by afarrell** [comment]
> The second problem is known, I don't really plan on tracking it down soon since it's so minor. You definitely shouldn't be having the first issue though 😕 I haven't gotten any other reports of 3.1.2 having that issue.

I can confirm the same behaviour - takes about 2.5 seconds for the prompt to update.

fish, version 3.1.2
tide, version 3.2.0
xterm-256color

**Comment by IlanCosman** [comment]
> takes about 2.5 seconds for the prompt to update.

That's not this bug. This bug is that the prompt won't update at all unless you press something. Please open a new issue.

**Comment by IlanCosman** [comment]
Something fishy is going on here 😂 I just don't think this is an issue on 3.1.2. I haven't seen it at all, and why would it not have been reported earlier? Async has been out for months. Why would a 3.2 report be first, and only then I see 3.1.2 follow-up reports? That's seems very unlikely given the relative user percentages.

It's not that I don't believe you guys, but just that I can't reconcile your reports with my current understanding of things.

**Comment by a-glapinski** [comment]
I understand you 😄 I can only say that I've tried this plugin for the first time and I had this bug from the very beginning. Since this bug is quite annoying, I had to come back to previously used `mattgreen/lucid.fish` plugin which has async features as well. Not sure if it is possible, but maybe something has been broken after installing and removing `lucid.fish`?

**Comment by afarrell** [comment]
> Something fishy is going on here 😂 I just don't think this is an issue on 3.1.2. I haven't seen it at all, and why would it not have been reported earlier? Async has been out for months. Why would a 3.2 report be first, and only then I see 3.1.2 follow-up reports? That's seems very unlikely given the relative user percentages.
> 
> It's not that I don't believe you guys, but just that I can't reconcile your reports with my current understanding of things.

I can reproduce this on an older intel mac with Catalina and also on an m1 running iterm under Rosetta on Big Sur. In both cases the slowness was caused by calling the `brew prefix` command from a file in the fish conf.d folder. Something is causing all scripts in that folder to be reevaluated several times each time you enter a newline. This is hard to spot when it's fast, but the brew command was slow.

If you try fisher & tide on the macos Terminal you will see the title bar flashing by a bunch of commands. Hope this helps track it down! Maybe related to #60 ?

**Comment by IlanCosman** [comment]
Ok @afarrell, I think you're having a different issue than this one. When you `cd` into a new directory does the prompt eventually update without you pressing anything? I think you just have a slow fish startup time, which translates to slow async functionality.

**Comment by afarrell** [comment]
@IlanCosman yes the prompt does eventually update after a delay. I have no idea how, but I somehow read the bug description "until any key is pressed" as "after a delay"... Sorry, I'll open a separate ticket. It's not as simple as just a slow fish startup time. Thanks for this lovely prompt btw.

**Comment by IlanCosman** [comment]
Fixed: https://github.com/fish-shell/fish-shell/issues/7671
