### ISSUE TITLE
fish_git_prompt missing?

### ISSUE THREAD

**Issue by IngwiePhoenix** [IlanCosman/tide#73]
#### Describe the bug
I just installed Fisher, added Tide and... apparently I don't have a `fish_git_prompt`. Is there something else I have to install first?

#### Steps to reproduce

1. Install Fisher
2. Install Tide
3. See error

#### Expected behavior
A working, pretty prompt.

#### Screenshots

```
fish: Unknown command fish_git_prompt                                                                                                                                       ✔ ╱ 10:56:32
~/.config/fish/functions/_tide_item_git_prompt.fish (line 2):
    fish_git_prompt '%s'
    ^
in function “_tide_item_git_prompt”
        called on line 2 of file ~/.config/fish/functions/_tide_left_prompt.fish

in command substitution
        called on line 12 of file ~/.config/fish/functions/_tide_left_prompt.fish

in function “_tide_left_prompt”
        called on line 14 of file ~/.config/fish/functions/_tide_prompt.fish

in function “_tide_prompt”
        called on standard input

in command substitution
        called on standard input
```

#### Environment (please complete the following information)

- Operating System: Debian 10, WSL2
- Output of `tide bug-report`:

```console
fish, version 3.0.2
tide, version 3.2.0
xterm-256color
```

#### Additional context

Literally never touched any kinds of package managers on my shell, ever. This is my first one so I might not have done everything that I needed to do...

**Comment by jorgebucaran** [comment]
@IngwiePhoenix Your Fish doesn't have `fish_git_prompt` (https://github.com/fish-shell/fish-shell/issues/5586). You should upgrade to Fish 3.1 or later. 

If you can't do that for any reason, try wrapping the old `__fish_git_prompt`:

```fish
function fish_git_prompt
    __fish_git_prompt $argv
end 
```

Keep in mind that Tide [requires Fish 3.1](https://github.com/IlanCosman/tide#system-requirements).

**Comment by jorgebucaran** [comment]
Your Fish doesn't have `fish_git_prompt` (https://github.com/fish-shell/fish-shell/issues/5586). You should upgrade to Fish 3.1 or later. 

If you can't do that for any reason, try wrapping the old `__fish_git_prompt`:

```fish
function fish_git_prompt
    __fish_git_prompt $argv
end 
```

**Comment by IngwiePhoenix** [comment]
Turns out that APT just prioritized the old (3.0.2) over the newer (3.1.2) version. Forcefuly installing it fixed the issue. 

Had no idea this could happen. Well, now I know what `apt-cache policy` is for :)
