### ISSUE TITLE
Tide prints an error when on a path containing a space

### ISSUE THREAD

**Issue by toph-allen** [IlanCosman/tide#74]
#### Describe the bug

Whenever I'm in a directory with a space, Tide prints an error. Looks like it's a problem with the `test` function.

#### Steps to reproduce

```fish
mkdir "has space"
cd has\ space/
```

#### Expected behavior

No such error.

#### Screenshots

<img width="682" alt="Screen Shot 2021-01-13 at 9 20 33 AM" src="https://user-images.githubusercontent.com/3117884/104464133-993cb700-5580-11eb-92e1-64d74c25156c.png">

#### Environment (please complete the following information)

macOS 11.1; iTerm 2; fish 3.1.2
- Output of `tide bug-report`: 

```console
╰─test: Expected a combining operator like '-a' at index 5                    ─╯

~/.config/fish/functions/_tide_item_pwd.fish (line 1):
test -z thisPartIsFalse -o -e ~/has space/.bzr -o -e ~/has space/.citc -o -e ~/has space/.git -o -e ~/has space/.hg -o -e ~/has space/.node-version -o -e ~/has space/.python-version -o -e ~/has space/.ruby-version -o -e ~/has space/.shorten_folder_marker -o -e ~/has space/.svn -o -e ~/has space/.terraform -o -e ~/has space/Cargo.toml -o -e ~/has space/composer.json -o -e ~/has space/CVS -o -e ~/has space/go.mod -o -e ~/has space/package.json
^
in function '_tide_item_pwd'
	called on line 1 of file ~/.config/fish/functions/_tide_left_prompt.fish
in command substitution
	called on line 11 of file ~/.config/fish/functions/_tide_left_prompt.fish
in function '_tide_left_prompt'
	called on line 13 of file ~/.config/fish/functions/_tide_prompt.fish
in function '_tide_prompt'
in command substitution

(Type 'help test' for related documentation)
```

#### Additional context

I *think* this could be fixed by quoting every argument to the `test` call (per [this issue](https://github.com/fish-shell/fish-shell/issues/5186)), but I'm not sure.

**Comment by IlanCosman** [comment]
Great catch! Should have noticed that myself. I'll get on this right away 😄

**Comment by IlanCosman** [comment]
Alright, still working on this, but the real moral of the story is that spaces are the devil and you should feel bad for using them 😂 

Simply putting quotes around the argument doesn't work unfortunately, because then `~` wont be expanded into `/home/yourUser`. Instead I tried `string escape`ing, which is kind of working, but it wrecks the truncation logic. _Sigh_

**Comment by IlanCosman** [comment]
I mean, that probably would work? But it's fragile and kind of gross no offense. There are tools like `string escape` to handle this, I just need to figure out the correct way of using them.

**Comment by IlanCosman** [comment]
Nice to know that even the greats can have these issues: https://github.com/romkatv/powerlevel10k/issues/1220

**Comment by jorgebucaran** [comment]
Of course, but you do have a performance goal. If you think you can manage without any cheap tricks, then even better! 💯

**Comment by toph-allen** [comment]
I'm just spitballing here, and not that familiar with the truncation logic or how the path is being processed, but would it be possible to expand the tilde and *then* quote everything? Or will that also wreck performance?
