### ISSUE TITLE
Remove Pure style?

### ISSUE THREAD

**Issue by IlanCosman** [IlanCosman/tide#77]
Originally, I implemented the Pure style simply because Powerlevel10k has it, and because I could. Later, I thought it made sense to have a simpler prompt style that wouldn't slow down even in large git repositories, unlike the other styles.

However, that reason is gone now that Tide is asynchronous. Lean is now equally fast and far more informative. Therefore the only justification I can think of for Pure style existing is that it might make converting to Tide easier for those people coming from Pure. I don't think that's a very strong argument especially when Lean is so similar.

Thus, I'd like to remove the burden, however small, of ensuring that Pure style functions correctly.

However, I don't have any statistics on Tide users, so perhaps Pure style is actually widely used. Please react with a 👎 on this issue if you'd prefer that Tide keep Pure style.  I'll leave this up for a week and then act accordingly.

**Comment by Princesseuh** [comment]
I use the Pure style but wouldn't mind it being removed if feature parity (including in the configuration tool) is reached. For instance, right now the configuration tool doesn't allow you to put the `Non-permanent content location` on the left like it does with the Pure style

Personally, my main reason for using the Pure style is that the default colors matches my terminal color scheme and I didn't want to bother configuring the colors on the Lean style, I'd be cool if that was easily configurable too

**Comment by IlanCosman** [comment]
Closed in v4

**Comment by Debilski** [comment]
Hmm, is there a pointer as to how I can configure Lean to be like Pure again? I cannot really tell what it is, but there is something about the Lean style that I find off-putting (maybe the colours or the bold-style in the path), a feeling that I don’t have with the Pure style with its more toned-down colours.

**Comment by IlanCosman** [comment]
Yah sure, you can tone down the colors, and remove first and set `tide_pwd_anchors` to empty. You won't be able to recreate the old simplified git style, but you can tone down the colors there too. Everything you need is in the [configuration docs](https://github.com/IlanCosman/tide/blob/main/docs/Configuration.md).

If you are really, truly, attached to Pure though, it's probably best to just use that. Give it some time though, Lean is pretty nice 😂

Ultimately I'm trying to move Tide in a more "Fish" direction. i.e being opinionated, for example with the git situation. Trying to be as configurable as Powerlevel10k won't be good for the long-term health of the project and it's maintainability.

**Comment by Debilski** [comment]
Ah, well, the git style was the one that I changed in Pure anyway to give more information. :) That would have been my main criticism with it. Now I just need to figure out what the old colour names were and maybe I can make Lean work for me as well (or get used to it).

In general I appreciate the opinionated direction, though, as long as I can still write my own item snippets as easily as before, so I won’t complain. :)
