### ISSUE TITLE
Allow color configuration using terminal colors

### ISSUE THREAD

**Issue by IlanCosman** [IlanCosman/tide#79]
#### Is your feature request related to a problem? Please describe

@Princesseuh in #77:
> Personally, my main reason for using the Pure style is that the default colors matches my terminal color scheme and I didn't want to bother configuring the colors on the Lean style, I'd be cool if that was easily configurable too

#### Describe the solution you'd like

Apparently Powerlevel10k [does this](https://github.com/romkatv/powerlevel10k#change-the-color-palette-used-by-your-terminal):
> When you change the terminal color palette, it usually affects only the first 16 colors, numbered from 0 to 15. In order to see any effect on Powerlevel10k prompt, you need to use prompt style that utilizes these low-numbered colors. Type p10k configure and select Rainbow, Lean → 8 colors or Pure → Original. Other styles use higher-numbered colors, so they look the same in any terminal color palette.

Tide should do the same by using named colors in the rainbow style, and offering an 8-color mode for Lean.

**Comment by IlanCosman** [comment]
Hi @romkatv 👋 I'm wondering about your philosophy as to when to use terminal colors. In Powerlevel10k, Rainbow has it by default, Lean lets you choose, and Classic doesn't have that option at all. Could you explain your decisions there? I want to learn from the master 🙇

**Comment by romkatv** [comment]
There is no rhyme or reason to it.

- Lean with 8 colors uses only the low-numbered colors, so every prompt character is affected by the terminal color scheme.
- Lean with 256, Classic and Pure Snazzy use only the high-numbered colors, so no prompt characters are affected by the terminal color scheme.
- Rainbow uses a mix of low- and high-numbered colors.

It's hard to do any worse than this.

**Comment by IlanCosman** [comment]
Closed in v4
