### ISSUE TITLE
Custom command item and color prompt prefix?

### ISSUE THREAD

**Issue by Barbarossa93** [IlanCosman/tide#83]
#### Is your feature request related to a problem? Please describe

It would be nice to be able to create a custom command item so that I can display info in my prompt that isn't available as one of the predefined ones. In my case, I really want a taskwarrior item that tells me how many active tasks I have similar to how p10k for zsh does it.
Additionally, I noticed that its possible to include a prefix (`tide_left_prompt_prefix`). While that is great, I can't change its foreground color. It'd be nice to add that variable as well
#### Describe the solution you'd like

Either a taskwarrior item or a custom command item would be great. Not sure how the custom command item would work in practice to be honest. I recently switched from zsh myself.

Adding another option for prefix foreground color should be straightforward I think. Something like `tide_left_prompt_prefix_color` would be fantastic

**Comment by IlanCosman** [comment]
Have you taken a look at the https://github.com/IlanCosman/tide#extensible feature demonstration? What you're suggesting should already be doable.

**Comment by Barbarossa93** [comment]
Oh! 🤦🏾‍

My bad, that slipped past me. Maybe a section in configuration.md regarding this would be nice? Totally missed it by being absorbed over there

**Comment by IlanCosman** [comment]
No worries 😄

Yah, adding it to the configuration doc might be a good idea. Also, if you do end up creating a taskwarrior item, I'd really appreciate a PR 😄 Other people might find that item useful.

**Comment by Barbarossa93** [comment]
For sure! I'm new to fish, so I need to get used to it's syntax first. I should be able to whip up a simple little taskwarrior item before too long though. I'll want to double check with the internals of p10k as well to make sure its functionally the same.

Regarding the prefix color, I can't seem to get it to work? I tried `set -U tide_left_prompt_prefix_color blue` as well as `set -U tide_left_prompt_prefix_fg_color blue`. Looks Like I actually need to define the function? Not sure how to do that so that it colors the prefix. Does this work?:
```
function tide_left_prompt_prefix_color
    set color blue
    tide_left_prompt_prefix
end
```
Not sure how to make it accept colors if I decide to change it later

**Comment by IlanCosman** [comment]
Prefix is the thing the comes before the whole prompt. It's entirely unrelated to what you're trying to do. 

As the extensible feature demonstration shows, all you need to do to fully define a new item is to create a function, create a `bg_color` for it, and then add it to one of your prompt's sides. These require specific naming schemes.

So for you it would look something like this:

```fish
function _tide_item_taskwarrior
    # Do some taskwarrior stuff
end
```

Then you'd define the background color for the item:
```console
set -U tide_taskwarrior_bg_color blue
```

and then add it to the beginning of your right prompt lets say:
```console
set --prepend tide_right_prompt_items taskwarrior
```

**Comment by Barbarossa93** [comment]
Sorry, there is two things I'm doing/requesting help with here: creating the taskwarrior item and setting the color for the left_prompt prefix. I probably should have made two separate issues for clarity but I didn't want to spam multiple issues. I have a basic taskwarrior item figured out, I just need to fix it up some more before a PR. What I'm having trouble with is setting the foreground color for the prefix. Was the function I defined previously in the right direction?

**Comment by IlanCosman** [comment]
The prefix doesn't have a color. It uses the same color as whatever item is first printed such that it blends together nicely. That's almost always the pwd item, or perhaps the os item sometimes.

**Comment by Barbarossa93** [comment]
Strange, the first item is pwd and its cyan, but the prefix is just white. Here's a screenshot:
![1611686776](https://user-images.githubusercontent.com/57952969/105890142-f69f2200-5fdc-11eb-9b34-e4eabe39cc24.png)
Personally, I'm not a fan of the white and I want to make it blue instead. There's no way to do that?

**Comment by IlanCosman** [comment]
Could you post the output of `tide bug-report -v`?

**Comment by Barbarossa93** [comment]
Here ya go:
```
fish, version 3.1.2
tide, version 3.2.0
xterm-termite

__fish_git_prompt_char_dirtystate *
__fish_git_prompt_char_stagedstate *
__fish_git_prompt_char_stashstate  ≡
__fish_git_prompt_char_stateseparator 
__fish_git_prompt_char_upstream_ahead  ⇡
__fish_git_prompt_char_upstream_behind  ⇣
__fish_git_prompt_char_upstream_diverged  ⇡⇣
__fish_git_prompt_char_upstream_equal 
__fish_git_prompt_color_branch brblack
__fish_git_prompt_color_dirtystate brblack
__fish_git_prompt_color_stagedstate brblack
__fish_git_prompt_color_stashstate cyan
__fish_git_prompt_color_upstream cyan
__fish_git_prompt_showdirtystate true
__fish_git_prompt_showstashstate true
__fish_git_prompt_showupstream true
tide_cmd_duration_bg_color normal
tide_cmd_duration_color yellow
tide_cmd_duration_decimals 0
tide_cmd_duration_icon 
tide_cmd_duration_threshold 3000
tide_context_always_display false
tide_context_bg_color normal
tide_context_default_color D7AF87
tide_context_root_color D7AF00
tide_context_ssh_color D7AF87
tide_git_prompt_bg_color normal
tide_jobs_bg_color normal
tide_jobs_color 5FAF00
tide_jobs_icon 
tide_left_prompt_frame_color 6C6C6C
tide_left_prompt_frame_enabled false
tide_left_prompt_item_separator_diff_color  
tide_left_prompt_item_separator_same_color  
tide_left_prompt_item_separator_same_color_color 949494
tide_left_prompt_items pwd git_prompt prompt_char
tide_left_prompt_pad_items false
tide_left_prompt_prefix  
tide_left_prompt_suffix  
tide_nvm_bg_color normal
tide_nvm_color 00AFAF
tide_nvm_default_node 
tide_nvm_icon ⬢
tide_os_bg_color normal
tide_os_color normal
tide_print_newline_before_prompt true
tide_prompt_char_bg_color normal
tide_prompt_char_failure_color red
tide_prompt_char_icon ❯
tide_prompt_char_success_color magenta
tide_prompt_char_vi_default_icon ❮
tide_prompt_char_vi_insert_icon ❯
tide_prompt_char_vi_replace_icon ❮
tide_prompt_char_vi_visual_icon ❮
tide_prompt_connection_color 6C6C6C
tide_prompt_connection_icon 
tide_pwd_anchors 
tide_pwd_bg_color normal
tide_pwd_color_anchors 00AFFF
tide_pwd_color_dirs blue
tide_pwd_color_truncated_dirs 8787AF
tide_pwd_dir_icon 
tide_pwd_home_icon 
tide_pwd_markers 
tide_pwd_truncate_margin 10
tide_pwd_unwritable_icon 
tide_right_prompt_frame_color 6C6C6C
tide_right_prompt_frame_enabled false
tide_right_prompt_item_separator_diff_color  
tide_right_prompt_item_separator_same_color  
tide_right_prompt_item_separator_same_color_color 949494
tide_right_prompt_items cmd_duration virtual_env taskwarrior
tide_right_prompt_pad_items false
tide_right_prompt_prefix  
tide_right_prompt_suffix 
tide_rust_bg_color normal
tide_rust_color 00AFAF
tide_rust_icon 
tide_rust_verbose_version true
tide_status_always_display false
tide_status_failure_bg_color normal
tide_status_failure_color D70000
tide_status_failure_icon ✘
tide_status_success_bg_color normal
tide_status_success_color 5FAF00
tide_status_success_icon ✔
tide_time_bg_color normal
tide_time_color 6C6C6C
tide_time_format 
tide_vi_mode_default_bg_color 
tide_vi_mode_default_color 
tide_vi_mode_default_icon 
tide_vi_mode_insert_bg_color 
tide_vi_mode_insert_color 
tide_vi_mode_insert_icon 
tide_vi_mode_replace_bg_color 
tide_vi_mode_replace_color 
tide_vi_mode_replace_icon 
tide_vi_mode_visual_bg_color 
tide_vi_mode_visual_color 
tide_vi_mode_visual_icon 
tide_virtual_env_bg_color normal
tide_virtual_env_color brblack
tide_virtual_env_display_mode venvName
tide_virtual_env_icon 
```

**Comment by IlanCosman** [comment]
Ah ok. You're using the prefix in an unintended manner. I should have been more clear: the prefix uses the _background_ color of the first item printed. Since your first item has a `bg_color` of normal, the prefix will have no color. 

What you should do, if you want to display an icon before each prompt, is just create a new item to do so.

**Comment by Barbarossa93** [comment]
Ahhhh, of course! So simple. Thanks for working through this with me! And thanks for creating/sharing tide! As a former zsh/p10k user, it's exactly what I was looking for ☺️
