### ISSUE TITLE
Add transient prompt feature

### ISSUE THREAD

**Issue by IlanCosman** [IlanCosman/tide#85]
#### Is your feature request related to a problem? Please describe

A multi-line prompt is nice to use, but takes up a ton of scroll-back history.

#### Describe the solution you'd like

The prompt should optionally change right before hitting enter to become one line. Powerlevel10k [has this feature](https://github.com/romkatv/powerlevel10k/#transient-prompt) and it has been requested in the past.

**Comment by pusewicz** [comment]
This would be *sick*!

**Comment by matallui** [comment]
Yes, please!

**Comment by branchvincent** [comment]
for visibility, see https://github.com/fish-shell/fish-shell/issues/7602 (and the linked PR which addresses it)

**Comment by ahillio** [comment]
fish-shell/fish-shell#7602 is closed now.  It references a PR that was merged and a couple other closed issues.

Does that mean this is waiting on a new release of fish-shell to be available?  Does `Tide` need https://github.com/fish-shell/fish-shell/milestone/30 to be completed for the transient prompt to work in Tide?

**Comment by IlanCosman** [comment]
@ahillio Yes, Fish 3.4 would have to come out before Tide adds transient prompt. There is also [a bug with repaints](https://github.com/fish-shell/fish-shell/issues/8418) that would need to get fixed beforehand. Rest assured that Tide will add this feature when it is ready to be added 😄

**Comment by Crocmagnon** [comment]
Oh wow just found this issue. Yes please! 😀 can't wait for fish 3.4 to be release ^^

**Comment by pusewicz** [comment]
@IlanCosman Sooooo… Can this be implemented? 👯

**Comment by Crocmagnon** [comment]
The bug mentioned by Ilan is still not fixed: https://github.com/fish-shell/fish-shell/issues/8418

I guess we need to wait for this one too :)

**Comment by ahillio** [comment]
Interesting... that issue https://github.com/fish-shell/fish-shell/issues/8418 is referenced by another https://github.com/JanDeDobbeleer/oh-my-posh/issues/2467 and apparently oh-my-posh makes it possible to do a transient prompt in fish. I wonder if their method is something that could be used here?

**Comment by asportnoy** [comment]
Probably worth a shot.

**Comment by SolidRhino** [comment]
👍 for this feature 😄

**Comment by k-kedzierski** [comment]
Still waiting for this one 🙏

**Comment by zzhaolei** [comment]
I wrote [this](https://github.com/zzhaolei/transient-prompt.fish), It works fine for me:

```fish
if not type --query __fish_prompt
    functions --copy fish_prompt __fish_prompt
    functions --erase fish_prompt
end

function fish_prompt
    set --function default_prompt "\e[1;32m❯\e[0m "

    if test "$TRANSIENT" = 1
        or test "$TRANSIENT" = 2
        printf \e\[0J # clear from cursor to end of screen
        if type --query transient_prompt_func
            transient_prompt_func
        else
            printf $default_prompt
        end

        if test "$TRANSIENT" = 2
            set --global TRANSIENT 0
            commandline --function repaint
        end
    else
        if type --query __fish_prompt
            __fish_prompt
        else
            printf $default_prompt
        end
    end
end

# transience related functions
function reset-transient --on-event fish_postexec
    set --global TRANSIENT 0
end

function transient_execute
    if commandline --is-valid
        set --global TRANSIENT 1
        commandline --function repaint
    else if test "$(commandline -b)" = "" # fix empty enter
        set --global TRANSIENT 2
        commandline --function repaint
    else
        set --global TRANSIENT 0
    end
    commandline --function execute
end

bind -M insert \r transient_execute # when enable vi keybinding use this bind
# bind \r transient_execute # disable vi keybinding use this bind
```

**Comment by real-or-random** [comment]
> I wrote [this](https://github.com/zzhaolei/transient-prompt.fish)

I installed the plugin and it works like a charm so far. :)

**Comment by SolidRhino** [comment]
> I wrote [this](https://github.com/zzhaolei/transient-prompt.fish), It works fine for me:
> 
> ```fish
> if not type --query __fish_prompt
>     functions --copy fish_prompt __fish_prompt
>     functions --erase fish_prompt
> end
> 
> function fish_prompt
>     set --function default_prompt (set_color 5FD700)"❯ "(set_color normal)
> 
>     if test "$TRANSIENT" = 1
>         or test "$TRANSIENT" = 2
>         printf \e\[0J # clear from cursor to end of screen
>         if type --query transient_prompt_func
>             transient_prompt_func
>         else
>             printf $default_prompt
>         end
> 
>         if test "$TRANSIENT" = 2
>             set --global TRANSIENT 0
>             commandline --function repaint
>         end
>     else
>         if type --query __fish_prompt
>             __fish_prompt
>         else
>             printf $default_prompt
>         end
>     end
> end
> 
> # transience related functions
> function reset-transient --on-event fish_postexec
>     set --global TRANSIENT 0
> end
> 
> function transient_execute
>     if commandline --is-valid
>         set --global TRANSIENT 1
>         commandline --function repaint
>     else if test "$(commandline -b)" = "" # fix empty enter
>         set --global TRANSIENT 2
>         commandline --function repaint
>     else
>         set --global TRANSIENT 0
>     end
>     commandline --function execute
> end
> 
> bind -M insert \r transient_execute # when enable vi keybinding use this bind
> # bind \r transient_execute # disable vi keybinding use this bind
> ```

This is not working for me. I'm using macOS. I see no difference.

**Comment by m-messiah** [comment]
I'm using MacOS. @SolidRhino the last line is important - if you are not using vi keybinding - you should swap comments and it would work as a Charm.

The other problem is about right_prompt - @zzhaolei do you know if it could be possible to remove right prompt as well?

**Comment by zzhaolei** [comment]
> This is not working for me. I'm using macOS. I see no difference.

As @m-messiah  said, "f you are not using vi keybinding - you should swap comments and it would work"

```fish
# bind -M insert \r transient_execute  # when enable vi keybinding use this bind
bind \r transient_execute  # disable vi keybinding use this bind
```

**Comment by zzhaolei** [comment]
@SolidRhino try [this](https://github.com/zzhaolei/transient-prompt.fish/blob/main/conf.d/transient.fish)

**Comment by SolidRhino** [comment]
@zzhaolei 

The last lines of the code are now:

```
#bind -M insert \r transient_execute
#bind -M insert \cc ctrl_c_transient_execute
bind \r transient_execute
bind \cc ctrl_c_transient_execute
```

But still have this prompt:
<img width="1434" alt="afbeelding" src="https://user-images.githubusercontent.com/222683/215785005-0507b75c-f061-4edd-890b-0a2789ad0f27.png">

**Comment by zzhaolei** [comment]
@SolidRhino @m-messiah 

This is what is said in [issue](https://github.com/fish-shell/fish-shell/issues/8418), 

We can only clear the character before the cursor.

![image](https://user-images.githubusercontent.com/17561793/215796304-c1b25921-0072-4efc-ab66-e58a376934bc.png)
Relative to the screenshot. 

Currently, the red part can be clear, but the green part cannot.

**Comment by zzhaolei** [comment]
@SolidRhino @m-messiah 

Try [this](https://github.com/zzhaolei/transient-prompt.fish/blob/main/conf.d/transient.fish)

This commit makes `fish_right_prompt` transient.

![image](https://user-images.githubusercontent.com/17561793/215935109-5567c047-25bf-4bb0-9be8-f99bdd3b4c7b.png)

**Comment by Naadiyaar** [comment]
This is literary the oldest open issue and so far lots of problems had to be solved to reach this state. now that https://github.com/IlanCosman/tide/issues/85#issuecomment-1409875980 works too, can we expect a PR :)

**Comment by IlanCosman** [comment]
> This is literary the oldest open issue and so far lots of problems had to be solved to reach this state. now that [#85 (comment)](https://github.com/IlanCosman/tide/issues/85#issuecomment-1409875980) works too, can we expect a PR :)

@Naadiyaar  Sure, cooked something up. Try the `transient-prompt` branch and `set -U tide_transient_enabled true`.

**Comment by Naadiyaar** [comment]
> > This is literary the oldest open issue and so far lots of problems had to be solved to reach this state. now that [#85 (comment)](https://github.com/IlanCosman/tide/issues/85#issuecomment-1409875980) works too, can we expect a PR :)
> 
> @Naadiyaar Sure, cooked something up. Try the `transient-prompt` branch and `set -U tide_transient_enabled true`.

Awesome, tried it right now and it works flawlessly with icons, frames, right prompt... enabled, good work.

**Comment by jacobwhall** [comment]
> it works flawlessly with icons, frames, right prompt...

Same here, thanks for working on this! I'll report any issues here should I run into them.

**Comment by IlanCosman** [comment]
v6 released
