### ISSUE TITLE
_tide_detect_os: command not found

### ISSUE THREAD

**Issue by JSchrtke** [IlanCosman/tide#86]
#### Describe the bug

When install tide with `fisher install IlanCosman/tide`, an error is returned during the installation:

```console
_tide_detect_os: command not found
~/.config/fish/functions/fish_prompt.fish (line 1): 
_tide_detect_os
^
from sourcing file ~/.config/fish/functions/fish_prompt.fish
	called on line 177 of file ~/.config/fish/functions/fisher.fish
in function 'fisher' with arguments 'install IlanCosman/tide'
```

#### Steps to reproduce

Without having the tide prompt installed, run `fisher install IlanCosman/tide`

#### Expected behavior

The installation finishes without any errors.

#### Environment (please complete the following information)

- Operating System: OS: Ubuntu 20.04.2 LTS x86_64
- Output of `tide bug-report`:
```console
fish, version 3.1.0
tide, version 4.0.0
xterm-kitty
```

**Comment by IlanCosman** [comment]
This doesn't really make sense to me, v4 shouldn't have changed anything with detect_os afaik. Can you try reproducing this in a perfectly clean fish instance? Run `sh -c 'env HOME=$(mktemp -d) fish -C "curl -sL https://git.io/fisher | source && fisher install jorgebucaran/fisher ilancosman/tide"'`.

**Comment by JSchrtke** [comment]
Yeah, that works fine, without any errors. Weird. Well, it's something in my config then, although I'm not sure why. This is a really fresh install, I'm just starting to configure the system, so there shouldn't be to much weird stuff going on.

**Comment by JSchrtke** [comment]
It's not v4, v3.2.0 has the same issue now. It did not do this when I originally install Tide yesterday for the first time.
I also tried installing v3.2.0 clean, as per your instruction earlier, and that works, as does v4.

I think I must have broken something in a config somewhere.

**Comment by JSchrtke** [comment]
Oh, by the way, besides the installer complaining, it still completes. I should have maybe mentioned that earlier. The prompt seems to work just fine as well, at least I haven't found any issue so far

**Comment by JSchrtke** [comment]
Right, I've just uninstalled fish and all it's related config and reinstalled. Installing the prompt worked just fine as well, there was clearly just something broken on my end. Sorry for the inconvenience.
This can be closed as far as I'm concerned.

**Comment by IlanCosman** [comment]
No problem, thanks for submitting a ticket, not everyone goes to the effort 👍

**Comment by JSchrtke** [comment]
Well, sure, should have cleary done some more testing before doing so though.
Anyway, thanks for making the prompt, it's truly awesome. I tried a whole bunch, but this one is just, well, the best. From the config wizard to just being ripping fast. Very nice :heart:
