### ISSUE TITLE
Add virtualenv support

### ISSUE THREAD

**Issue by xolve** [IlanCosman/tide#9]
**Is your feature request related to a problem? Please describe.**
Python virtualenv right now is displayed as name of virtualenv in parenthesis and tide prompt follows on new line after that. I am using tide with pormpt on a new line.

**Describe the solution you'd like**
It should be integrated with prompt along with its own syntax coloring.

**Additional context**
How `bobthefish` has it, but virtualenv being mentioned twice is redundant.
![Screenshot_20200628_225712](https://user-images.githubusercontent.com/520649/85954100-bcac6580-b992-11ea-8460-602ceeba5668.png)

**Comment by IlanCosman** [comment]
Done! You can read about the configuration options at <https://github.com/IlanCosman/tide#virtual_env>

**Comment by xolve** [comment]
Thanks :smile:

**Comment by xolve** [comment]
@IlanCosman 
IMHO usable default should be to set `tide_virtual_env_display` to `venvName`.
Also, the name of the environment is quite as important as current directory or git branch. Would you prefer to keep it on left side along with rest of prompt.

Can add similar extensions for nvm.

P.S. Would make for a good first issue to solve.

**Comment by IlanCosman** [comment]
Given how popular and well thought-out powerlevel10k is, I am hesitant to depart from it's shadow. p10k uses projectName and puts virtual env on the right side. 

I agree with both of these things. Given that a virtual environment is often named .venv and is usually used only for one project, I think that projectName is the better default. I have also never used Python before this in any real capacity, so it would certainly not belong on _my_ left prompt. Only essentially universal things belong on the left side by default.

Don't forget that you can modify _your_ prompt! Just remove `virtual_env` from `tide_right_prompt_items` and put it in `tide_left_prompt_items`.

I would welcome a new issue (and a pull request if you're willing) for nvm. 😄
