### ISSUE TITLE
Add PHP, Laravel, Laravel sail, Docker and NPM (yarn) (version) detection

### ISSUE THREAD

**Issue by SolidRhino** [IlanCosman/tide#91]
Add NPM (yarn), PHP, Laravel version detection.
Add Docker composer and use of Laravel sail detection.
And add the info to the prompt.

Like this:
![CleanShot 2021-02-12 at 21 22 31@2x](https://user-images.githubusercontent.com/222683/107818990-b8458900-6d78-11eb-9e1d-5c7a318a9096.png)

**Comment by IlanCosman** [comment]
Thanks for opening this request 😄 Docker for certain, PHP sure, NPM/Yarn sure, Laravel idk. I'm willing to accept a PR for it, but I don't think I'll be making one myself for now. Laravel just doesn't have the nearly the same reach as the others you requested. This'll be a v4.2 issue, so not soon, but not too far either 😂

**Comment by chvolkmann** [comment]
@SolidRhino Could you elaborate on the Docker Compose part? I'm not sure which information would be useful to display there.

**Comment by IlanCosman** [comment]
Also, there is no npm/yarn segment in powerlevel10k. What you're referring to is the node item
