### ISSUE TITLE
Icons not displaying

### ISSUE THREAD

**Issue by rr326** [IlanCosman/tide#94]
#### Describe the bug

When I installed tide, I don't get icons / fancy lines = just a question mark in a box (see screenshot below)
(I have p10k working in zsh on Macos 11.2 in iterm2 so I know it should work.)
I HAVE installed the fonts, and restarted my shell. 

Any idea how I can debug?

#### Steps to reproduce

(in tide configuration)

#### Expected behavior

See screenshot

#### Screenshots

![image](https://user-images.githubusercontent.com/1766391/107882227-018ef900-6e9d-11eb-8af3-25e78a89a2be.png)

#### Environment (please complete the following information)

- Operating System: Darwin ross-imac-pro-7.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

- Output of `tide bug-report`

```console
fish, version 3.1.2
tide, version 4.0.0
xterm-256color
```

**Comment by IlanCosman** [comment]
Just to make sure: You are using iterm2, with the MesloLGS NF font selected in your Terminal? Can you switch to zsh, see that the glyphs display correctly, and then back to Fish, where they don't? I would be absolutely shocked if that was the case.

**Comment by rr326** [comment]
That was it! I think I had changed the default font, but not the 'non-text' font.  And event that didn't work - until I restarted my terminal. 

I'll put the solution here for iTerm2 users.

* Go to Preferences/Profiles/Text
* For "Non-Ascii Font" select "MesloLGS NF"
* Restart your terminal, just in case

![image](https://user-images.githubusercontent.com/1766391/107883039-44eb6680-6ea1-11eb-9507-fd0b6f2fc1c1.png)


And btw @IlanCosman - thank you so much for the enormous effort it must have taken to port P10k. I appreciate it.

**Comment by IlanCosman** [comment]
@rr326 Glad to hear you solved the problem! I didn't even realize you could have a different font for ascii vs non-ascii characters 😄

Sorry if I was brusque earlier. Font questions are a bit annoying to deal with since it's never really a Tide bug. It's definitely something I should have in an FAQ and/or canned response.

> thank you so much for the enormous effort it must have taken to port P10k

Thanks for the kind words ❤️ The work I've put into Tide makes it clear to me how absolutely insane Powerlevel10k is 😂
