### ISSUE TITLE
virtualenv is displayed incorrectly for poetry and conda

### ISSUE THREAD

**Issue by chvolkmann** [IlanCosman/tide#97]
When using [poetry](https://python-poetry.org/) to manage virtualenvs, this is what tide displays

![image](https://user-images.githubusercontent.com/15794071/108014645-a0873280-700e-11eb-9360-08fdd85b96cd.png)

The `virtualenvs` should be the name of my virtualenv.

```bash
echo $VIRTUAL_ENV
/home/user/.cache/pypoetry/virtualenvs/myproject-j_EVlIcP-py3.8
```

So the venv should be displayed as `myproject-j_EVlIcP-py3.8` or `myproject`. Something similar could be implemented for [conda](https://docs.conda.io/en/latest/) users. Here, `CONDA_DEFAULT_ENV` should be used instead of `VIRTUAL_ENV`.

I'll cook up a pull request for [`_tide_item_virtual_env.fish`](https://github.com/IlanCosman/tide/blob/main/functions/_tide_item_virtual_env.fish) in a bit!

**Comment by IlanCosman** [comment]
This [is the intended behavior](https://github.com/IlanCosman/tide/blob/main/docs/Configuration.md#virtual_env), though perhaps it should be changed.

**Comment by IlanCosman** [comment]
@chvolkmann I've made the virtual_env item a bit smarter, so that poetry won't have this issue. Feel free to open a new issue for conda 😄
